//! GENERATED by behaviour/gen.py from behaviour/ids.json — do not edit by hand.
//!
//! Id tables of the 8-byte behaviour record (see `behaviour/README.md`).
//! Every function here is a plain `match`; unknown inputs map to 0 (n/a)
//! or `ALG_OTHER`, never to a panic.

#![allow(dead_code)]

pub const TABLE_VERSION: u32 = 1;

// ── src (byte 0) ─────────────────────────────────────────────────────────
pub const SRC_KMIP_DATA: u8 = 1;
pub const SRC_KMIP_ADMIN: u8 = 2;
pub const SRC_POLICY: u8 = 3;
pub const SRC_P11_REMOTING_GRPC: u8 = 4;
pub const SRC_P11_REMOTING_REST: u8 = 5;
pub const SRC_P11_LOCAL: u8 = 6;
pub const SRC_TLS: u8 = 7;
pub const SRC_AUTH: u8 = 8;

/// `src` id for a `PQC_BEHAVIOUR_SRC` value (the three PKCS#11 producers).
pub fn src_from_name(name: &str) -> Option<u8> {
    match name {
        "kmip-data" => Some(1),
        "kmip-admin" => Some(2),
        "policy" => Some(3),
        "p11-remoting-grpc" => Some(4),
        "p11-remoting-rest" => Some(5),
        "p11-local" => Some(6),
        "tls" => Some(7),
        "auth" => Some(8),
        _ => None,
    }
}

// ── op (byte 1), namespace `kmip` ──────────────────────────────────────
pub const OP_KMIP_CREATE: u8 = 1;
pub const OP_KMIP_CREATEKEYPAIR: u8 = 2;
pub const OP_KMIP_REGISTER: u8 = 3;
pub const OP_KMIP_REKEY: u8 = 4;
pub const OP_KMIP_DERIVEKEY: u8 = 5;
pub const OP_KMIP_CERTIFY: u8 = 6;
pub const OP_KMIP_RECERTIFY: u8 = 7;
pub const OP_KMIP_LOCATE: u8 = 8;
pub const OP_KMIP_CHECK: u8 = 9;
pub const OP_KMIP_GET: u8 = 10;
pub const OP_KMIP_GETATTRIBUTES: u8 = 11;
pub const OP_KMIP_GETATTRIBUTELIST: u8 = 12;
pub const OP_KMIP_ADDATTRIBUTE: u8 = 13;
pub const OP_KMIP_MODIFYATTRIBUTE: u8 = 14;
pub const OP_KMIP_DELETEATTRIBUTE: u8 = 15;
pub const OP_KMIP_OBTAINLEASE: u8 = 16;
pub const OP_KMIP_GETUSAGEALLOCATION: u8 = 17;
pub const OP_KMIP_ACTIVATE: u8 = 18;
pub const OP_KMIP_REVOKE: u8 = 19;
pub const OP_KMIP_DESTROY: u8 = 20;
pub const OP_KMIP_ARCHIVE: u8 = 21;
pub const OP_KMIP_RECOVER: u8 = 22;
pub const OP_KMIP_VALIDATE: u8 = 23;
pub const OP_KMIP_QUERY: u8 = 24;
pub const OP_KMIP_CANCEL: u8 = 25;
pub const OP_KMIP_POLL: u8 = 26;
pub const OP_KMIP_NOTIFY: u8 = 27;
pub const OP_KMIP_PUT: u8 = 28;
pub const OP_KMIP_REKEYKEYPAIR: u8 = 29;
pub const OP_KMIP_DISCOVERVERSIONS: u8 = 30;
pub const OP_KMIP_ENCRYPT: u8 = 31;
pub const OP_KMIP_DECRYPT: u8 = 32;
pub const OP_KMIP_SIGN: u8 = 33;
pub const OP_KMIP_SIGNATUREVERIFY: u8 = 34;
pub const OP_KMIP_MAC: u8 = 35;
pub const OP_KMIP_MACVERIFY: u8 = 36;
pub const OP_KMIP_RNGRETRIEVE: u8 = 37;
pub const OP_KMIP_RNGSEED: u8 = 38;
pub const OP_KMIP_HASH: u8 = 39;
pub const OP_KMIP_CREATESPLITKEY: u8 = 40;
pub const OP_KMIP_JOINSPLITKEY: u8 = 41;
pub const OP_KMIP_IMPORT: u8 = 42;
pub const OP_KMIP_EXPORT: u8 = 43;
pub const OP_KMIP_LOG: u8 = 44;
pub const OP_KMIP_LOGIN: u8 = 45;
pub const OP_KMIP_LOGOUT: u8 = 46;
pub const OP_KMIP_DELEGATEDLOGIN: u8 = 47;
pub const OP_KMIP_ADJUSTATTRIBUTE: u8 = 48;
pub const OP_KMIP_SETATTRIBUTE: u8 = 49;
pub const OP_KMIP_SETENDPOINTROLE: u8 = 50;
pub const OP_KMIP_PKCS11: u8 = 51;
pub const OP_KMIP_INTEROP: u8 = 52;
pub const OP_KMIP_REPROVISION: u8 = 53;
pub const OP_KMIP_SETDEFAULTS: u8 = 54;
pub const OP_KMIP_SETCONSTRAINTS: u8 = 55;
pub const OP_KMIP_GETCONSTRAINTS: u8 = 56;
pub const OP_KMIP_QUERYASYNCHRONOUSREQUESTS: u8 = 57;
pub const OP_KMIP_PROCESS: u8 = 58;
pub const OP_KMIP_PING: u8 = 59;
pub const OP_KMIP_CREATEGROUP: u8 = 60;
pub const OP_KMIP_OBLITERATE: u8 = 61;
pub const OP_KMIP_CREATEUSER: u8 = 62;
pub const OP_KMIP_CREATECREDENTIAL: u8 = 63;
pub const OP_KMIP_DEACTIVATE: u8 = 64;
pub const OP_KMIP_ENCAPSULATE: u8 = 65;
pub const OP_KMIP_DECAPSULATE: u8 = 66;

/// `op` id in the `kmip` namespace; 0 when the name is not in the table.
pub fn op_kmip(name: &str) -> u8 {
    match name {
        "Create" => 1,
        "CreateKeyPair" => 2,
        "Register" => 3,
        "ReKey" => 4,
        "DeriveKey" => 5,
        "Certify" => 6,
        "ReCertify" => 7,
        "Locate" => 8,
        "Check" => 9,
        "Get" => 10,
        "GetAttributes" => 11,
        "GetAttributeList" => 12,
        "AddAttribute" => 13,
        "ModifyAttribute" => 14,
        "DeleteAttribute" => 15,
        "ObtainLease" => 16,
        "GetUsageAllocation" => 17,
        "Activate" => 18,
        "Revoke" => 19,
        "Destroy" => 20,
        "Archive" => 21,
        "Recover" => 22,
        "Validate" => 23,
        "Query" => 24,
        "Cancel" => 25,
        "Poll" => 26,
        "Notify" => 27,
        "Put" => 28,
        "ReKeyKeyPair" => 29,
        "DiscoverVersions" => 30,
        "Encrypt" => 31,
        "Decrypt" => 32,
        "Sign" => 33,
        "SignatureVerify" => 34,
        "MAC" => 35,
        "MACVerify" => 36,
        "RNGRetrieve" => 37,
        "RNGSeed" => 38,
        "Hash" => 39,
        "CreateSplitKey" => 40,
        "JoinSplitKey" => 41,
        "Import" => 42,
        "Export" => 43,
        "Log" => 44,
        "Login" => 45,
        "Logout" => 46,
        "DelegatedLogin" => 47,
        "AdjustAttribute" => 48,
        "SetAttribute" => 49,
        "SetEndpointRole" => 50,
        "Pkcs11" => 51,
        "Interop" => 52,
        "ReProvision" => 53,
        "SetDefaults" => 54,
        "SetConstraints" => 55,
        "GetConstraints" => 56,
        "QueryAsynchronousRequests" => 57,
        "Process" => 58,
        "Ping" => 59,
        "CreateGroup" => 60,
        "Obliterate" => 61,
        "CreateUser" => 62,
        "CreateCredential" => 63,
        "Deactivate" => 64,
        "Encapsulate" => 65,
        "Decapsulate" => 66,
        _ => 0,
    }
}

// ── op (byte 1), namespace `kmip-admin` ──────────────────────────────────────
pub const OP_KMIP_ADMIN_HEALTHZ: u8 = 1;
pub const OP_KMIP_ADMIN_VERSION: u8 = 2;
pub const OP_KMIP_ADMIN_OPENAPI_YAML: u8 = 3;
pub const OP_KMIP_ADMIN_API_V1_POLICIES: u8 = 4;
pub const OP_KMIP_ADMIN_API_V1_POLICIES_NAME: u8 = 5;
pub const OP_KMIP_ADMIN_API_V1_ACTIVE: u8 = 6;
pub const OP_KMIP_ADMIN_API_V1_VALIDATE: u8 = 7;
pub const OP_KMIP_ADMIN_API_V1_DRY_RUN: u8 = 8;
pub const OP_KMIP_ADMIN_API_V1_AUDIT: u8 = 9;
pub const OP_KMIP_ADMIN_API_V1_AUDIT_STREAM: u8 = 10;
pub const OP_KMIP_ADMIN_API_V1_ACTIVE_MODULES: u8 = 11;
pub const OP_KMIP_ADMIN_API_V1_ACTIVE_MODULES_NAME: u8 = 12;
pub const OP_KMIP_ADMIN_API_V1_CONFIG_UNCOVERED_OPS: u8 = 13;

/// `op` id in the `kmip-admin` namespace; 0 when the name is not in the table.
pub fn op_kmip_admin(name: &str) -> u8 {
    match name {
        "/healthz" => 1,
        "/version" => 2,
        "/openapi.yaml" => 3,
        "/api/v1/policies" => 4,
        "/api/v1/policies/{name}" => 5,
        "/api/v1/active" => 6,
        "/api/v1/validate" => 7,
        "/api/v1/dry-run" => 8,
        "/api/v1/audit" => 9,
        "/api/v1/audit/stream" => 10,
        "/api/v1/active-modules" => 11,
        "/api/v1/active-modules/{name}" => 12,
        "/api/v1/config/uncovered-ops" => 13,
        _ => 0,
    }
}

// ── op (byte 1), namespace `policy` ──────────────────────────────────────
pub const OP_POLICY_DENY: u8 = 1;
pub const OP_POLICY_WARN: u8 = 2;
pub const OP_POLICY_REKEY_PLANNED: u8 = 3;
pub const OP_POLICY_ACTIVATED: u8 = 4;

/// `op` id in the `policy` namespace; 0 when the name is not in the table.
pub fn op_policy(name: &str) -> u8 {
    match name {
        "deny" => 1,
        "warn" => 2,
        "rekey-planned" => 3,
        "activated" => 4,
        _ => 0,
    }
}

// ── op (byte 1), namespace `pkcs11` ──────────────────────────────────────
pub const OP_PKCS11_C_SIGNINIT: u8 = 1;
pub const OP_PKCS11_C_SIGN: u8 = 2;
pub const OP_PKCS11_C_SIGNFINAL: u8 = 3;
pub const OP_PKCS11_C_VERIFYINIT: u8 = 4;
pub const OP_PKCS11_C_VERIFY: u8 = 5;
pub const OP_PKCS11_C_VERIFYFINAL: u8 = 6;
pub const OP_PKCS11_C_GENERATEKEYPAIR: u8 = 7;
pub const OP_PKCS11_C_ENCAPSULATEKEY: u8 = 8;
pub const OP_PKCS11_C_DECAPSULATEKEY: u8 = 9;

/// `op` id in the `pkcs11` namespace; 0 when the name is not in the table.
pub fn op_pkcs11(name: &str) -> u8 {
    match name {
        "C_SignInit" => 1,
        "C_Sign" => 2,
        "C_SignFinal" => 3,
        "C_VerifyInit" => 4,
        "C_Verify" => 5,
        "C_VerifyFinal" => 6,
        "C_GenerateKeyPair" => 7,
        "C_EncapsulateKey" => 8,
        "C_DecapsulateKey" => 9,
        _ => 0,
    }
}

// ── op (byte 1), namespace `tls` ──────────────────────────────────────
pub const OP_TLS_KMIP: u8 = 1;
pub const OP_TLS_ADMIN: u8 = 2;

/// `op` id in the `tls` namespace; 0 when the name is not in the table.
pub fn op_tls(name: &str) -> u8 {
    match name {
        "kmip" => 1,
        "admin" => 2,
        _ => 0,
    }
}

// ── op (byte 1), namespace `auth` ──────────────────────────────────────
pub const OP_AUTH_KMIP_CREDENTIAL: u8 = 1;
pub const OP_AUTH_KMIP_TLS_HANDSHAKE: u8 = 2;
pub const OP_AUTH_REMOTING_PIN: u8 = 3;

/// `op` id in the `auth` namespace; 0 when the name is not in the table.
pub fn op_auth(name: &str) -> u8 {
    match name {
        "kmip-credential" => 1,
        "kmip-tls-handshake" => 2,
        "remoting-pin" => 3,
        _ => 0,
    }
}

// ── alg (byte 2) ─────────────────────────────────────────────────────────
pub const ALG_NONE: u8 = 0;
pub const ALG_ML_DSA_44: u8 = 1;
pub const ALG_ML_DSA_65: u8 = 2;
pub const ALG_ML_DSA_87: u8 = 3;
pub const ALG_ML_KEM_512: u8 = 4;
pub const ALG_ML_KEM_768: u8 = 5;
pub const ALG_ML_KEM_1024: u8 = 6;
pub const ALG_SLH_DSA_SHA2_128S: u8 = 7;
pub const ALG_SLH_DSA_SHAKE_128S: u8 = 8;
pub const ALG_SLH_DSA_SHA2_128F: u8 = 9;
pub const ALG_SLH_DSA_SHAKE_128F: u8 = 10;
pub const ALG_SLH_DSA_SHA2_192S: u8 = 11;
pub const ALG_SLH_DSA_SHAKE_192S: u8 = 12;
pub const ALG_SLH_DSA_SHA2_192F: u8 = 13;
pub const ALG_SLH_DSA_SHAKE_192F: u8 = 14;
pub const ALG_SLH_DSA_SHA2_256S: u8 = 15;
pub const ALG_SLH_DSA_SHAKE_256S: u8 = 16;
pub const ALG_SLH_DSA_SHA2_256F: u8 = 17;
pub const ALG_SLH_DSA_SHAKE_256F: u8 = 18;
pub const ALG_HSS: u8 = 19;
pub const ALG_XMSS: u8 = 20;
pub const ALG_XMSSMT: u8 = 21;
pub const ALG_RSA: u8 = 22;
pub const ALG_ECDSA: u8 = 23;
pub const ALG_EDDSA: u8 = 24;
pub const ALG_ECDH: u8 = 25;
pub const ALG_AES: u8 = 26;
pub const ALG_HMAC: u8 = 27;
pub const ALG_CHACHA20: u8 = 28;
pub const ALG_OTHER: u8 = 255;

/// `alg` id for a canonical algorithm name (`"ML-DSA-65"`, `"RSA"`, …);
/// `ALG_NONE` for an empty name, `ALG_OTHER` for one not in the table.
pub fn alg_from_name(name: &str) -> u8 {
    match name {
        "" => ALG_NONE,
        "ML-DSA-44" => 1,
        "ML-DSA-65" => 2,
        "ML-DSA-87" => 3,
        "ML-KEM-512" => 4,
        "ML-KEM-768" => 5,
        "ML-KEM-1024" => 6,
        "SLH-DSA-SHA2-128s" => 7,
        "SLH-DSA-SHAKE-128s" => 8,
        "SLH-DSA-SHA2-128f" => 9,
        "SLH-DSA-SHAKE-128f" => 10,
        "SLH-DSA-SHA2-192s" => 11,
        "SLH-DSA-SHAKE-192s" => 12,
        "SLH-DSA-SHA2-192f" => 13,
        "SLH-DSA-SHAKE-192f" => 14,
        "SLH-DSA-SHA2-256s" => 15,
        "SLH-DSA-SHAKE-256s" => 16,
        "SLH-DSA-SHA2-256f" => 17,
        "SLH-DSA-SHAKE-256f" => 18,
        "HSS" => 19,
        "XMSS" => 20,
        "XMSSMT" => 21,
        "RSA" => 22,
        "ECDSA" => 23,
        "EdDSA" => 24,
        "ECDH" => 25,
        "AES" => 26,
        "HMAC" => 27,
        "ChaCha20" => 28,
        _ => ALG_OTHER,
    }
}

/// `alg` id for a PKCS#11 (mechanism, `CKA_PARAMETER_SET`) pair. Pairs listed
/// with parameter set 0 match any parameter set. `ALG_OTHER` when unknown.
pub fn alg_from_ckm(mech: u32, param_set: u32) -> u8 {
    match (mech, param_set) {
        (0x0000001d, 1) => 1,
        (0x0000001c, 1) => 1,
        (0x0000001f, 1) => 1,
        (0x0000403c, 1) => 1,
        (0x0000001d, 2) => 2,
        (0x0000001c, 2) => 2,
        (0x0000001f, 2) => 2,
        (0x0000403c, 2) => 2,
        (0x0000001d, 3) => 3,
        (0x0000001c, 3) => 3,
        (0x0000001f, 3) => 3,
        (0x0000403c, 3) => 3,
        (0x00000017, 1) => 4,
        (0x0000000f, 1) => 4,
        (0x00000017, 2) => 5,
        (0x0000000f, 2) => 5,
        (0x00000017, 3) => 6,
        (0x0000000f, 3) => 6,
        (0x0000002e, 1) => 7,
        (0x0000002d, 1) => 7,
        (0x00000034, 1) => 7,
        (0x0000002e, 2) => 8,
        (0x0000002d, 2) => 8,
        (0x00000034, 2) => 8,
        (0x0000002e, 3) => 9,
        (0x0000002d, 3) => 9,
        (0x00000034, 3) => 9,
        (0x0000002e, 4) => 10,
        (0x0000002d, 4) => 10,
        (0x00000034, 4) => 10,
        (0x0000002e, 5) => 11,
        (0x0000002d, 5) => 11,
        (0x00000034, 5) => 11,
        (0x0000002e, 6) => 12,
        (0x0000002d, 6) => 12,
        (0x00000034, 6) => 12,
        (0x0000002e, 7) => 13,
        (0x0000002d, 7) => 13,
        (0x00000034, 7) => 13,
        (0x0000002e, 8) => 14,
        (0x0000002d, 8) => 14,
        (0x00000034, 8) => 14,
        (0x0000002e, 9) => 15,
        (0x0000002d, 9) => 15,
        (0x00000034, 9) => 15,
        (0x0000002e, 10) => 16,
        (0x0000002d, 10) => 16,
        (0x00000034, 10) => 16,
        (0x0000002e, 11) => 17,
        (0x0000002d, 11) => 17,
        (0x00000034, 11) => 17,
        (0x0000002e, 12) => 18,
        (0x0000002d, 12) => 18,
        (0x00000034, 12) => 18,
        (0x00004033, _) => 19,
        (0x00004032, _) => 19,
        (0x00004036, _) => 20,
        (0x00004034, _) => 20,
        (0x00004037, _) => 21,
        (0x00004035, _) => 21,
        (0x00000000, _) => 22,
        (0x00000001, _) => 22,
        (0x00000003, _) => 22,
        (0x00000006, _) => 22,
        (0x00000009, _) => 22,
        (0x0000000d, _) => 22,
        (0x0000000e, _) => 22,
        (0x00000040, _) => 22,
        (0x00000041, _) => 22,
        (0x00000042, _) => 22,
        (0x00000043, _) => 22,
        (0x00000044, _) => 22,
        (0x00000045, _) => 22,
        (0x00000046, _) => 22,
        (0x00000047, _) => 22,
        (0x00000060, _) => 22,
        (0x00000063, _) => 22,
        (0x00001040, _) => 23,
        (0x00001041, _) => 23,
        (0x00001042, _) => 23,
        (0x00001043, _) => 23,
        (0x00001044, _) => 23,
        (0x00001045, _) => 23,
        (0x00001046, _) => 23,
        (0x00001047, _) => 23,
        (0x00001048, _) => 23,
        (0x00001049, _) => 23,
        (0x0000104a, _) => 23,
        (0x0000140b, _) => 23,
        (0x00001057, _) => 24,
        (0x00001055, _) => 24,
        (0x80001057, _) => 24,
        (0x00001050, _) => 25,
        (0x00001056, _) => 25,
        (0x00001080, _) => 26,
        (0x00001081, _) => 26,
        (0x00001082, _) => 26,
        (0x00001085, _) => 26,
        (0x00001086, _) => 26,
        (0x00001087, _) => 26,
        (0x0000108a, _) => 26,
        (0x00002109, _) => 26,
        (0x0000210a, _) => 26,
        (0x0000210b, _) => 26,
        (0x00000251, _) => 27,
        (0x00000261, _) => 27,
        (0x00000271, _) => 27,
        (0x000002b1, _) => 27,
        (0x00000252, _) => 27,
        (0x00000262, _) => 27,
        (0x00000272, _) => 27,
        (0x000002b2, _) => 27,
        (0x80000100, _) => 27,
        (0x80000101, _) => 27,
        (0x00001225, _) => 28,
        (0x00001226, _) => 28,
        (0x00004021, _) => 28,
        _ => ALG_OTHER,
    }
}

// ── result (byte 3) ──────────────────────────────────────────────────────
pub const RESULT_OK: u8 = 0;
pub const RESULT_POLICY_DENY: u8 = 1;
pub const RESULT_AUTH_FAIL: u8 = 2;
pub const RESULT_CALLER_ERROR: u8 = 3;
pub const RESULT_INTERNAL_ERROR: u8 = 4;
pub const RESULT_WARN_REKEY: u8 = 5;

/// Result class of a PKCS#11 `CK_RV`.
pub fn result_from_ckr(rv: u32) -> u8 {
    match rv {
        0 => 0,
        0x000000a0 => 2,
        0x000000a1 => 2,
        0x000000a2 => 2,
        0x000000a3 => 2,
        0x000000a4 => 2,
        0x000001b8 => 2,
        0x00000100 => 2,
        0x00000101 => 2,
        0x00000102 => 2,
        0x00000103 => 2,
        0x00000104 => 2,
        0x00000105 => 2,
        0x000000b5 => 2,
        0x000000b7 => 2,
        0x000000b8 => 2,
        0x00000002 => 4,
        0x00000005 => 4,
        0x00000006 => 4,
        0x00000009 => 4,
        0x0000000a => 4,
        0x00000030 => 4,
        0x00000031 => 4,
        0x00000032 => 4,
        0x00000054 => 4,
        0x000000e0 => 4,
        0x000000e1 => 4,
        0x000000e2 => 4,
        0x00000120 => 4,
        0x00000121 => 4,
        0x00000160 => 4,
        0x00000180 => 4,
        0x00000190 => 4,
        0x00000191 => 4,
        0x000001a0 => 4,
        0x000001a1 => 4,
        _ => 3,
    }
}

/// Result class of a KMIP `ResultReason` variant name (`KmipResponseSent`
/// carries it as `format!("{:?}", reason)`); `None` means success.
pub fn result_from_kmip_reason(reason: Option<&str>) -> u8 {
    match reason {
        None => 0,
        Some("PermissionDenied") => 1,
        Some("AuthenticationNotSuccessful") => 2,
        Some("NotAuthorised") => 2,
        Some("BadPassword") => 2,
        Some("InvalidTicket") => 2,
        Some("AttestationRequired") => 2,
        Some("AttestationFailed") => 2,
        Some("InternalServerError") => 4,
        Some("CryptographicFailure") => 4,
        Some("ProtectionStorageUnavailable") => 4,
        Some("PrivateProtectionStorageUnavailable") => 4,
        Some("PublicProtectionStorageUnavailable") => 4,
        Some("ServerLimitExceeded") => 4,
        Some("ResponseTooLarge") => 4,
        Some(_) => 3,
    }
}

/// Result class of an HTTP status on the admin plane.
pub fn result_from_http_status(status: u16) -> u8 {
    match status {
        200..=399 => 0,
        401 | 403 => 2,
        400..=499 => 3,
        500..=599 => 4,
        _ => 3,
    }
}

// ── golden vectors (tests in both engines encode these) ─────────────────
/// `(src, op, alg, result, client, size_bytes, latency_us, dt_us, expected LE u64)`;
/// `dt_us == -1` means "first record from this process".
pub const VECTORS: &[(u8, u8, u8, u8, u8, u64, u64, i64, u64)] = &[
    (6, 2, 2, 0, 0, 32, 1500, -1, 0xff0a050000020206),
    (4, 7, 5, 0, 0, 0, 900, 2048, 0x0b09000000050704),
    (6, 1, 0, 3, 0, 0, 0, 1, 0x0000000003000106),
    (1, 33, 3, 1, 17, 0, 12000, 1000000, 0x130d001101032101),
    (8, 3, 0, 2, 200, 0, 0, 0, 0x000000c802000308),
    (7, 1, 0, 0, 0, 0, 0, 65536, 0x1000000000000107),
];
