/*
 * test_classic_mceliece_cross_engine.cpp — file-based CLI bridge for the
 * C++ side of the C++/Rust cross-engine validation (implementation plan
 * §5.5(b), docs/implementation-plan-classic-mceliece-all-parameter-sets-
 * 2026-09-08.md): a keypair generated by one engine must be usable by the
 * other, in both directions, for all 10 parameter sets. Paired with
 * rust/classic-mceliece-multi/examples/cross_engine_cli.rs on the Rust
 * side; driven by a shell script that shuttles raw pk/sk/ct/ss files
 * between the two.
 *
 * Ad-hoc executable, not a CppUnit suite addition — same precedent as
 * test_classic_mceliece_kat.cpp / test_acvp_lms_sigver.cpp.
 *
 * Build: g++ -o test_classic_mceliece_cross_engine test_classic_mceliece_cross_engine.cpp -ldl -I src/lib/pkcs11 -std=c++17
 * Usage: ./test_classic_mceliece_cross_engine keygen <variant> <pk_out> <sk_out> [libPath]
 *        ./test_classic_mceliece_cross_engine encaps <variant> <pk_in> <ct_out> <ss_out> [libPath]
 *        ./test_classic_mceliece_cross_engine decaps <variant> <sk_in> <ct_in> <ss_out> [libPath]
 */

#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>
#include <string.h>
#include <string>
#include <vector>
#include <fstream>
#include <map>

#define CK_PTR *
#define CK_DECLARE_FUNCTION(returnType, name) returnType name
#define CK_DECLARE_FUNCTION_POINTER(returnType, name) returnType (* name)
#define CK_CALLBACK_FUNCTION(returnType, name) returnType (* name)
#ifndef NULL_PTR
#define NULL_PTR 0
#endif

#include "src/lib/pkcs11/pkcs11.h"

#define CKK_PQCTODAY_CLASSIC_MCELIECE              0x80000002UL
#define CKM_PQCTODAY_CLASSIC_MCELIECE_KEY_PAIR_GEN 0x80000003UL
#define CKM_PQCTODAY_CLASSIC_MCELIECE_ENCAPSULATE  0x80000004UL
#define CKP_CLASSIC_MCELIECE_6688128  0x1UL
#define CKP_CLASSIC_MCELIECE_348864   0x2UL
#define CKP_CLASSIC_MCELIECE_348864F  0x3UL
#define CKP_CLASSIC_MCELIECE_460896   0x4UL
#define CKP_CLASSIC_MCELIECE_460896F  0x5UL
#define CKP_CLASSIC_MCELIECE_6688128F 0x6UL
#define CKP_CLASSIC_MCELIECE_6960119  0x7UL
#define CKP_CLASSIC_MCELIECE_6960119F 0x8UL
#define CKP_CLASSIC_MCELIECE_8192128  0x9UL
#define CKP_CLASSIC_MCELIECE_8192128F 0xAUL

static const std::map<std::string, CK_ULONG> VARIANTS = {
    { "348864",   CKP_CLASSIC_MCELIECE_348864   },
    { "348864f",  CKP_CLASSIC_MCELIECE_348864F  },
    { "460896",   CKP_CLASSIC_MCELIECE_460896   },
    { "460896f",  CKP_CLASSIC_MCELIECE_460896F  },
    { "6688128",  CKP_CLASSIC_MCELIECE_6688128  },
    { "6688128f", CKP_CLASSIC_MCELIECE_6688128F },
    { "6960119",  CKP_CLASSIC_MCELIECE_6960119  },
    { "6960119f", CKP_CLASSIC_MCELIECE_6960119F },
    { "8192128",  CKP_CLASSIC_MCELIECE_8192128  },
    { "8192128f", CKP_CLASSIC_MCELIECE_8192128F },
};

static std::vector<unsigned char> readFile(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) { fprintf(stderr, "cannot read %s\n", path.c_str()); exit(1); }
    return std::vector<unsigned char>((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
}

static void writeFile(const std::string& path, const unsigned char* data, size_t len) {
    std::ofstream f(path, std::ios::binary);
    if (!f) { fprintf(stderr, "cannot write %s\n", path.c_str()); exit(1); }
    f.write((const char*)data, (std::streamsize)len);
}

static CK_FUNCTION_LIST_3_2_PTR gFl;
static CK_SESSION_HANDLE gSess;

static void initEngine(const char* libPath) {
    system("rm -rf /tmp/softhsm-mceliece-cross && mkdir -p /tmp/softhsm-mceliece-cross/tokens");
    FILE* f = fopen("/tmp/softhsm-mceliece-cross/softhsm2.conf", "w");
    fprintf(f, "directories.tokendir = /tmp/softhsm-mceliece-cross/tokens/\n"
               "objectstore.backend = file\nlog.level = ERROR\nslots.removable = false\n");
    fclose(f);
    setenv("SOFTHSM2_CONF", "/tmp/softhsm-mceliece-cross/softhsm2.conf", 1);

    void* handle = dlopen(libPath, RTLD_NOW);
    if (!handle) { fprintf(stderr, "dlopen(%s): %s\n", libPath, dlerror()); exit(1); }

    typedef CK_RV (*CK_C_GetInterfaceFn)(CK_UTF8CHAR_PTR, CK_VERSION_PTR, CK_INTERFACE_PTR_PTR, CK_FLAGS);
    CK_C_GetInterfaceFn getInterface = (CK_C_GetInterfaceFn)dlsym(handle, "C_GetInterface");
    if (!getInterface) { fprintf(stderr, "dlsym(C_GetInterface): %s\n", dlerror()); exit(1); }

    CK_VERSION v32 = { 3, 2 };
    CK_INTERFACE_PTR iface = NULL_PTR;
    CK_RV rv = getInterface((CK_UTF8CHAR_PTR)"PKCS 11", &v32, &iface, 0);
    if (rv != CKR_OK || iface == NULL_PTR || iface->pFunctionList == NULL_PTR) {
        fprintf(stderr, "C_GetInterface(\"PKCS 11\", 3.2): rv=0x%08lX\n", (unsigned long)rv);
        exit(1);
    }
    gFl = (CK_FUNCTION_LIST_3_2_PTR)iface->pFunctionList;
    gFl->C_Initialize(NULL_PTR);

    CK_SLOT_ID slots[10];
    CK_ULONG ulCount = 10;
    gFl->C_GetSlotList(CK_FALSE, slots, &ulCount);
    CK_UTF8CHAR label[32];
    memset(label, ' ', 32);
    memcpy(label, "mceliece-cross", 14);
    gFl->C_InitToken(slots[0], (CK_UTF8CHAR_PTR)"5678", 4, label);
    gFl->C_OpenSession(slots[0], CKF_SERIAL_SESSION | CKF_RW_SESSION, NULL_PTR, NULL_PTR, &gSess);
    gFl->C_Login(gSess, CKU_SO, (CK_UTF8CHAR_PTR)"5678", 4);
    gFl->C_InitPIN(gSess, (CK_UTF8CHAR_PTR)"1234", 4);
    gFl->C_Logout(gSess);
    gFl->C_Login(gSess, CKU_USER, (CK_UTF8CHAR_PTR)"1234", 4);
}

static CK_ULONG lookupVariant(const std::string& name) {
    auto it = VARIANTS.find(name);
    if (it == VARIANTS.end()) { fprintf(stderr, "unknown variant: %s\n", name.c_str()); exit(1); }
    return it->second;
}

static void checkRv(CK_RV rv, const char* what) {
    if (rv != CKR_OK) { fprintf(stderr, "%s failed: rv=0x%08lX\n", what, (unsigned long)rv); exit(1); }
}

int cmdKeygen(const std::string& variant, const std::string& pkOut, const std::string& skOut) {
    CK_ULONG ps = lookupVariant(variant);
    CK_MECHANISM mech = { CKM_PQCTODAY_CLASSIC_MCELIECE_KEY_PAIR_GEN, NULL_PTR, 0 };
    CK_BBOOL bFalse = CK_FALSE;
    CK_ATTRIBUTE pukT[] = {
        { CKA_TOKEN, &bFalse, sizeof(bFalse) },
        { CKA_PRIVATE, &bFalse, sizeof(bFalse) },
        { CKA_PARAMETER_SET, &ps, sizeof(ps) },
    };
    CK_BBOOL bTrue = CK_TRUE;
    CK_ATTRIBUTE prkT[] = {
        { CKA_TOKEN, &bFalse, sizeof(bFalse) },
        { CKA_PRIVATE, &bTrue, sizeof(bTrue) },
        { CKA_SENSITIVE, &bFalse, sizeof(bFalse) },
        { CKA_EXTRACTABLE, &bTrue, sizeof(bTrue) },
    };
    CK_OBJECT_HANDLE hPuk = CK_INVALID_HANDLE, hPrk = CK_INVALID_HANDLE;
    checkRv(gFl->C_GenerateKeyPair(gSess, &mech,
                pukT, sizeof(pukT) / sizeof(CK_ATTRIBUTE),
                prkT, sizeof(prkT) / sizeof(CK_ATTRIBUTE),
                &hPuk, &hPrk), "C_GenerateKeyPair");

    CK_ATTRIBUTE pukVal[] = { { CKA_VALUE, NULL_PTR, 0 } };
    checkRv(gFl->C_GetAttributeValue(gSess, hPuk, pukVal, 1), "C_GetAttributeValue(pk size)");
    std::vector<unsigned char> pk(pukVal[0].ulValueLen);
    pukVal[0].pValue = pk.data();
    checkRv(gFl->C_GetAttributeValue(gSess, hPuk, pukVal, 1), "C_GetAttributeValue(pk)");

    CK_ATTRIBUTE prkVal[] = { { CKA_VALUE, NULL_PTR, 0 } };
    checkRv(gFl->C_GetAttributeValue(gSess, hPrk, prkVal, 1), "C_GetAttributeValue(sk size)");
    std::vector<unsigned char> sk(prkVal[0].ulValueLen);
    prkVal[0].pValue = sk.data();
    checkRv(gFl->C_GetAttributeValue(gSess, hPrk, prkVal, 1), "C_GetAttributeValue(sk)");

    writeFile(pkOut, pk.data(), pk.size());
    writeFile(skOut, sk.data(), sk.size());
    return 0;
}

int cmdEncaps(const std::string& variant, const std::string& pkIn, const std::string& ctOut, const std::string& ssOut) {
    CK_ULONG ps = lookupVariant(variant);
    std::vector<unsigned char> pk = readFile(pkIn);

    CK_OBJECT_CLASS pukClass = CKO_PUBLIC_KEY;
    CK_KEY_TYPE keyType = CKK_PQCTODAY_CLASSIC_MCELIECE;
    CK_BBOOL bFalse = CK_FALSE;
    CK_BBOOL bTrue = CK_TRUE;
    CK_ATTRIBUTE pukT[] = {
        { CKA_CLASS, &pukClass, sizeof(pukClass) },
        { CKA_KEY_TYPE, &keyType, sizeof(keyType) },
        { CKA_TOKEN, &bFalse, sizeof(bFalse) },
        { CKA_PRIVATE, &bFalse, sizeof(bFalse) },
        { CKA_ENCAPSULATE, &bTrue, sizeof(bTrue) },
        { CKA_PARAMETER_SET, &ps, sizeof(ps) },
        { CKA_VALUE, pk.data(), (CK_ULONG)pk.size() },
    };
    CK_OBJECT_HANDLE hPuk = CK_INVALID_HANDLE;
    checkRv(gFl->C_CreateObject(gSess, pukT, sizeof(pukT) / sizeof(CK_ATTRIBUTE), &hPuk), "C_CreateObject(pk)");

    CK_MECHANISM mech = { CKM_PQCTODAY_CLASSIC_MCELIECE_ENCAPSULATE, NULL_PTR, 0 };
    CK_OBJECT_CLASS secretClass = CKO_SECRET_KEY;
    CK_ATTRIBUTE secretT[] = {
        { CKA_CLASS, &secretClass, sizeof(secretClass) },
        { CKA_EXTRACTABLE, &bTrue, sizeof(bTrue) },
    };
    const CK_ULONG secretTCount = sizeof(secretT) / sizeof(CK_ATTRIBUTE);

    CK_ULONG ctLen = 0;
    CK_OBJECT_HANDLE hSecretSizeQuery = CK_INVALID_HANDLE;
    checkRv(gFl->C_EncapsulateKey(gSess, &mech, hPuk, secretT, secretTCount, NULL_PTR, &ctLen, &hSecretSizeQuery),
            "C_EncapsulateKey(size query)");
    std::vector<unsigned char> ct(ctLen);
    CK_OBJECT_HANDLE hSecret = CK_INVALID_HANDLE;
    checkRv(gFl->C_EncapsulateKey(gSess, &mech, hPuk, secretT, secretTCount, ct.data(), &ctLen, &hSecret),
            "C_EncapsulateKey");

    unsigned char ss[64];
    CK_ATTRIBUTE getSs[] = { { CKA_VALUE, ss, sizeof(ss) } };
    checkRv(gFl->C_GetAttributeValue(gSess, hSecret, getSs, 1), "C_GetAttributeValue(ss)");

    writeFile(ctOut, ct.data(), ct.size());
    writeFile(ssOut, ss, getSs[0].ulValueLen);
    return 0;
}

int cmdDecaps(const std::string& variant, const std::string& skIn, const std::string& ctIn, const std::string& ssOut) {
    CK_ULONG ps = lookupVariant(variant);
    std::vector<unsigned char> sk = readFile(skIn);
    std::vector<unsigned char> ct = readFile(ctIn);

    CK_OBJECT_CLASS prkClass = CKO_PRIVATE_KEY;
    CK_KEY_TYPE keyType = CKK_PQCTODAY_CLASSIC_MCELIECE;
    CK_BBOOL bFalse = CK_FALSE;
    CK_BBOOL bTrue = CK_TRUE;
    CK_ATTRIBUTE prkT[] = {
        { CKA_CLASS, &prkClass, sizeof(prkClass) },
        { CKA_KEY_TYPE, &keyType, sizeof(keyType) },
        { CKA_TOKEN, &bFalse, sizeof(bFalse) },
        { CKA_PRIVATE, &bTrue, sizeof(bTrue) },
        { CKA_SENSITIVE, &bFalse, sizeof(bFalse) },
        { CKA_EXTRACTABLE, &bTrue, sizeof(bTrue) },
        { CKA_DECAPSULATE, &bTrue, sizeof(bTrue) },
        { CKA_PARAMETER_SET, &ps, sizeof(ps) },
        { CKA_VALUE, sk.data(), (CK_ULONG)sk.size() },
    };
    CK_OBJECT_HANDLE hPrk = CK_INVALID_HANDLE;
    checkRv(gFl->C_CreateObject(gSess, prkT, sizeof(prkT) / sizeof(CK_ATTRIBUTE), &hPrk), "C_CreateObject(sk)");

    CK_MECHANISM mech = { CKM_PQCTODAY_CLASSIC_MCELIECE_ENCAPSULATE, NULL_PTR, 0 };
    CK_OBJECT_CLASS secretClass = CKO_SECRET_KEY;
    CK_ATTRIBUTE secretT[] = {
        { CKA_CLASS, &secretClass, sizeof(secretClass) },
        { CKA_EXTRACTABLE, &bTrue, sizeof(bTrue) },
    };
    CK_OBJECT_HANDLE hSecret = CK_INVALID_HANDLE;
    checkRv(gFl->C_DecapsulateKey(gSess, &mech, hPrk, secretT, sizeof(secretT) / sizeof(CK_ATTRIBUTE),
                ct.data(), (CK_ULONG)ct.size(), &hSecret), "C_DecapsulateKey");

    unsigned char ss[64];
    CK_ATTRIBUTE getSs[] = { { CKA_VALUE, ss, sizeof(ss) } };
    checkRv(gFl->C_GetAttributeValue(gSess, hSecret, getSs, 1), "C_GetAttributeValue(ss)");

    writeFile(ssOut, ss, getSs[0].ulValueLen);
    return 0;
}

int main(int argc, char** argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <keygen|encaps|decaps> <variant> <args...> [libPath]\n", argv[0]);
        return 1;
    }
    std::string cmd = argv[1];

    if (cmd == "keygen" && argc >= 5) {
        std::string libPath = (argc >= 6) ? argv[5] : "./build-mceliece-p2/src/lib/libsofthsmv3.so";
        initEngine(libPath.c_str());
        return cmdKeygen(argv[2], argv[3], argv[4]);
    }
    if (cmd == "encaps" && argc >= 6) {
        std::string libPath = (argc >= 7) ? argv[6] : "./build-mceliece-p2/src/lib/libsofthsmv3.so";
        initEngine(libPath.c_str());
        return cmdEncaps(argv[2], argv[3], argv[4], argv[5]);
    }
    if (cmd == "decaps" && argc >= 6) {
        std::string libPath = (argc >= 7) ? argv[6] : "./build-mceliece-p2/src/lib/libsofthsmv3.so";
        initEngine(libPath.c_str());
        return cmdDecaps(argv[2], argv[3], argv[4], argv[5]);
    }

    fprintf(stderr, "usage: %s <keygen|encaps|decaps> <variant> <args...> [libPath]\n", argv[0]);
    return 1;
}
