//! Token-state snapshot / restore — the persistence surface for the
//! wasm32-unknown-emscripten staticlib embedding (openssl.wasm).
//!
//! Why this exists: this engine keeps ALL state in memory (`state.rs`
//! lazy_statics). That is fine for the wasm-bindgen playground (one module
//! instance per page) and the native KMIP server (one long-lived process),
//! but openssl.wasm is built with `-sEXIT_RUNTIME=1`: every `callMain()`
//! tears the runtime down, and pkcs11-provider's teardown calls
//! `C_Finalize`, which zeroizes and wipes the object store. Without a
//! snapshot taken BEFORE that wipe, a token key generated by one CLI
//! command simply does not exist for the next one — the exact failure mode
//! the C++ engine avoided with its file-backed token directory (see
//! openssl-studio-pkcs11-wiring-plan-07242026.md WP1/WP3).
//!
//! Scope of a snapshot (PKCS#11 semantics: what a real token's nonvolatile
//! storage would hold):
//!   - `TOKEN_STORE` (slot/token metadata, PIN hashes; `login_state` is
//!     always restored as `Public` — sessions do not survive finalize)
//!   - objects in `OBJECTS` with `CKA_TOKEN = TRUE` (session objects die
//!     with the session per §4.4)
//!   - `NEXT_HANDLE` / `UNIQUE_ID_COUNTER` (so rehydrated handles can
//!     never collide with newly created ones)
//!
//! Format: versioned little-endian binary, magic `SHR3SNP1`. Hand-rolled
//! (no serde dependency) — the shapes are three flat maps of bytes.

use std::collections::HashMap;

use crate::constants::*;
use crate::crypto::handlers::Attributes;
use crate::state::{
    LoginState, TokenState, NEXT_HANDLE, OBJECTS, TOKEN_STORE, UNIQUE_ID_COUNTER,
};

/// Snapshot format magic. Bumped `SHR3SNP1` → `SHR3SNP2` on 2026-08-13 by
/// remediation item S4: the stateful HBS attribute ids MOVED out of the
/// client-writable vendor range into the engine-private one. A snapshot
/// written under the old layout carries the leaf index and serialised
/// one-time-signature state under ids this build no longer reads, so the
/// counters would come back ABSENT — presenting a partially used XMSS/LMS key
/// as a fresh one, which is precisely the rewind the item exists to prevent.
///
/// The decision (taken before implementation, not discovered here) is to
/// REFUSE such snapshots loudly rather than migrate them in place: a
/// silently reinterpreted stateful key is a forgery risk, an explicit load
/// failure is an operations problem. Anyone implementing KMIP engine-key
/// persistence must read this first.
const MAGIC: &[u8; 8] = b"SHR3SNP2";

/// The superseded pre-S4 magic — recognised only so the loader can return a
/// specific error instead of a generic parse failure.
const MAGIC_V1: &[u8; 8] = b"SHR3SNP1";

// ─────────────────────────────────────────────────────────────────────────
// Serialize
// ─────────────────────────────────────────────────────────────────────────

fn put_u32(out: &mut Vec<u8>, v: u32) {
    out.extend_from_slice(&v.to_le_bytes());
}
fn put_u64(out: &mut Vec<u8>, v: u64) {
    out.extend_from_slice(&v.to_le_bytes());
}

/// Serialize the persistent slice of engine state. Always succeeds; an
/// empty engine produces a valid (small) snapshot.
pub fn serialize_token_state() -> Vec<u8> {
    let mut out = Vec::with_capacity(4096);
    out.extend_from_slice(MAGIC);
    put_u32(
        &mut out,
        NEXT_HANDLE.load(std::sync::atomic::Ordering::Relaxed),
    );
    put_u64(
        &mut out,
        UNIQUE_ID_COUNTER.load(std::sync::atomic::Ordering::Relaxed),
    );

    TOKEN_STORE.with(|ts| {
        let store = ts.borrow();
        put_u32(&mut out, store.len() as u32);
        // Deterministic order (BTreeMap-like) so identical state → identical bytes.
        let mut slots: Vec<&u32> = store.keys().collect();
        slots.sort();
        for slot in slots {
            let t = &store[slot];
            put_u32(&mut out, t.slot_id);
            out.push(t.initialized as u8);
            out.extend_from_slice(&t.label);
            out.extend_from_slice(&t.so_pin_salt);
            out.extend_from_slice(&t.so_pin_hash);
            match (&t.user_pin_salt, &t.user_pin_hash) {
                (Some(salt), Some(hash)) => {
                    out.push(1);
                    out.extend_from_slice(salt);
                    out.extend_from_slice(hash);
                }
                _ => out.push(0),
            }
        }
    });

    OBJECTS.with(|o| {
        let store = o.borrow();
        let token_objects: Vec<(&u32, &Attributes)> = {
            let mut v: Vec<(&u32, &Attributes)> = store
                .iter()
                .filter(|(_, attrs)| {
                    attrs
                        .get(&CKA_TOKEN)
                        .map(|v| v.first() == Some(&1))
                        .unwrap_or(false)
                })
                .collect();
            v.sort_by_key(|(h, _)| **h);
            v
        };
        put_u32(&mut out, token_objects.len() as u32);
        for (handle, attrs) in token_objects {
            put_u32(&mut out, *handle);
            put_u32(&mut out, attrs.len() as u32);
            let mut types: Vec<&u32> = attrs.keys().collect();
            types.sort();
            for ty in types {
                let val = &attrs[ty];
                put_u32(&mut out, *ty);
                put_u32(&mut out, val.len() as u32);
                out.extend_from_slice(val);
            }
        }
    });

    out
}

// ─────────────────────────────────────────────────────────────────────────
// Deserialize
// ─────────────────────────────────────────────────────────────────────────

struct Cursor<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> Cursor<'a> {
    fn take(&mut self, n: usize) -> Result<&'a [u8], u32> {
        if self.pos + n > self.buf.len() {
            return Err(CKR_GENERAL_ERROR);
        }
        let s = &self.buf[self.pos..self.pos + n];
        self.pos += n;
        Ok(s)
    }
    fn u8(&mut self) -> Result<u8, u32> {
        Ok(self.take(1)?[0])
    }
    fn u32(&mut self) -> Result<u32, u32> {
        Ok(u32::from_le_bytes(self.take(4)?.try_into().unwrap()))
    }
    fn u64(&mut self) -> Result<u64, u32> {
        Ok(u64::from_le_bytes(self.take(8)?.try_into().unwrap()))
    }
}

/// Parse and install a snapshot produced by [`serialize_token_state`].
///
/// Fully parses into temporaries BEFORE touching engine state — a truncated
/// or corrupt snapshot returns `CKR_GENERAL_ERROR` and leaves the engine
/// untouched. On success, replaces `TOKEN_STORE` and the token objects in
/// `OBJECTS` (session objects and operation state are untouched — callers
/// load snapshots at module boot when those are empty anyway), and bumps
/// the counters to at least their snapshot values.
pub fn deserialize_token_state(buf: &[u8]) -> Result<(), u32> {
    let mut c = Cursor { buf, pos: 0 };
    let magic = c.take(8)?;
    if magic == MAGIC_V1 {
        // S4 — old layout: refuse, do not reinterpret. See MAGIC.
        return Err(CKR_PQCTODAY_SNAPSHOT_FORMAT_UNSUPPORTED);
    }
    if magic != MAGIC {
        return Err(CKR_GENERAL_ERROR);
    }
    let next_handle = c.u32()?;
    let unique_id = c.u64()?;

    let token_count = c.u32()?;
    let mut tokens: HashMap<u32, TokenState> = HashMap::new();
    for _ in 0..token_count {
        let slot_id = c.u32()?;
        let initialized = c.u8()? != 0;
        let label: [u8; 32] = c.take(32)?.try_into().unwrap();
        let so_pin_salt: [u8; 16] = c.take(16)?.try_into().unwrap();
        let so_pin_hash: [u8; 32] = c.take(32)?.try_into().unwrap();
        let (user_pin_salt, user_pin_hash) = if c.u8()? != 0 {
            (
                Some(c.take(16)?.try_into().unwrap()),
                Some(c.take(32)?.try_into().unwrap()),
            )
        } else {
            (None, None)
        };
        tokens.insert(
            slot_id,
            TokenState {
                slot_id,
                initialized,
                label,
                login_state: LoginState::Public,
                so_pin_salt,
                so_pin_hash,
                user_pin_salt,
                user_pin_hash,
            },
        );
    }

    let obj_count = c.u32()?;
    let mut objects: HashMap<u32, Attributes> = HashMap::new();
    for _ in 0..obj_count {
        let handle = c.u32()?;
        let attr_count = c.u32()?;
        let mut attrs: Attributes = HashMap::with_capacity(attr_count as usize);
        for _ in 0..attr_count {
            let ty = c.u32()?;
            let len = c.u32()? as usize;
            attrs.insert(ty, c.take(len)?.to_vec());
        }
        objects.insert(handle, attrs);
    }

    // Commit.
    TOKEN_STORE.with(|ts| *ts.borrow_mut() = tokens);
    OBJECTS.with(|o| {
        let mut store = o.borrow_mut();
        // Drop any stale token objects (a load REPLACES nonvolatile storage),
        // keep session objects (none exist at the intended call point).
        store.retain(|_, attrs| {
            !attrs
                .get(&CKA_TOKEN)
                .map(|v| v.first() == Some(&1))
                .unwrap_or(false)
        });
        store.extend(objects);
    });
    let bump = |atomic: &std::sync::atomic::AtomicU32, v: u32| {
        atomic.fetch_max(v, std::sync::atomic::Ordering::Relaxed);
    };
    bump(&NEXT_HANDLE, next_handle);
    UNIQUE_ID_COUNTER.fetch_max(unique_id, std::sync::atomic::Ordering::Relaxed);
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────
// Finalize stash + C exports (emscripten staticlib embedding only)
// ─────────────────────────────────────────────────────────────────────────

#[cfg(target_os = "emscripten")]
mod emscripten_exports {
    use super::*;
    use crate::state::GlobalState;

    /// MEMFS path the atexit hook (`pqctoday_hsm_atexit_stash`, below) and
    /// `stash_before_finalize` both write to — the primary handoff for any
    /// embedder reached via `callMain` (the real OpenSSL CLI), not just
    /// direct C-API calls. See `pqctoday_hsm_atexit_stash`'s doc comment for
    /// why this is a file, not the STASH pull further down.
    pub const HSM_STATE_FILE_PATH: &str = "/tmp/.pqctoday_hsm_state.bin";

    lazy_static::lazy_static! {
        /// Snapshot parked by `stash_before_finalize`, for callers that can
        /// pull it out via `pqctoday_hsm_state_take` while still inside a
        /// LIVE module instance that never called `callMain` — see that
        /// function's doc comment for why this is NOT safe for a
        /// callMain-based caller.
        static ref STASH: GlobalState<Option<Vec<u8>>> = GlobalState::new(None);
    }

    fn write_state_file() {
        let blob = serialize_token_state();
        let _ = std::fs::write(HSM_STATE_FILE_PATH, &blob);
    }

    /// C-callable, unconditional stash — call this from a process-wide
    /// `atexit()` hook, NOT from `C_Finalize`. See the doc comment below for
    /// why: `C_Finalize` is only reachable from a caller that explicitly
    /// tears the provider down, which the real openssl.wasm CLI embedding
    /// never does.
    ///
    /// Deliberately unconditional (no `require_init!` gate): if the engine
    /// was never used this command, `serialize_token_state()` just produces
    /// an empty-but-valid snapshot — harmless to overwrite the file with.
    #[unsafe(no_mangle)]
    pub extern "C" fn pqctoday_hsm_atexit_stash() {
        write_state_file();
    }

    /// Called by `ffi::C_Finalize` (emscripten builds only) BEFORE it wipes
    /// the object store. Deliberately NOT compiled on native: parking key
    /// material past finalize would defeat the zeroize pass there.
    ///
    /// CORRECTED 2026-07-24, after this was found not to fire in practice:
    /// this function is reachable ONLY when something explicitly calls
    /// `OSSL_PROVIDER_unload()` on the pkcs11 provider (verified directly —
    /// `C_Finalize` works correctly when called that way) — but
    /// `OPENSSL_cleanup()`, which DOES run at the end of every `callMain`
    /// (confirmed empirically), does NOT unload providers registered via an
    /// explicit `OSSL_PROVIDER_load()` call (as `pqctoday_cms_init()` does);
    /// it has no code path that even mentions "provider" or "libctx". So in
    /// the real openssl.wasm CLI embedding, this function is NEVER called
    /// during a normal command's lifecycle — the real handoff mechanism is
    /// `pqctoday_hsm_atexit_stash` above, registered via a genuine C
    /// `atexit()` in `cms_provider_init.c`, which reaches the SAME MEMFS
    /// file. This function is kept for the one caller where it IS correct:
    /// an embedder that explicitly calls `pqctoday_cms_shutdown()` (which
    /// does call `OSSL_PROVIDER_unload`) before letting `callMain` return.
    pub fn stash_before_finalize() {
        let blob = serialize_token_state();
        let _ = std::fs::write(HSM_STATE_FILE_PATH, &blob);
        STASH.with(|s| *s.borrow_mut() = Some(blob));
    }

    /// Take the persisted snapshot: the finalize stash if one exists,
    /// otherwise a snapshot of live state. Ownership transfers to the
    /// caller — copy it out, then call `pqctoday_hsm_state_free`.
    /// Returns NULL (len 0) only on alloc-level impossibilities.
    ///
    /// SAFE ONLY when called on a module instance that has not (yet)
    /// returned from a `callMain` invocation — see `stash_before_finalize`.
    #[unsafe(no_mangle)]
    pub unsafe extern "C" fn pqctoday_hsm_state_take(len_out: *mut u32) -> *mut u8 {
        if len_out.is_null() {
            return std::ptr::null_mut();
        }
        let blob = STASH
            .with(|s| s.borrow_mut().take())
            .unwrap_or_else(serialize_token_state);
        let mut boxed = blob.into_boxed_slice();
        let len = boxed.len() as u32;
        let ptr = boxed.as_mut_ptr();
        std::mem::forget(boxed);
        *len_out = len;
        ptr
    }

    /// Free a buffer returned by `pqctoday_hsm_state_take`.
    #[unsafe(no_mangle)]
    pub unsafe extern "C" fn pqctoday_hsm_state_free(ptr: *mut u8, len: u32) {
        if ptr.is_null() {
            return;
        }
        drop(Box::from_raw(std::slice::from_raw_parts_mut(
            ptr,
            len as usize,
        )));
    }

    /// Install a snapshot (see `deserialize_token_state`). Call at module
    /// boot, before or after `C_Initialize` (`init_token_store` keeps a
    /// non-empty `TOKEN_STORE`). Returns CKR_OK / CKR_GENERAL_ERROR.
    #[unsafe(no_mangle)]
    pub unsafe extern "C" fn pqctoday_hsm_state_load(ptr: *const u8, len: u32) -> u32 {
        if ptr.is_null() {
            return CKR_ARGUMENTS_BAD;
        }
        let buf = std::slice::from_raw_parts(ptr, len as usize);
        match deserialize_token_state(buf) {
            Ok(()) => CKR_OK,
            Err(rv) => rv,
        }
    }
}

#[cfg(target_os = "emscripten")]
pub use emscripten_exports::stash_before_finalize;

// ─────────────────────────────────────────────────────────────────────────
// Tests (native) — round-trip the SEAM, not just each half.
// ─────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::pad_label_32;

    fn reset() {
        TOKEN_STORE.with(|ts| ts.borrow_mut().clear());
        OBJECTS.with(|o| o.borrow_mut().clear());
    }

    fn sample_token(slot: u32) -> TokenState {
        TokenState {
            slot_id: slot,
            initialized: true,
            label: pad_label_32("snap-test"),
            login_state: LoginState::User, // must NOT survive the round-trip
            so_pin_salt: [7u8; 16],
            so_pin_hash: [8u8; 32],
            user_pin_salt: Some([9u8; 16]),
            user_pin_hash: Some([10u8; 32]),
        }
    }

    #[test]
    fn round_trip_restores_tokens_and_token_objects_only() {
        // The crate-wide lock, NOT a private one: these tests clear the
        // global OBJECTS / TOKEN_STORE, which every `native::*` test also
        // depends on (see native::mod::test_lock's own doc comment).
        let _g = crate::native::test_lock::acquire();
        reset();
        TOKEN_STORE.with(|ts| {
            ts.borrow_mut().insert(0, sample_token(0));
        });
        let mut token_obj: Attributes = HashMap::new();
        token_obj.insert(CKA_TOKEN, vec![1]);
        token_obj.insert(CKA_VALUE, vec![1, 2, 3, 4]);
        let mut session_obj: Attributes = HashMap::new();
        session_obj.insert(CKA_TOKEN, vec![0]);
        session_obj.insert(CKA_VALUE, vec![9, 9]);
        OBJECTS.with(|o| {
            let mut s = o.borrow_mut();
            s.insert(200, token_obj.clone());
            s.insert(201, session_obj);
        });

        let blob = serialize_token_state();
        reset();
        deserialize_token_state(&blob).expect("round trip");

        TOKEN_STORE.with(|ts| {
            let s = ts.borrow();
            let t = s.get(&0).expect("token restored");
            assert!(t.initialized);
            assert_eq!(t.label, pad_label_32("snap-test"));
            assert_eq!(t.user_pin_hash, Some([10u8; 32]));
            // Sessions are gone — login state resets.
            assert!(matches!(t.login_state, LoginState::Public));
        });
        OBJECTS.with(|o| {
            let s = o.borrow();
            assert_eq!(s.get(&200), Some(&token_obj), "token object restored");
            assert!(
                !s.contains_key(&201),
                "session object must not survive the snapshot"
            );
        });
    }

    #[test]
    fn truncated_snapshot_is_rejected_and_state_untouched() {
        // The crate-wide lock, NOT a private one: these tests clear the
        // global OBJECTS / TOKEN_STORE, which every `native::*` test also
        // depends on (see native::mod::test_lock's own doc comment).
        let _g = crate::native::test_lock::acquire();
        reset();
        TOKEN_STORE.with(|ts| {
            ts.borrow_mut().insert(0, sample_token(0));
        });
        let blob = serialize_token_state();

        // Pre-load some live state that a failed load must not disturb.
        reset();
        TOKEN_STORE.with(|ts| {
            ts.borrow_mut().insert(3, sample_token(3));
        });

        for cut in [0, 4, 9, blob.len() - 1] {
            assert!(
                deserialize_token_state(&blob[..cut]).is_err(),
                "truncation at {cut} must fail"
            );
        }
        assert!(
            deserialize_token_state(b"XXXXXXXXjunkjunkjunk").is_err(),
            "bad magic must fail"
        );
        TOKEN_STORE.with(|ts| {
            assert!(ts.borrow().contains_key(&3), "failed load must not wipe state");
        });
    }
}
