//! KMIP 3.0 algorithm registry — the [`KmipAlgorithm`] enum and its mappings
//! to/from wire-format codepoints and PKCS#11 mechanism IDs.
//!
//! Wire codepoints are the OASIS KMIP 3.0 `CryptographicAlgorithm`
//! enumeration values (see
//! `spec/oasis-kmip-3.0/kmip-spec-3.0-tags-enums.json`, regenerated by
//! `tools/extract_kmip_spec.rs` from the OASIS HTML).
//!
//! Per the 2026-06-07 workflow decision, **v0.1 ships FIPS-certified algorithms
//! only** (ML-KEM / ML-DSA / SLH-DSA / classical RSA-ECDSA-AES-HMAC). NIST
//! Round-3-alt and Round-4 candidates (Falcon, HQC, BIKE, FrodoKEM, Classic
//! McEliece, XMSS) are parked indefinitely — they have reserved codepoints
//! in `pkcs11-mech-manifest.json` but are not exposed here.
//!
//! ## Mech selection by operation
//!
//! KMIP wire only carries `CryptographicAlgorithm = ML-DSA-65`. The mech
//! the PKCS#11 bridge calls depends on which OPERATION is being requested:
//!
//! - `Create` (key generation) → `CKM_ML_DSA_KEY_PAIR_GEN` (`0x1c`)
//! - `Sign` / `SignatureVerify` → `CKM_ML_DSA` (`0x1d`)
//! - `Encrypt` (ML-KEM encapsulation) → `CKM_ML_KEM` (`0x17`)
//!
//! That's why [`KmipAlgorithm::to_pkcs11_mech`] takes a [`PkcsOp`] argument —
//! the mapping is `(algorithm, op) → mech`, not just `algorithm → mech`.

/// PKCS#11 mechanism ID (CK_MECHANISM_TYPE on the wire). Conceptually a
/// `CK_ULONG`; we model it as `u32` because every codepoint we ship fits.
pub type CkMechanismType = u32;

/// KMIP 3.0 `Recommended Curve` enumeration values (spec §4.16, tag `0x420075`).
/// Values verified against `spec/oasis-kmip-3.0/kmip-spec-3.0-tags-enums.json` —
/// used to resolve an ECDH `CreateKeyPair`'s curve. X25519/X448 key agreement is
/// `CryptographicAlgorithm=ECDH` + `RecommendedCurve = CURVE25519 / CURVE448`.
pub mod recommended_curve {
    pub const P_256: u32 = 0x00000007;
    pub const P_384: u32 = 0x0000000a;
    pub const P_521: u32 = 0x0000000d;
    pub const CURVE25519: u32 = 0x00000045;
    pub const CURVE448: u32 = 0x00000046;
}

// ── Standard PKCS#11 v3.2 PQC mech codepoints ────────────────────────────
// Re-exported from the engine (`softhsmrustv3::constants`) — single source
// of truth, values per the normative pkcs11t.h.
//
// History (compliance-audit B-1, fixed by K5): the KMIP layer used to define
// a "vendor" block CKM_PQCTODAY_* at 0x4032–0x4037. Those values collide
// with the OASIS-assigned CKM_HSS_KEY_PAIR_GEN / CKM_HSS /
// CKM_XMSS_KEY_PAIR_GEN / CKM_XMSSMT_KEY_PAIR_GEN / CKM_XMSS / CKM_XMSSMT
// (pkcs11t.h:1218-1224) and sat below CKM_VENDOR_DEFINED (0x80000000),
// violating the PKCS#11 vendor-extension rule. All six had standard v3.2
// equivalents, so the vendor block is retired (codepoints stay reserved
// forever per pkcs11-vendor-mech-allocation.md's mutation policy). Any
// future genuinely vendor-specific mech MUST be allocated at
// `0x8000_0000 | n`.

pub use softhsmrustv3::constants::{
    CKM_HSS, CKM_HSS_KEY_PAIR_GEN, CKM_ML_DSA, CKM_ML_DSA_KEY_PAIR_GEN, CKM_ML_KEM,
    CKM_ML_KEM_KEY_PAIR_GEN, CKM_SLH_DSA, CKM_SLH_DSA_KEY_PAIR_GEN,
    // BSI TR-02102-1 recommended KEMs (vendor mechanisms — see
    // pqctoday-priv/docs/platform/data/pkcs11-vendor-mech-allocation.md §1.4).
    CKM_PQCTODAY_FRODOKEM_KEY_PAIR_GEN, CKM_PQCTODAY_FRODOKEM_ENCAPSULATE,
    CKM_PQCTODAY_CLASSIC_MCELIECE_KEY_PAIR_GEN, CKM_PQCTODAY_CLASSIC_MCELIECE_ENCAPSULATE,
};

// ── Standard PKCS#11 v3.2 mech codepoints used by classical algos ──────────
// From src/lib/pkcs11/pkcs11t.h (in pqctoday-hsm root). These do NOT live in
// the vendor manifest — they are part of the OASIS PKCS#11 v3.2 normative
// surface.

pub const CKM_RSA_PKCS_KEY_PAIR_GEN: CkMechanismType = 0x0000;
pub const CKM_RSA_PKCS: CkMechanismType              = 0x0001;
pub const CKM_RSA_PKCS_OAEP: CkMechanismType         = 0x0009;
pub const CKM_RSA_PKCS_PSS: CkMechanismType          = 0x000D;

pub const CKM_EC_KEY_PAIR_GEN: CkMechanismType = 0x1040;
pub const CKM_ECDSA: CkMechanismType           = 0x1041;
pub const CKM_ECDSA_SHA256: CkMechanismType    = 0x1044;

/// PKCS#11 v3.2 §6.24 — EdDSA key pair generation (Edwards curve). Value
/// verified against `rust/src/constants.rs` (softhsmrustv3's own mirror of
/// `pkcs11t.h`, the project's source of truth for `CK*` values).
pub const CKM_EC_EDWARDS_KEY_PAIR_GEN: CkMechanismType = 0x1055;
/// PKCS#11 v3.2 §6.24 — EdDSA sign/verify (Ed25519/Ed448). Same
/// verification source as above.
pub const CKM_EDDSA: CkMechanismType = 0x1057;

pub const CKM_AES_KEY_GEN: CkMechanismType = 0x1080;
pub const CKM_AES_GCM: CkMechanismType     = 0x1087;

/// PKCS#11 v3.2 §6.20 — IETF ChaCha20 stream cipher. Codepoint
/// `0x1226` verified from the normative `pkcs11t.h`
/// (`src/lib/pkcs11/pkcs11t.h:1132`) — the earlier `0x1071` here was a
/// drifted duplicate that desynchronised from the engine when
/// `softhsmrustv3::constants` was corrected to the spec value.
pub const CKM_CHACHA20: CkMechanismType         = 0x1226;
/// PKCS#11 v3.2 §6.20 — IETF ChaCha20-Poly1305 AEAD (RFC 8439).
/// Codepoint `0x4021` per `pkcs11t.h:1187` (was a drifted `0x1093`).
pub const CKM_CHACHA20_POLY1305: CkMechanismType = 0x4021;

pub const CKM_GENERIC_SECRET_KEY_GEN: CkMechanismType = 0x0350;
pub const CKM_SHA256_HMAC: CkMechanismType            = 0x0251;
pub const CKM_SHA384_HMAC: CkMechanismType            = 0x0261;
pub const CKM_SHA512_HMAC: CkMechanismType            = 0x0271;

/// PKCS#11 operation that the bridge is about to perform — disambiguates the
/// `(KmipAlgorithm, op) → mech` mapping. KMIP wire format carries the
/// algorithm; the operation is determined by the KMIP op handler that owns
/// the request.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PkcsOp {
    /// Key pair generation (for asymmetric algos) or symmetric key gen.
    KeyGen,
    /// Sign / SignatureVerify.
    SignVerify,
    /// KMIP Encrypt — for ML-KEM this is encapsulation; for AES/RSA it's
    /// classical encryption.
    Encrypt,
    /// KMIP Decrypt — symmetric to Encrypt; for ML-KEM this is decapsulation.
    Decrypt,
    /// MAC generation / verification.
    Mac,
}

/// KMIP 3.0 `CryptographicAlgorithm` enum value — the subset we expose in v0.1.
///
/// Wire-format `Enumeration` codepoint comes from OASIS KMIP 3.0 §10.2.6,
/// extracted into `spec/oasis-kmip-3.0/kmip-spec-3.0-tags-enums.json`.
/// Symbolic names follow the OASIS spec's hyphenation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, serde::Serialize, serde::Deserialize)]
pub enum KmipAlgorithm {
    // ── Classical baseline ────────────────────────────────────────────────
    // Deprecated symmetric primitives (DES=0x01, 3DES=0x02) and the
    // discrete-log signature algorithm (DSA=0x05) are explicitly NOT
    // supported per pqctoday's deprecated-mechanism policy. Register
    // requests carrying those codepoints surface as `InvalidMessage`
    // via `from_wire_value` returning None.
    Aes,           // 0x03
    Rsa,           // 0x04
    Ecdsa,         // 0x06 — covers ECDSA over any curve; curve = attribute
    HmacSha256,    // 0x09
    HmacSha384,    // 0x0a
    HmacSha512,    // 0x0b
    Ecdh,          // 0x0e
    /// IETF ChaCha20 stream cipher (RFC 8439) — KMIP 3.0 §11
    /// `Cryptographic Algorithm` codepoint `0x1c`.
    ChaCha20,
    /// IETF ChaCha20-Poly1305 AEAD (RFC 8439) — codepoint `0x1e`.
    /// Distinct from `ChaCha20` so the shim picks the right primitive
    /// (separate auth-tag emit path) without needing a `BlockCipherMode`
    /// hint.
    ChaCha20Poly1305,
    /// EdDSA over Curve25519 (RFC 8032) — KMIP 3.0 §11 codepoint `0x37`
    /// (base spec enum, predates WD19). Edwards-form signing curve —
    /// distinct key type, mechanism, and OID from `X25519` (Montgomery-form
    /// key agreement on the same underlying curve; not yet a KmipAlgorithm
    /// variant — see `hybrid_kem.rs` for X25519's only current use, inside
    /// the hybrid KEM combiner). 2026-07-05 (P1): keygen/sign/verify all
    /// pre-existed at the PKCS#11 layer (`ffi.rs` CKM_EC_EDWARDS_KEY_PAIR_GEN
    /// / CKM_EDDSA) — this variant is the KMIP-layer plumbing that was
    /// missing.
    Ed25519,       // 0x37

    // ── FIPS PQC — ML-KEM (FIPS 203) ──────────────────────────────────────
    MlKem512,      // 0x39
    MlKem768,      // 0x3a
    MlKem1024,     // 0x3b

    // ── FIPS PQC — ML-DSA (FIPS 204) ──────────────────────────────────────
    MlDsa44,       // 0x3c
    MlDsa65,       // 0x3d
    MlDsa87,       // 0x3e

    // ── FIPS PQC — SLH-DSA (FIPS 205) ─────────────────────────────────────
    SlhDsaSha2_128s,  // 0x3f
    SlhDsaSha2_128f,  // 0x40
    SlhDsaSha2_192s,  // 0x41
    SlhDsaSha2_192f,  // 0x42
    SlhDsaSha2_256s,  // 0x43
    SlhDsaSha2_256f,  // 0x44
    SlhDsaShake128s,  // 0x45
    SlhDsaShake128f,  // 0x46
    SlhDsaShake192s,  // 0x47
    SlhDsaShake192f,  // 0x48
    SlhDsaShake256s,  // 0x49
    SlhDsaShake256f,  // 0x4a

    // ── KMIP 3.0 WD19 hybrid KEMs (K6) ────────────────────────────────────
    // ML-KEM composed with a classical ECDH per draft-ietf-tls-ecdhe-mlkem.
    // These do NOT map to a single PKCS#11 mechanism — the engine composes the
    // two component keys (see `softhsmrustv3::native::hybrid`).
    X25519MlKem768,     // 0x5c (WD19)
    SecP256r1MlKem768,  // 0x5d (WD19)
    // SecP384r1MLKEM1024 (draft-ietf-tls-ecdhe-mlkem group 0x11ED) has NO WD19
    // CryptographicAlgorithm value (WD19 stops at 0x5D). Assigned a codepoint
    // in the `8XXXXXXX` Extensions range — KMIP 3.0's OWN spec-sanctioned
    // vendor-extension convention for enumeration values (every enum table,
    // including this one — §11.12 Table 543 Cryptographic Algorithm
    // Enumeration — lists "Extensions 8XXXXXXX" as a valid entry; confirmed
    // present in 60 enum tables across the spec). This is a real, working
    // extension codepoint per spec convention, not an ad hoc invention — it
    // is simply not (yet) an OASIS-assigned standard value, pending a future
    // official assignment for this algorithm.
    SecP384r1MlKem1024, // 0x8000005e (spec-convention vendor extension, §11.12)

    // ── BSI TR-02102-1 §2.4.2 — Classic McEliece ─────────────────────────
    // KMIP's own `CryptographicAlgorithm` enum already has REAL OASIS
    // codepoints for McEliece (0x34 generic, 0x35 = McEliece-6960119, 0x36 =
    // McEliece-8192128 — confirmed directly in
    // `spec/oasis-kmip-3.0/kmip-spec-3.0-tags-enums.json`) — but none
    // specific to `mceliece6688128` (BSI's Category-5 pick, the only
    // parameter set this engine implements — see the FrodoKEM/
    // Classic-McEliece/HQC implementation plan Phase 0.5). Using the
    // generic 0x34 codepoint here; if a second parameter set is added
    // later, disambiguation will need a real attribute (mirrors how `Ecdh`
    // is one variant covering multiple curves via `RecommendedCurve`), not
    // a rename of this variant.
    ClassicMcEliece6688128, // 0x00000034 (OASIS, generic "McEliece")

    // ── BSI TR-02102-1 §2.4.1 — FrodoKEM ──────────────────────────────────
    // No OASIS codepoint exists for FrodoKEM at all (confirmed: absent from
    // the same tags-enums.json). Vendor/extension range, continuing after
    // `SecP384r1MlKem1024` (0x8000005e) — same posture as that entry.
    // eFrodoKEM (ephemeral) variants intentionally not included — see
    // implementation plan Phase 0.8.
    FrodoKem640Aes,     // 0x8000005f (vendor/extension — non-standard)
    FrodoKem640Shake,   // 0x80000060 (vendor/extension — non-standard)
    FrodoKem976Aes,     // 0x80000061 (vendor/extension — non-standard)
    FrodoKem976Shake,   // 0x80000062 (vendor/extension — non-standard)
    FrodoKem1344Aes,    // 0x80000063 (vendor/extension — non-standard)
    FrodoKem1344Shake,  // 0x80000064 (vendor/extension — non-standard)

    // ── HSS/LMS (RFC 8554) ─────────────────────────────────────────────────
    // KMIP 3.0's Cryptographic Algorithm Enumeration (§11.12 Table 545) has
    // NO entry for HSS/LMS — verified directly against the spec text (both
    // the base CSD01 and the WD19 PQC draft): only `XMSS` (0x32) is listed,
    // a genuine gap in the spec, not something missed here. Assigned the
    // next free codepoint in the same `8XXXXXXX` Extensions range as
    // `SecP384r1MlKem1024`/the FrodoKEM block above (0x80000065 — 0x5f-0x64
    // are taken by FrodoKEM), following the identical spec-sanctioned
    // vendor-extension convention (§11.12). Represents HSS generically —
    // per RFC 8554 §6, a single-level HSS key IS an LMS key, so this one
    // variant covers both; the specific LMS/LM-OTS parameter combination is
    // carried as an engine attribute (`CKA_LMS_PARAM_SET`), the same pattern
    // `Ecdsa` already uses for its curve ("covers ECDSA over any curve;
    // curve = attribute").
    Hss, // 0x80000065 (spec-convention vendor extension, §11.12)

    // ── LAMPS composite signatures (draft-ietf-lamps-pq-composite-sigs-19) ──
    // Composite-sig OIDs have no OASIS `CryptographicAlgorithm` codepoint
    // (they're an X.509 AlgorithmIdentifier OID, not a KMIP enum value the
    // spec assigns) — same §11.12 vendor-extension convention as the PQC
    // KEM block above, continuing the free range after `Hss` (0x80000065).
    // Each variant's `to_pkcs11_mech` is intentionally `None` for every
    // `PkcsOp` (see below): a composite signature is never produced by ONE
    // engine mechanism call the way `CKM_ECDSA_SHA256` is — it's two
    // independent single-algorithm signs assembled by the kmip crate (see
    // `ops/composite_sig.rs`), mirroring how `is_hybrid_kem` already
    // documents "no single PKCS#11 mechanism" for the K6 hybrid KEMs.
    // OID values ported verbatim from the hub's own
    // `certBuilder.ts::COMPOSITE_PROFILE_MLDSA*` constants (already used in
    // this monorepo, cross-checked against `pkcs11-provider/src/
    // composite.c`'s independent implementation of the same draft) — not
    // retyped from the draft text.
    /// id-MLDSA44-RSA2048-PSS-SHA256 — OID `1.3.6.1.5.5.7.6.37`.
    CompositeMlDsa44Rsa2048PssSha256, // 0x80000066 (spec-convention vendor extension, §11.12)
    /// id-MLDSA65-ECDSA-P256-SHA512 — OID `1.3.6.1.5.5.7.6.45`.
    CompositeMlDsa65EcdsaP256Sha512, // 0x80000067 (spec-convention vendor extension, §11.12)
    /// id-MLDSA87-ECDSA-P384-SHA512 — OID `1.3.6.1.5.5.7.6.49`.
    CompositeMlDsa87EcdsaP384Sha512, // 0x80000068 (spec-convention vendor extension, §11.12)
}

impl KmipAlgorithm {
    /// Wire-format `CryptographicAlgorithm` enumeration value (OASIS KMIP 3.0
    /// §10.2.6). The wire encoding is `Enumeration` (item type `0x05`) with
    /// this `u32` as the value.
    pub const fn to_wire_value(self) -> u32 {
        use KmipAlgorithm::*;
        match self {
            Aes        => 0x00000003,
            Rsa        => 0x00000004,
            Ecdsa      => 0x00000006,
            HmacSha256 => 0x00000009,
            HmacSha384 => 0x0000000a,
            HmacSha512 => 0x0000000b,
            Ecdh       => 0x0000000e,
            ChaCha20         => 0x0000001c,
            ChaCha20Poly1305 => 0x0000001e,
            Ed25519    => 0x00000037,
            MlKem512   => 0x00000039,
            MlKem768   => 0x0000003a,
            MlKem1024  => 0x0000003b,
            MlDsa44    => 0x0000003c,
            MlDsa65    => 0x0000003d,
            MlDsa87    => 0x0000003e,
            SlhDsaSha2_128s  => 0x0000003f,
            SlhDsaSha2_128f  => 0x00000040,
            SlhDsaSha2_192s  => 0x00000041,
            SlhDsaSha2_192f  => 0x00000042,
            SlhDsaSha2_256s  => 0x00000043,
            SlhDsaSha2_256f  => 0x00000044,
            SlhDsaShake128s  => 0x00000045,
            SlhDsaShake128f  => 0x00000046,
            SlhDsaShake192s  => 0x00000047,
            SlhDsaShake192f  => 0x00000048,
            SlhDsaShake256s  => 0x00000049,
            SlhDsaShake256f  => 0x0000004a,
            X25519MlKem768    => 0x0000005c,
            SecP256r1MlKem768 => 0x0000005d,
            SecP384r1MlKem1024 => 0x8000005e,
            ClassicMcEliece6688128 => 0x00000034,
            FrodoKem640Aes    => 0x8000005f,
            FrodoKem640Shake  => 0x80000060,
            FrodoKem976Aes    => 0x80000061,
            FrodoKem976Shake  => 0x80000062,
            FrodoKem1344Aes   => 0x80000063,
            FrodoKem1344Shake => 0x80000064,
            Hss => 0x80000065,
            CompositeMlDsa44Rsa2048PssSha256 => 0x80000066,
            CompositeMlDsa65EcdsaP256Sha512 => 0x80000067,
            CompositeMlDsa87EcdsaP384Sha512 => 0x80000068,
        }
    }

    /// Reverse of [`Self::to_wire_value`]. Returns `None` for values outside
    /// the algorithm set this v0.1 supports (mostly FIPS-certified
    /// primitives, plus a couple of NIST-recognized or vendor-extension
    /// entries — SecP384r1MlKem1024, Hss — that aren't FIPS numbers).
    pub const fn from_wire_value(v: u32) -> Option<Self> {
        use KmipAlgorithm::*;
        Some(match v {
            0x00000003 => Aes,
            0x00000004 => Rsa,
            0x00000006 => Ecdsa,
            0x00000009 => HmacSha256,
            0x0000000a => HmacSha384,
            0x0000000b => HmacSha512,
            0x0000000e => Ecdh,
            0x0000001c => ChaCha20,
            0x0000001e => ChaCha20Poly1305,
            0x00000037 => Ed25519,
            0x00000039 => MlKem512,
            0x0000003a => MlKem768,
            0x0000003b => MlKem1024,
            0x0000003c => MlDsa44,
            0x0000003d => MlDsa65,
            0x0000003e => MlDsa87,
            0x0000003f => SlhDsaSha2_128s,
            0x00000040 => SlhDsaSha2_128f,
            0x00000041 => SlhDsaSha2_192s,
            0x00000042 => SlhDsaSha2_192f,
            0x00000043 => SlhDsaSha2_256s,
            0x00000044 => SlhDsaSha2_256f,
            0x00000045 => SlhDsaShake128s,
            0x00000046 => SlhDsaShake128f,
            0x00000047 => SlhDsaShake192s,
            0x00000048 => SlhDsaShake192f,
            0x00000049 => SlhDsaShake256s,
            0x0000004a => SlhDsaShake256f,
            0x0000005c => X25519MlKem768,
            0x0000005d => SecP256r1MlKem768,
            0x8000005e => SecP384r1MlKem1024,
            0x00000034 => ClassicMcEliece6688128,
            0x8000005f => FrodoKem640Aes,
            0x80000060 => FrodoKem640Shake,
            0x80000061 => FrodoKem976Aes,
            0x80000062 => FrodoKem976Shake,
            0x80000063 => FrodoKem1344Aes,
            0x80000064 => FrodoKem1344Shake,
            0x80000065 => Hss,
            0x80000066 => CompositeMlDsa44Rsa2048PssSha256,
            0x80000067 => CompositeMlDsa65EcdsaP256Sha512,
            0x80000068 => CompositeMlDsa87EcdsaP384Sha512,
            _ => return None,
        })
    }

    /// `true` for a LAMPS draft-19 composite-signature algorithm — two
    /// independent component signatures over the same message
    /// representative, never one engine mechanism call (see
    /// `ops/composite_sig.rs`).
    pub const fn is_composite_sig(self) -> bool {
        matches!(
            self,
            KmipAlgorithm::CompositeMlDsa44Rsa2048PssSha256
                | KmipAlgorithm::CompositeMlDsa65EcdsaP256Sha512
                | KmipAlgorithm::CompositeMlDsa87EcdsaP384Sha512
        )
    }

    /// `true` if this is a KMIP 3.0 WD19 hybrid KEM (K6), composed in-process
    /// from ML-KEM-768 + a classical ECDH rather than a single PKCS#11 mech.
    pub const fn is_hybrid_kem(self) -> bool {
        matches!(
            self,
            KmipAlgorithm::X25519MlKem768
                | KmipAlgorithm::SecP256r1MlKem768
                | KmipAlgorithm::SecP384r1MlKem1024
        )
    }

    /// Map to the engine's [`crate::hybrid_kem::Hybrid`] combiner (a re-export
    /// of `softhsmrustv3::native::hybrid::Hybrid`), or `None` if not hybrid.
    pub const fn hybrid_kem(self) -> Option<crate::hybrid_kem::Hybrid> {
        match self {
            KmipAlgorithm::X25519MlKem768 => Some(crate::hybrid_kem::Hybrid::X25519MlKem768),
            KmipAlgorithm::SecP256r1MlKem768 => Some(crate::hybrid_kem::Hybrid::SecP256r1MlKem768),
            KmipAlgorithm::SecP384r1MlKem1024 => Some(crate::hybrid_kem::Hybrid::SecP384r1MlKem1024),
            _ => None,
        }
    }

    /// `true` if this algorithm is one of the NIST FIPS PQC standards
    /// (FIPS 203 ML-KEM, FIPS 204 ML-DSA, FIPS 205 SLH-DSA) — or a
    /// composite signature built on one. A composite is quantum-safe via
    /// its ML-DSA half exactly the way a hybrid KEM is via its ML-KEM half
    /// (`quantum_safe_with_length`'s existing "secure while EITHER
    /// component holds" rule) — this is what makes composite ML-DSA+RSA/
    /// ECDSA a PQC-migration primitive at all, not a classical one.
    pub const fn is_pqc(self) -> bool {
        use KmipAlgorithm::*;
        matches!(
            self,
            MlKem512 | MlKem768 | MlKem1024
                | MlDsa44 | MlDsa65 | MlDsa87
                | SlhDsaSha2_128s | SlhDsaSha2_128f
                | SlhDsaSha2_192s | SlhDsaSha2_192f
                | SlhDsaSha2_256s | SlhDsaSha2_256f
                | SlhDsaShake128s | SlhDsaShake128f
                | SlhDsaShake192s | SlhDsaShake192f
                | SlhDsaShake256s | SlhDsaShake256f
                | CompositeMlDsa44Rsa2048PssSha256
                | CompositeMlDsa65EcdsaP256Sha512
                | CompositeMlDsa87EcdsaP384Sha512
        )
    }

    /// Length-aware quantum-safety classification for the playground's
    /// keystore badges (NOT the KMIP §11 `Quantum Safe` attribute claim,
    /// which `register_import_export::algorithm_is_quantum_safe` gates and
    /// the OASIS corpus pins to PQC-only). Symmetric primitives count as
    /// safe at ≥ 256-bit (Grover margin — AES-128 is flagged at-risk, the
    /// Migration tab's whole point); hybrids count as safe (secure while
    /// EITHER component holds); classical public-key algorithms do not.
    pub const fn quantum_safe_with_length(self, length_bits: u32) -> bool {
        use KmipAlgorithm::*;
        match self {
            Aes | ChaCha20 | ChaCha20Poly1305 | HmacSha256 | HmacSha384 | HmacSha512 => {
                length_bits >= 256
            }
            Rsa | Ecdsa | Ecdh | Ed25519 => false,
            X25519MlKem768 | SecP256r1MlKem768 => true,
            _ => self.is_pqc(),
        }
    }

    /// PKCS#11 mech to call for `(self, op)`. Returns `None` if the operation
    /// is not defined for this algorithm (e.g. `KeyGen` for HMAC, `SignVerify`
    /// for ML-KEM).
    ///
    /// PQC families map to the standard PKCS#11 v3.2 mechanisms
    /// (`CKM_ML_KEM* / CKM_ML_DSA* / CKM_SLH_DSA*`) re-exported from
    /// `softhsmrustv3::constants` — pinned by the
    /// `standard_codepoint_consistency_test` below.
    pub const fn to_pkcs11_mech(self, op: PkcsOp) -> Option<CkMechanismType> {
        use KmipAlgorithm::*;
        use PkcsOp::*;
        match (self, op) {
            // ── ML-KEM (FIPS 203) ─────────────────────────────────────────
            (MlKem512 | MlKem768 | MlKem1024, KeyGen) =>
                Some(CKM_ML_KEM_KEY_PAIR_GEN),
            (MlKem512 | MlKem768 | MlKem1024, Encrypt | Decrypt) =>
                Some(CKM_ML_KEM),

            // ── FrodoKEM (BSI TR-02102-1 §2.4.1) ──────────────────────────
            (FrodoKem640Aes | FrodoKem640Shake | FrodoKem976Aes
                | FrodoKem976Shake | FrodoKem1344Aes | FrodoKem1344Shake, KeyGen)
                => Some(CKM_PQCTODAY_FRODOKEM_KEY_PAIR_GEN),
            (FrodoKem640Aes | FrodoKem640Shake | FrodoKem976Aes
                | FrodoKem976Shake | FrodoKem1344Aes | FrodoKem1344Shake, Encrypt | Decrypt)
                => Some(CKM_PQCTODAY_FRODOKEM_ENCAPSULATE),

            // ── Classic McEliece (BSI TR-02102-1 §2.4.2) ──────────────────
            (ClassicMcEliece6688128, KeyGen) =>
                Some(CKM_PQCTODAY_CLASSIC_MCELIECE_KEY_PAIR_GEN),
            (ClassicMcEliece6688128, Encrypt | Decrypt) =>
                Some(CKM_PQCTODAY_CLASSIC_MCELIECE_ENCAPSULATE),

            // ── ML-DSA (FIPS 204) ─────────────────────────────────────────
            (MlDsa44 | MlDsa65 | MlDsa87, KeyGen) =>
                Some(CKM_ML_DSA_KEY_PAIR_GEN),
            (MlDsa44 | MlDsa65 | MlDsa87, SignVerify) =>
                Some(CKM_ML_DSA),

            // ── SLH-DSA (FIPS 205) ────────────────────────────────────────
            // PKCS#11 v3.2 §6.69 — CKM_SLH_DSA_KEY_PAIR_GEN covers all 12
            // parameter sets (variant selected via CKA_PARAMETER_SET).
            // Pre-K5 this was mislabeled as the HSS keygen codepoint
            // (compliance-audit B-1).
            (SlhDsaSha2_128s | SlhDsaSha2_128f
                | SlhDsaSha2_192s | SlhDsaSha2_192f
                | SlhDsaSha2_256s | SlhDsaSha2_256f
                | SlhDsaShake128s | SlhDsaShake128f
                | SlhDsaShake192s | SlhDsaShake192f
                | SlhDsaShake256s | SlhDsaShake256f, KeyGen)
                => Some(CKM_SLH_DSA_KEY_PAIR_GEN),
            (SlhDsaSha2_128s | SlhDsaSha2_128f
                | SlhDsaSha2_192s | SlhDsaSha2_192f
                | SlhDsaSha2_256s | SlhDsaSha2_256f
                | SlhDsaShake128s | SlhDsaShake128f
                | SlhDsaShake192s | SlhDsaShake192f
                | SlhDsaShake256s | SlhDsaShake256f, SignVerify)
                => Some(CKM_SLH_DSA),

            // ── RSA classical ─────────────────────────────────────────────
            (Rsa, KeyGen)     => Some(CKM_RSA_PKCS_KEY_PAIR_GEN),
            (Rsa, SignVerify) => Some(CKM_RSA_PKCS_PSS),
            (Rsa, Encrypt | Decrypt) => Some(CKM_RSA_PKCS_OAEP),

            // ── ECDSA / ECDH classical ────────────────────────────────────
            (Ecdsa, KeyGen) | (Ecdh, KeyGen) => Some(CKM_EC_KEY_PAIR_GEN),
            (Ecdsa, SignVerify) => Some(CKM_ECDSA),

            // ── AES symmetric ─────────────────────────────────────────────
            (Aes, KeyGen) => Some(CKM_AES_KEY_GEN),
            (Aes, Encrypt | Decrypt) => Some(CKM_AES_GCM),

            // ── ChaCha20 family ───────────────────────────────────────────
            // KMIP carries ChaCha20 (stream) and ChaCha20-Poly1305 (AEAD)
            // as distinct algorithms — see KMIP 3.0 §11 codepoints
            // `0x1c` / `0x1e`. Encrypt/Decrypt routes straight to the
            // softhsmv3 PKCS#11 mechanism; the underlying cipher lives
            // entirely inside that crate.
            (ChaCha20, Encrypt | Decrypt) => Some(CKM_CHACHA20),
            (ChaCha20Poly1305, Encrypt | Decrypt) => Some(CKM_CHACHA20_POLY1305),

            // ── HMAC families ─────────────────────────────────────────────
            (HmacSha256 | HmacSha384 | HmacSha512, KeyGen) =>
                Some(CKM_GENERIC_SECRET_KEY_GEN),
            (HmacSha256, Mac) => Some(CKM_SHA256_HMAC),
            (HmacSha384, Mac) => Some(CKM_SHA384_HMAC),
            (HmacSha512, Mac) => Some(CKM_SHA512_HMAC),

            // ── Ed25519 (RFC 8032 EdDSA) ────────────────────────────────────
            (Ed25519, KeyGen) => Some(CKM_EC_EDWARDS_KEY_PAIR_GEN),
            (Ed25519, SignVerify) => Some(CKM_EDDSA),

            // ── HSS/LMS (RFC 8554) ────────────────────────────────────────
            (Hss, KeyGen) => Some(CKM_HSS_KEY_PAIR_GEN),
            (Hss, SignVerify) => Some(CKM_HSS),

            // Any other (algorithm, op) pair is undefined.
            _ => None,
        }
    }

    /// Spec-text symbolic name (matches OASIS spelling). Useful for logging
    /// and error messages.
    pub const fn spec_name(self) -> &'static str {
        use KmipAlgorithm::*;
        match self {
            Aes        => "AES",
            Rsa        => "RSA",
            Ecdsa      => "ECDSA",
            HmacSha256 => "HMAC-SHA256",
            HmacSha384 => "HMAC-SHA384",
            HmacSha512 => "HMAC-SHA512",
            Ecdh       => "ECDH",
            ChaCha20         => "ChaCha20",
            ChaCha20Poly1305 => "ChaCha20-Poly1305",
            Ed25519    => "Ed25519",
            MlKem512   => "ML-KEM-512",
            MlKem768   => "ML-KEM-768",
            MlKem1024  => "ML-KEM-1024",
            MlDsa44    => "ML-DSA-44",
            MlDsa65    => "ML-DSA-65",
            MlDsa87    => "ML-DSA-87",
            SlhDsaSha2_128s  => "SLH-DSA-SHA2-128s",
            SlhDsaSha2_128f  => "SLH-DSA-SHA2-128f",
            SlhDsaSha2_192s  => "SLH-DSA-SHA2-192s",
            SlhDsaSha2_192f  => "SLH-DSA-SHA2-192f",
            SlhDsaSha2_256s  => "SLH-DSA-SHA2-256s",
            SlhDsaSha2_256f  => "SLH-DSA-SHA2-256f",
            SlhDsaShake128s  => "SLH-DSA-SHAKE-128s",
            SlhDsaShake128f  => "SLH-DSA-SHAKE-128f",
            SlhDsaShake192s  => "SLH-DSA-SHAKE-192s",
            SlhDsaShake192f  => "SLH-DSA-SHAKE-192f",
            SlhDsaShake256s  => "SLH-DSA-SHAKE-256s",
            SlhDsaShake256f  => "SLH-DSA-SHAKE-256f",
            X25519MlKem768    => "X25519MLKEM768",
            SecP256r1MlKem768 => "SecP256r1MLKEM768",
            SecP384r1MlKem1024 => "SecP384r1MLKEM1024",
            ClassicMcEliece6688128 => "Classic-McEliece-6688128",
            FrodoKem640Aes    => "FrodoKEM-640-AES",
            FrodoKem640Shake  => "FrodoKEM-640-SHAKE",
            FrodoKem976Aes    => "FrodoKEM-976-AES",
            FrodoKem976Shake  => "FrodoKEM-976-SHAKE",
            FrodoKem1344Aes   => "FrodoKEM-1344-AES",
            FrodoKem1344Shake => "FrodoKEM-1344-SHAKE",
            Hss => "HSS",
            // Canonical, self-describing names — NOT the 2-part
            // `primary-secondary` shape `policy::rule::
            // HybridDualSignRequirement` synthesizes (`format!("{}-{}",
            // primary, secondary)`). A policy author targeting one of these
            // via that rule needs `primary="ML-DSA-65"` +
            // `secondary="ECDSA-P256-SHA512"` (etc.) to reproduce this exact
            // string — verified by a real test in WP-C12, not assumed here.
            CompositeMlDsa44Rsa2048PssSha256 => "ML-DSA-44-RSA2048-PSS",
            CompositeMlDsa65EcdsaP256Sha512 => "ML-DSA-65-ECDSA-P256",
            CompositeMlDsa87EcdsaP384Sha512 => "ML-DSA-87-ECDSA-P384",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every variant of `KmipAlgorithm`; centralising the enumeration so each
    /// test below exhausts the whole set without repeating itself.
    fn all_algos() -> &'static [KmipAlgorithm] {
        use KmipAlgorithm::*;
        &[
            Aes, Rsa, Ecdsa, HmacSha256, HmacSha384, HmacSha512, Ecdh,
            MlKem512, MlKem768, MlKem1024,
            MlDsa44, MlDsa65, MlDsa87,
            SlhDsaSha2_128s, SlhDsaSha2_128f,
            SlhDsaSha2_192s, SlhDsaSha2_192f,
            SlhDsaSha2_256s, SlhDsaSha2_256f,
            SlhDsaShake128s, SlhDsaShake128f,
            SlhDsaShake192s, SlhDsaShake192f,
            SlhDsaShake256s, SlhDsaShake256f,
            X25519MlKem768, SecP256r1MlKem768, SecP384r1MlKem1024,
            ClassicMcEliece6688128,
            FrodoKem640Aes, FrodoKem640Shake, FrodoKem976Aes, FrodoKem976Shake,
            FrodoKem1344Aes, FrodoKem1344Shake,
            Hss,
            CompositeMlDsa44Rsa2048PssSha256,
            CompositeMlDsa65EcdsaP256Sha512,
            CompositeMlDsa87EcdsaP384Sha512,
        ]
    }

    #[test]
    fn wire_value_round_trips_for_every_variant() {
        for &a in all_algos() {
            let v = a.to_wire_value();
            assert_eq!(KmipAlgorithm::from_wire_value(v), Some(a), "{}", a.spec_name());
        }
    }

    /// Merge safety net: two independently-developed branches each picking
    /// the "next free" vendor codepoint in the `8XXXXXXX` Extensions range
    /// is exactly the kind of collision that merges silently — this would
    /// have caught the real one found while merging Hss (0x8000005f) with
    /// the FrodoKEM block (which also claimed 0x8000005f), before Hss was
    /// renumbered to 0x80000065.
    #[test]
    fn every_wire_value_is_unique() {
        use std::collections::HashMap;
        let mut seen: HashMap<u32, KmipAlgorithm> = HashMap::new();
        for &a in all_algos() {
            let v = a.to_wire_value();
            if let Some(prev) = seen.insert(v, a) {
                panic!("codepoint {v:#x} claimed by both {} and {}", prev.spec_name(), a.spec_name());
            }
        }
    }

    #[test]
    fn unknown_wire_value_is_none() {
        // 0x4b is one past the last FIPS PQC entry we ship.
        assert_eq!(KmipAlgorithm::from_wire_value(0x0000004b), None);
        // Falcon would be at 0x4b+ if added; parked indefinitely per
        // workflow decision §4.
        assert_eq!(KmipAlgorithm::from_wire_value(0x00000100), None);
    }

    #[test]
    fn pqc_classifier_matches_fips_set() {
        for &a in all_algos() {
            let expected = matches!(
                a.spec_name(),
                s if s.starts_with("ML-KEM-") || s.starts_with("ML-DSA-") || s.starts_with("SLH-DSA-")
            );
            assert_eq!(a.is_pqc(), expected, "{}", a.spec_name());
        }
    }

    #[test]
    fn ml_kem_768_keygen_dispatches_to_standard_mech() {
        assert_eq!(
            KmipAlgorithm::MlKem768.to_pkcs11_mech(PkcsOp::KeyGen),
            Some(CKM_ML_KEM_KEY_PAIR_GEN),
        );
        assert_eq!(CKM_ML_KEM_KEY_PAIR_GEN, 0x0f);
    }

    #[test]
    fn ml_dsa_65_sign_verify_dispatches_to_standard_mech() {
        assert_eq!(
            KmipAlgorithm::MlDsa65.to_pkcs11_mech(PkcsOp::SignVerify),
            Some(CKM_ML_DSA),
        );
        assert_eq!(CKM_ML_DSA, 0x1d);
    }

    #[test]
    fn ml_kem_encap_decap_share_mech() {
        let encap = KmipAlgorithm::MlKem1024.to_pkcs11_mech(PkcsOp::Encrypt);
        let decap = KmipAlgorithm::MlKem1024.to_pkcs11_mech(PkcsOp::Decrypt);
        assert_eq!(encap, decap);
        assert_eq!(encap, Some(CKM_ML_KEM));
    }

    #[test]
    fn ml_dsa_does_not_support_encrypt() {
        // ML-DSA is a signature algorithm — KMIP Encrypt is undefined.
        assert_eq!(
            KmipAlgorithm::MlDsa65.to_pkcs11_mech(PkcsOp::Encrypt),
            None,
        );
    }

    #[test]
    fn ml_kem_does_not_support_sign() {
        // ML-KEM is a KEM — KMIP Sign is undefined.
        assert_eq!(
            KmipAlgorithm::MlKem768.to_pkcs11_mech(PkcsOp::SignVerify),
            None,
        );
    }

    #[test]
    fn aes_keygen_and_gcm_dispatch_correctly() {
        assert_eq!(KmipAlgorithm::Aes.to_pkcs11_mech(PkcsOp::KeyGen), Some(CKM_AES_KEY_GEN));
        assert_eq!(KmipAlgorithm::Aes.to_pkcs11_mech(PkcsOp::Encrypt), Some(CKM_AES_GCM));
    }

    /// Pins the PQC mech codepoints to the **standard PKCS#11 v3.2** values
    /// from the normative `pkcs11t.h` (mirrored by
    /// `softhsmrustv3::constants` and by `pkcs11-mech-manifest.json`'s
    /// `standard_pkcs11_v3_2` block). The former CKM_PQCTODAY_* vendor
    /// block (0x4032–0x4037) was retired by K5 — those values are the
    /// OASIS-assigned CKM_HSS/CKM_XMSS* codepoints and must never be
    /// emitted by this layer.
    #[test]
    fn manifest_consistency_test() {
        assert_eq!(CKM_ML_KEM_KEY_PAIR_GEN,  0x0f);
        assert_eq!(CKM_ML_KEM,               0x17);
        assert_eq!(CKM_ML_DSA_KEY_PAIR_GEN,  0x1c);
        assert_eq!(CKM_ML_DSA,               0x1d);
        assert_eq!(CKM_SLH_DSA_KEY_PAIR_GEN, 0x2d);
        assert_eq!(CKM_SLH_DSA,              0x2e);
    }

    /// K5 regression — every PQC family's `(op) → mech` selection emits the
    /// standard PKCS#11 v3.2 codepoint, never the retired CKM_PQCTODAY_*
    /// pseudo-vendor block K5 removed. HSS (wired later, Phase 1.5) is a
    /// deliberate, explicitly-asserted exception: 0x4032/0x4033 are its
    /// own real standard codepoints, not the retired ones — see the
    /// assertion below for why the numbers are identical either way.
    #[test]
    fn pqc_mech_selection_emits_standard_codepoints() {
        use KmipAlgorithm::*;
        use PkcsOp::*;

        // ML-KEM: keygen + encapsulate (Encrypt/Decrypt).
        for a in [MlKem512, MlKem768, MlKem1024] {
            assert_eq!(a.to_pkcs11_mech(KeyGen), Some(0x0f), "{}", a.spec_name());
            assert_eq!(a.to_pkcs11_mech(Encrypt), Some(0x17), "{}", a.spec_name());
            assert_eq!(a.to_pkcs11_mech(Decrypt), Some(0x17), "{}", a.spec_name());
        }

        // ML-DSA: keygen + sign/verify.
        for a in [MlDsa44, MlDsa65, MlDsa87] {
            assert_eq!(a.to_pkcs11_mech(KeyGen), Some(0x1c), "{}", a.spec_name());
            assert_eq!(a.to_pkcs11_mech(SignVerify), Some(0x1d), "{}", a.spec_name());
        }

        // SLH-DSA (all 12 parameter sets): keygen + sign/verify. Keygen was
        // mislabeled as the HSS codepoint pre-K5 (compliance-audit B-1).
        for a in [
            SlhDsaSha2_128s, SlhDsaSha2_128f, SlhDsaSha2_192s, SlhDsaSha2_192f,
            SlhDsaSha2_256s, SlhDsaSha2_256f, SlhDsaShake128s, SlhDsaShake128f,
            SlhDsaShake192s, SlhDsaShake192f, SlhDsaShake256s, SlhDsaShake256f,
        ] {
            assert_eq!(a.to_pkcs11_mech(KeyGen), Some(0x2d), "{}", a.spec_name());
            assert_eq!(a.to_pkcs11_mech(SignVerify), Some(0x2e), "{}", a.spec_name());
        }

        // HSS (Phase 1.5, post-dates K5): 0x4032/0x4033 are its REAL,
        // OASIS-assigned standard codepoints (verified directly against
        // `src/lib/pkcs11/pkcs11t.h`) — not the retired CKM_PQCTODAY_*
        // pseudo-vendor block K5 removed. The numeric range is identical
        // by construction (retiring the fake vendor scheme meant handing
        // these exact numbers to the real mechanisms), which is why the
        // blanket "nothing in 0x4032-0x4037" check below carves this
        // pair out explicitly rather than asserting it can never appear.
        assert_eq!(Hss.to_pkcs11_mech(KeyGen), Some(0x4032), "{}", Hss.spec_name());
        assert_eq!(Hss.to_pkcs11_mech(SignVerify), Some(0x4033), "{}", Hss.spec_name());

        // No OTHER (algorithm, op) pair may emit a retired pseudo-vendor
        // codepoint — HSS is the sole, explicitly-checked-above exception.
        for &a in all_algos() {
            if a == Hss {
                continue;
            }
            for op in [KeyGen, SignVerify, Encrypt, Decrypt, Mac] {
                if let Some(m) = a.to_pkcs11_mech(op) {
                    assert!(
                        !(0x4032..=0x4037).contains(&m),
                        "{} {:?} emits retired pseudo-vendor mech 0x{m:04X}",
                        a.spec_name(),
                        op,
                    );
                }
            }
        }
    }
}
