//! KMIP 3.0 algorithm registry — the [`KmipAlgorithm`] enum and its mappings
//! to/from wire-format codepoints and PKCS#11 mechanism IDs.
//!
//! Wire codepoints are the OASIS KMIP 3.0 `CryptographicAlgorithm`
//! enumeration values (see
//! `spec/oasis-kmip-3.0/kmip-spec-3.0-tags-enums.json`, regenerated by
//! `tools/extract_kmip_spec.rs` from the OASIS HTML).
//!
//! Per the 2026-06-07 workflow decision, **v0.1 ships FIPS-certified algorithms
//! only** (ML-KEM / ML-DSA / SLH-DSA / classical RSA-ECDSA-AES-HMAC). NIST
//! Round-3-alt and Round-4 candidates (Falcon, HQC, BIKE, FrodoKEM, Classic
//! McEliece, XMSS) are parked indefinitely — they have reserved codepoints
//! in `pkcs11-mech-manifest.json` but are not exposed here.
//!
//! ## Mech selection by operation
//!
//! KMIP wire only carries `CryptographicAlgorithm = ML-DSA-65`. The mech
//! the PKCS#11 bridge calls depends on which OPERATION is being requested:
//!
//! - `Create` (key generation) → `CKM_PQCTODAY_ML_DSA_KEY_PAIR_GEN` (`0x4035`)
//! - `Sign` / `SignatureVerify` → `CKM_PQCTODAY_ML_DSA_SIGN_VERIFY` (`0x4036`)
//! - `Encrypt` (ML-KEM encapsulation) → `CKM_PQCTODAY_ML_KEM_ENCAPSULATE` (`0x4037`)
//!
//! That's why [`KmipAlgorithm::to_pkcs11_mech`] takes a [`PkcsOp`] argument —
//! the mapping is `(algorithm, op) → mech`, not just `algorithm → mech`.

/// PKCS#11 mechanism ID (CK_MECHANISM_TYPE on the wire). Conceptually a
/// `CK_ULONG`; we model it as `u32` because every codepoint we ship fits.
pub type CkMechanismType = u32;

// ── Vendor mech codepoints (pqctoday-hsm/softhsmv3, v0.5.0 shipping set) ────
// Authoritative source: pkcs11-mech-manifest.json
// (sha256 of pqctoday-priv/docs/platform/data/pkcs11-vendor-mech-allocation.md
//  is checked in `manifest_consistency_test` below).

pub const CKM_PQCTODAY_HSS_KEY_PAIR_GEN: CkMechanismType    = 0x4032;
pub const CKM_PQCTODAY_SLH_DSA_SIGN_VERIFY: CkMechanismType = 0x4033;
pub const CKM_PQCTODAY_ML_KEM_KEY_PAIR_GEN: CkMechanismType = 0x4034;
pub const CKM_PQCTODAY_ML_DSA_KEY_PAIR_GEN: CkMechanismType = 0x4035;
pub const CKM_PQCTODAY_ML_DSA_SIGN_VERIFY: CkMechanismType  = 0x4036;
pub const CKM_PQCTODAY_ML_KEM_ENCAPSULATE: CkMechanismType  = 0x4037;

// ── Standard PKCS#11 v3.2 mech codepoints used by classical algos ──────────
// From src/lib/pkcs11/pkcs11t.h (in pqctoday-hsm root). These do NOT live in
// the vendor manifest — they are part of the OASIS PKCS#11 v3.2 normative
// surface.

pub const CKM_RSA_PKCS_KEY_PAIR_GEN: CkMechanismType = 0x0000;
pub const CKM_RSA_PKCS: CkMechanismType              = 0x0001;
pub const CKM_RSA_PKCS_OAEP: CkMechanismType         = 0x0009;
pub const CKM_RSA_PKCS_PSS: CkMechanismType          = 0x000D;

pub const CKM_EC_KEY_PAIR_GEN: CkMechanismType = 0x1040;
pub const CKM_ECDSA: CkMechanismType           = 0x1041;
pub const CKM_ECDSA_SHA256: CkMechanismType    = 0x1044;

pub const CKM_AES_KEY_GEN: CkMechanismType = 0x1080;
pub const CKM_AES_GCM: CkMechanismType     = 0x1087;

/// PKCS#11 v3.2 §6.20 — IETF ChaCha20 stream cipher. Codepoint
/// `0x1071`. Distinct from `CKM_CHACHA20_POLY1305` so the bridge
/// picks the right primitive (the actual cipher implementation lives
/// in `softhsmrustv3::crypto`).
pub const CKM_CHACHA20: CkMechanismType         = 0x1071;
/// PKCS#11 v3.2 §6.20 — IETF ChaCha20-Poly1305 AEAD (RFC 8439).
pub const CKM_CHACHA20_POLY1305: CkMechanismType = 0x1093;

pub const CKM_GENERIC_SECRET_KEY_GEN: CkMechanismType = 0x0350;
pub const CKM_SHA256_HMAC: CkMechanismType            = 0x0251;
pub const CKM_SHA384_HMAC: CkMechanismType            = 0x0261;
pub const CKM_SHA512_HMAC: CkMechanismType            = 0x0271;

/// PKCS#11 operation that the bridge is about to perform — disambiguates the
/// `(KmipAlgorithm, op) → mech` mapping. KMIP wire format carries the
/// algorithm; the operation is determined by the KMIP op handler that owns
/// the request.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PkcsOp {
    /// Key pair generation (for asymmetric algos) or symmetric key gen.
    KeyGen,
    /// Sign / SignatureVerify.
    SignVerify,
    /// KMIP Encrypt — for ML-KEM this is encapsulation; for AES/RSA it's
    /// classical encryption.
    Encrypt,
    /// KMIP Decrypt — symmetric to Encrypt; for ML-KEM this is decapsulation.
    Decrypt,
    /// MAC generation / verification.
    Mac,
}

/// KMIP 3.0 `CryptographicAlgorithm` enum value — the subset we expose in v0.1.
///
/// Wire-format `Enumeration` codepoint comes from OASIS KMIP 3.0 §10.2.6,
/// extracted into `spec/oasis-kmip-3.0/kmip-spec-3.0-tags-enums.json`.
/// Symbolic names follow the OASIS spec's hyphenation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum KmipAlgorithm {
    // ── Classical baseline ────────────────────────────────────────────────
    Aes,           // 0x03
    Rsa,           // 0x04
    Ecdsa,         // 0x06 — covers ECDSA over any curve; curve = attribute
    HmacSha256,    // 0x09
    HmacSha384,    // 0x0a
    HmacSha512,    // 0x0b
    Ecdh,          // 0x0e
    /// IETF ChaCha20 stream cipher (RFC 8439) — KMIP 3.0 §11
    /// `Cryptographic Algorithm` codepoint `0x1c`.
    ChaCha20,
    /// IETF ChaCha20-Poly1305 AEAD (RFC 8439) — codepoint `0x1e`.
    /// Distinct from `ChaCha20` so the shim picks the right primitive
    /// (separate auth-tag emit path) without needing a `BlockCipherMode`
    /// hint.
    ChaCha20Poly1305,

    // ── FIPS PQC — ML-KEM (FIPS 203) ──────────────────────────────────────
    MlKem512,      // 0x39
    MlKem768,      // 0x3a
    MlKem1024,     // 0x3b

    // ── FIPS PQC — ML-DSA (FIPS 204) ──────────────────────────────────────
    MlDsa44,       // 0x3c
    MlDsa65,       // 0x3d
    MlDsa87,       // 0x3e

    // ── FIPS PQC — SLH-DSA (FIPS 205) ─────────────────────────────────────
    SlhDsaSha2_128s,  // 0x3f
    SlhDsaSha2_128f,  // 0x40
    SlhDsaSha2_192s,  // 0x41
    SlhDsaSha2_192f,  // 0x42
    SlhDsaSha2_256s,  // 0x43
    SlhDsaSha2_256f,  // 0x44
    SlhDsaShake128s,  // 0x45
    SlhDsaShake128f,  // 0x46
    SlhDsaShake192s,  // 0x47
    SlhDsaShake192f,  // 0x48
    SlhDsaShake256s,  // 0x49
    SlhDsaShake256f,  // 0x4a
}

impl KmipAlgorithm {
    /// Wire-format `CryptographicAlgorithm` enumeration value (OASIS KMIP 3.0
    /// §10.2.6). The wire encoding is `Enumeration` (item type `0x05`) with
    /// this `u32` as the value.
    pub const fn to_wire_value(self) -> u32 {
        use KmipAlgorithm::*;
        match self {
            Aes        => 0x00000003,
            Rsa        => 0x00000004,
            Ecdsa      => 0x00000006,
            HmacSha256 => 0x00000009,
            HmacSha384 => 0x0000000a,
            HmacSha512 => 0x0000000b,
            Ecdh       => 0x0000000e,
            ChaCha20         => 0x0000001c,
            ChaCha20Poly1305 => 0x0000001e,
            MlKem512   => 0x00000039,
            MlKem768   => 0x0000003a,
            MlKem1024  => 0x0000003b,
            MlDsa44    => 0x0000003c,
            MlDsa65    => 0x0000003d,
            MlDsa87    => 0x0000003e,
            SlhDsaSha2_128s  => 0x0000003f,
            SlhDsaSha2_128f  => 0x00000040,
            SlhDsaSha2_192s  => 0x00000041,
            SlhDsaSha2_192f  => 0x00000042,
            SlhDsaSha2_256s  => 0x00000043,
            SlhDsaSha2_256f  => 0x00000044,
            SlhDsaShake128s  => 0x00000045,
            SlhDsaShake128f  => 0x00000046,
            SlhDsaShake192s  => 0x00000047,
            SlhDsaShake192f  => 0x00000048,
            SlhDsaShake256s  => 0x00000049,
            SlhDsaShake256f  => 0x0000004a,
        }
    }

    /// Reverse of [`Self::to_wire_value`]. Returns `None` for values outside
    /// the FIPS-certified set this v0.1 supports.
    pub const fn from_wire_value(v: u32) -> Option<Self> {
        use KmipAlgorithm::*;
        Some(match v {
            0x00000003 => Aes,
            0x00000004 => Rsa,
            0x00000006 => Ecdsa,
            0x00000009 => HmacSha256,
            0x0000000a => HmacSha384,
            0x0000000b => HmacSha512,
            0x0000000e => Ecdh,
            0x0000001c => ChaCha20,
            0x0000001e => ChaCha20Poly1305,
            0x00000039 => MlKem512,
            0x0000003a => MlKem768,
            0x0000003b => MlKem1024,
            0x0000003c => MlDsa44,
            0x0000003d => MlDsa65,
            0x0000003e => MlDsa87,
            0x0000003f => SlhDsaSha2_128s,
            0x00000040 => SlhDsaSha2_128f,
            0x00000041 => SlhDsaSha2_192s,
            0x00000042 => SlhDsaSha2_192f,
            0x00000043 => SlhDsaSha2_256s,
            0x00000044 => SlhDsaSha2_256f,
            0x00000045 => SlhDsaShake128s,
            0x00000046 => SlhDsaShake128f,
            0x00000047 => SlhDsaShake192s,
            0x00000048 => SlhDsaShake192f,
            0x00000049 => SlhDsaShake256s,
            0x0000004a => SlhDsaShake256f,
            _ => return None,
        })
    }

    /// `true` if this algorithm is one of the NIST FIPS PQC standards
    /// (FIPS 203 ML-KEM, FIPS 204 ML-DSA, FIPS 205 SLH-DSA).
    pub const fn is_pqc(self) -> bool {
        use KmipAlgorithm::*;
        matches!(
            self,
            MlKem512 | MlKem768 | MlKem1024
                | MlDsa44 | MlDsa65 | MlDsa87
                | SlhDsaSha2_128s | SlhDsaSha2_128f
                | SlhDsaSha2_192s | SlhDsaSha2_192f
                | SlhDsaSha2_256s | SlhDsaSha2_256f
                | SlhDsaShake128s | SlhDsaShake128f
                | SlhDsaShake192s | SlhDsaShake192f
                | SlhDsaShake256s | SlhDsaShake256f
        )
    }

    /// PKCS#11 mech to call for `(self, op)`. Returns `None` if the operation
    /// is not defined for this algorithm (e.g. `KeyGen` for HMAC, `SignVerify`
    /// for ML-KEM).
    ///
    /// The mapping is verified against [`pkcs11-mech-manifest.json`] for the
    /// vendor codepoints in the manifest-consistency test below.
    ///
    /// [`pkcs11-mech-manifest.json`]: ../../pkcs11-mech-manifest.json
    pub const fn to_pkcs11_mech(self, op: PkcsOp) -> Option<CkMechanismType> {
        use KmipAlgorithm::*;
        use PkcsOp::*;
        match (self, op) {
            // ── ML-KEM (FIPS 203) ─────────────────────────────────────────
            (MlKem512 | MlKem768 | MlKem1024, KeyGen) =>
                Some(CKM_PQCTODAY_ML_KEM_KEY_PAIR_GEN),
            (MlKem512 | MlKem768 | MlKem1024, Encrypt | Decrypt) =>
                Some(CKM_PQCTODAY_ML_KEM_ENCAPSULATE),

            // ── ML-DSA (FIPS 204) ─────────────────────────────────────────
            (MlDsa44 | MlDsa65 | MlDsa87, KeyGen) =>
                Some(CKM_PQCTODAY_ML_DSA_KEY_PAIR_GEN),
            (MlDsa44 | MlDsa65 | MlDsa87, SignVerify) =>
                Some(CKM_PQCTODAY_ML_DSA_SIGN_VERIFY),

            // ── SLH-DSA (FIPS 205) ────────────────────────────────────────
            // Keygen is via the HSS keygen vendor codepoint per softhsmv3
            // shipping mech table (PKCS#11 v3.2 §6.14); SLH-DSA-specific
            // keygen would require an additional vendor mech codepoint
            // (0x4038+) which is not in the v0.5.0 shipping set.
            (SlhDsaSha2_128s | SlhDsaSha2_128f
                | SlhDsaSha2_192s | SlhDsaSha2_192f
                | SlhDsaSha2_256s | SlhDsaSha2_256f
                | SlhDsaShake128s | SlhDsaShake128f
                | SlhDsaShake192s | SlhDsaShake192f
                | SlhDsaShake256s | SlhDsaShake256f, KeyGen)
                => Some(CKM_PQCTODAY_HSS_KEY_PAIR_GEN),
            (SlhDsaSha2_128s | SlhDsaSha2_128f
                | SlhDsaSha2_192s | SlhDsaSha2_192f
                | SlhDsaSha2_256s | SlhDsaSha2_256f
                | SlhDsaShake128s | SlhDsaShake128f
                | SlhDsaShake192s | SlhDsaShake192f
                | SlhDsaShake256s | SlhDsaShake256f, SignVerify)
                => Some(CKM_PQCTODAY_SLH_DSA_SIGN_VERIFY),

            // ── RSA classical ─────────────────────────────────────────────
            (Rsa, KeyGen)     => Some(CKM_RSA_PKCS_KEY_PAIR_GEN),
            (Rsa, SignVerify) => Some(CKM_RSA_PKCS_PSS),
            (Rsa, Encrypt | Decrypt) => Some(CKM_RSA_PKCS_OAEP),

            // ── ECDSA / ECDH classical ────────────────────────────────────
            (Ecdsa, KeyGen) | (Ecdh, KeyGen) => Some(CKM_EC_KEY_PAIR_GEN),
            (Ecdsa, SignVerify) => Some(CKM_ECDSA),

            // ── AES symmetric ─────────────────────────────────────────────
            (Aes, KeyGen) => Some(CKM_AES_KEY_GEN),
            (Aes, Encrypt | Decrypt) => Some(CKM_AES_GCM),

            // ── ChaCha20 family ───────────────────────────────────────────
            // KMIP carries ChaCha20 (stream) and ChaCha20-Poly1305 (AEAD)
            // as distinct algorithms — see KMIP 3.0 §11 codepoints
            // `0x1c` / `0x1e`. Encrypt/Decrypt routes straight to the
            // softhsmv3 PKCS#11 mechanism; the underlying cipher lives
            // entirely inside that crate.
            (ChaCha20, Encrypt | Decrypt) => Some(CKM_CHACHA20),
            (ChaCha20Poly1305, Encrypt | Decrypt) => Some(CKM_CHACHA20_POLY1305),

            // ── HMAC families ─────────────────────────────────────────────
            (HmacSha256 | HmacSha384 | HmacSha512, KeyGen) =>
                Some(CKM_GENERIC_SECRET_KEY_GEN),
            (HmacSha256, Mac) => Some(CKM_SHA256_HMAC),
            (HmacSha384, Mac) => Some(CKM_SHA384_HMAC),
            (HmacSha512, Mac) => Some(CKM_SHA512_HMAC),

            // Any other (algorithm, op) pair is undefined.
            _ => None,
        }
    }

    /// Spec-text symbolic name (matches OASIS spelling). Useful for logging
    /// and error messages.
    pub const fn spec_name(self) -> &'static str {
        use KmipAlgorithm::*;
        match self {
            Aes        => "AES",
            Rsa        => "RSA",
            Ecdsa      => "ECDSA",
            HmacSha256 => "HMAC-SHA256",
            HmacSha384 => "HMAC-SHA384",
            HmacSha512 => "HMAC-SHA512",
            Ecdh       => "ECDH",
            ChaCha20         => "ChaCha20",
            ChaCha20Poly1305 => "ChaCha20-Poly1305",
            MlKem512   => "ML-KEM-512",
            MlKem768   => "ML-KEM-768",
            MlKem1024  => "ML-KEM-1024",
            MlDsa44    => "ML-DSA-44",
            MlDsa65    => "ML-DSA-65",
            MlDsa87    => "ML-DSA-87",
            SlhDsaSha2_128s  => "SLH-DSA-SHA2-128s",
            SlhDsaSha2_128f  => "SLH-DSA-SHA2-128f",
            SlhDsaSha2_192s  => "SLH-DSA-SHA2-192s",
            SlhDsaSha2_192f  => "SLH-DSA-SHA2-192f",
            SlhDsaSha2_256s  => "SLH-DSA-SHA2-256s",
            SlhDsaSha2_256f  => "SLH-DSA-SHA2-256f",
            SlhDsaShake128s  => "SLH-DSA-SHAKE-128s",
            SlhDsaShake128f  => "SLH-DSA-SHAKE-128f",
            SlhDsaShake192s  => "SLH-DSA-SHAKE-192s",
            SlhDsaShake192f  => "SLH-DSA-SHAKE-192f",
            SlhDsaShake256s  => "SLH-DSA-SHAKE-256s",
            SlhDsaShake256f  => "SLH-DSA-SHAKE-256f",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every variant of `KmipAlgorithm`; centralising the enumeration so each
    /// test below exhausts the whole set without repeating itself.
    fn all_algos() -> &'static [KmipAlgorithm] {
        use KmipAlgorithm::*;
        &[
            Aes, Rsa, Ecdsa, HmacSha256, HmacSha384, HmacSha512, Ecdh,
            MlKem512, MlKem768, MlKem1024,
            MlDsa44, MlDsa65, MlDsa87,
            SlhDsaSha2_128s, SlhDsaSha2_128f,
            SlhDsaSha2_192s, SlhDsaSha2_192f,
            SlhDsaSha2_256s, SlhDsaSha2_256f,
            SlhDsaShake128s, SlhDsaShake128f,
            SlhDsaShake192s, SlhDsaShake192f,
            SlhDsaShake256s, SlhDsaShake256f,
        ]
    }

    #[test]
    fn wire_value_round_trips_for_every_variant() {
        for &a in all_algos() {
            let v = a.to_wire_value();
            assert_eq!(KmipAlgorithm::from_wire_value(v), Some(a), "{}", a.spec_name());
        }
    }

    #[test]
    fn unknown_wire_value_is_none() {
        // 0x4b is one past the last FIPS PQC entry we ship.
        assert_eq!(KmipAlgorithm::from_wire_value(0x0000004b), None);
        // Falcon would be at 0x4b+ if added; parked indefinitely per
        // workflow decision §4.
        assert_eq!(KmipAlgorithm::from_wire_value(0x00000100), None);
    }

    #[test]
    fn pqc_classifier_matches_fips_set() {
        for &a in all_algos() {
            let expected = matches!(
                a.spec_name(),
                s if s.starts_with("ML-KEM-") || s.starts_with("ML-DSA-") || s.starts_with("SLH-DSA-")
            );
            assert_eq!(a.is_pqc(), expected, "{}", a.spec_name());
        }
    }

    #[test]
    fn ml_kem_768_keygen_dispatches_to_vendor_mech() {
        assert_eq!(
            KmipAlgorithm::MlKem768.to_pkcs11_mech(PkcsOp::KeyGen),
            Some(CKM_PQCTODAY_ML_KEM_KEY_PAIR_GEN),
        );
        assert_eq!(CKM_PQCTODAY_ML_KEM_KEY_PAIR_GEN, 0x4034);
    }

    #[test]
    fn ml_dsa_65_sign_verify_dispatches_to_vendor_mech() {
        assert_eq!(
            KmipAlgorithm::MlDsa65.to_pkcs11_mech(PkcsOp::SignVerify),
            Some(CKM_PQCTODAY_ML_DSA_SIGN_VERIFY),
        );
        assert_eq!(CKM_PQCTODAY_ML_DSA_SIGN_VERIFY, 0x4036);
    }

    #[test]
    fn ml_kem_encap_decap_share_mech() {
        let encap = KmipAlgorithm::MlKem1024.to_pkcs11_mech(PkcsOp::Encrypt);
        let decap = KmipAlgorithm::MlKem1024.to_pkcs11_mech(PkcsOp::Decrypt);
        assert_eq!(encap, decap);
        assert_eq!(encap, Some(CKM_PQCTODAY_ML_KEM_ENCAPSULATE));
    }

    #[test]
    fn ml_dsa_does_not_support_encrypt() {
        // ML-DSA is a signature algorithm — KMIP Encrypt is undefined.
        assert_eq!(
            KmipAlgorithm::MlDsa65.to_pkcs11_mech(PkcsOp::Encrypt),
            None,
        );
    }

    #[test]
    fn ml_kem_does_not_support_sign() {
        // ML-KEM is a KEM — KMIP Sign is undefined.
        assert_eq!(
            KmipAlgorithm::MlKem768.to_pkcs11_mech(PkcsOp::SignVerify),
            None,
        );
    }

    #[test]
    fn aes_keygen_and_gcm_dispatch_correctly() {
        assert_eq!(KmipAlgorithm::Aes.to_pkcs11_mech(PkcsOp::KeyGen), Some(CKM_AES_KEY_GEN));
        assert_eq!(KmipAlgorithm::Aes.to_pkcs11_mech(PkcsOp::Encrypt), Some(CKM_AES_GCM));
    }

    /// Pins the vendor mech codepoints to the values in
    /// [`pkcs11-mech-manifest.json`]. If the manifest moves a codepoint, this
    /// test fails loudly so the consumer table here can be updated in lockstep.
    ///
    /// [`pkcs11-mech-manifest.json`]: ../../pkcs11-mech-manifest.json
    #[test]
    fn manifest_consistency_test() {
        // Hard-coded against the active vendor codepoints in
        // pkcs11-mech-manifest.json `active.*` block. Authority sha256 of
        // pkcs11-vendor-mech-allocation.md is checked by the manifest's own
        // CI gate (`consumer_contract.ci_gate`); here we check the consumer
        // side of the contract.
        assert_eq!(CKM_PQCTODAY_HSS_KEY_PAIR_GEN,    0x4032);
        assert_eq!(CKM_PQCTODAY_SLH_DSA_SIGN_VERIFY, 0x4033);
        assert_eq!(CKM_PQCTODAY_ML_KEM_KEY_PAIR_GEN, 0x4034);
        assert_eq!(CKM_PQCTODAY_ML_DSA_KEY_PAIR_GEN, 0x4035);
        assert_eq!(CKM_PQCTODAY_ML_DSA_SIGN_VERIFY,  0x4036);
        assert_eq!(CKM_PQCTODAY_ML_KEM_ENCAPSULATE,  0x4037);
    }
}
