//! gRPC bindings + service impl for the IETF `mls_client.MLSClient`
//! contract — see `bin/pqctoday-mls-grpc` for the runnable server.
//!
//! ## Implemented RPCs (v0.2.1)
//!
//! 22 RPCs fully implemented:
//! `Name`, `SupportedCiphersuites`, `CreateGroup`, `JoinGroup`,
//! `CreateKeyPackage`, `AddProposal`, `Commit`, `HandleCommit`,
//! `HandlePendingCommit`, `StateAuth`, `Protect`, `Unprotect`,
//! `UpdateProposal`, `RemoveProposal`, `Export`, `GroupInfo`,
//! `ExternalJoin`, `StorePSK`, `ExternalPSKProposal`,
//! `ResumptionPSKProposal`, `GroupContextExtensionsProposal`, `Free`.
//!
//! 12 RPCs remain stubbed (`Status::unimplemented`) matching
//! `openmls/interop_client`'s own `todo!()`s: the ReInit, Branch,
//! NewMemberAdd, and ExternalSigner families.
//!
//! Each gRPC call that creates state spawns a sibling `PqcTodayProvider`
//! against the shared softhsm context. Every credential signing key
//! generated by these handlers lives in the HSM as a token object with
//! `CKA_SENSITIVE=TRUE` / `CKA_EXTRACTABLE=FALSE`; what crosses the gRPC
//! wire as `signature_priv` in the protobuf is our opaque `HsmKeyHandle`
//! blob, not raw key bytes.

use std::collections::HashMap;
use std::io::Write;
use std::path::PathBuf;
use std::sync::Mutex;

use cryptoki::context::{CInitializeArgs, Pkcs11};
use cryptoki::session::UserType;
use cryptoki::types::AuthPin;

use openmls::group::{
    GroupId, MlsGroup, MlsGroupCreateConfig, MlsGroupJoinConfig, StagedWelcome, WireFormatPolicy,
    PURE_CIPHERTEXT_WIRE_FORMAT_POLICY, PURE_PLAINTEXT_WIRE_FORMAT_POLICY,
};
use openmls::key_packages::{KeyPackage, KeyPackageBundle};
use openmls::prelude::tls_codec::{Deserialize as _, Serialize as _};
use openmls::prelude::{
    ApplicationIdExtension, BasicCredential, Capabilities, Credential, CredentialType,
    CredentialWithKey, Extension, ExtensionType, Extensions, ExternalPubExtension,
    ExternalSendersExtension, GroupContext, GroupEpoch, LeafNodeParameters, MlsMessageBodyIn,
    MlsMessageIn, MlsMessageOut, ProcessedMessageContent, ProtocolVersion, RatchetTreeExtension,
    RatchetTreeIn, RequiredCapabilitiesExtension, SenderRatchetConfiguration, UnknownExtension,
};
use openmls::schedule::{psk::ResumptionPskUsage, ExternalPsk, PreSharedKeyId, Psk};
use openmls_pqctoday_crypto::{HsmConfig, PqcTodayHsmSigner, PqcTodayProvider};
use openmls_traits::random::OpenMlsRand;
use openmls_traits::types::Ciphersuite;
use openmls_traits::OpenMlsProvider;
use tonic::{Code, Request, Response, Status};

pub mod mls_client {
    tonic::include_proto!("mls_client");
}

use mls_client::mls_client_server::MlsClient;
use mls_client::*;

pub const IMPLEMENTATION_NAME: &str = "pqctoday-mls";
pub const SUPPORTED_CIPHERSUITES: &[u32] = &[1, 2];

// Per RFC 9420 §13.1: the default extension types
// (ApplicationId, RatchetTree, RequiredCapabilities, ExternalPub,
// ExternalSenders, all <= 0x0005) MUST NOT be advertised in a leaf
// node's `capabilities.extensions` — they're implicitly supported.
// We list only NON-default extension types here. `mls-rs`'s
// leaf-node validator returns `MlsError::DefaultValueListed`
// if a default type appears; openmls's reference example happens
// to list them, hitting that quirk in cross-impl interop.
const EXTENSION_TYPES: [ExtensionType; 0] = [];
const CREDENTIAL_TYPES: [CredentialType; 1] = [CredentialType::Basic];

// ── Per-group state ──────────────────────────────────────────────────────────

/// One MLS group plus the HSM-backed signer + provider it uses.
pub struct InteropGroup {
    pub group: MlsGroup,
    pub signer: PqcTodayHsmSigner,
    pub provider: PqcTodayProvider,
    pub wire_format_policy: WireFormatPolicy,
    /// Track our own outbound messages so we can skip processing them when
    /// they come back to us in `Commit.by_reference` / `HandleCommit.proposal`.
    pub messages_out: Vec<MlsMessageIn>,
}

/// Cached state from `CreateKeyPackage`, consumed by a later `JoinGroup`
/// or `AddProposal`.
pub struct PendingKeyPackage {
    pub bundle: KeyPackageBundle,
    pub credential: Credential,
    pub signer: PqcTodayHsmSigner,
    pub provider: PqcTodayProvider,
}

// ── Server lifetime: one softhsm token + base provider ───────────────────────

/// Keeps the tmpdir + softhsm conf alive for the server's lifetime so the
/// per-call sibling providers all stay valid.
struct TokenEnv {
    _tokens_dir: tempfile::TempDir,
    _conf_file: tempfile::NamedTempFile,
}

pub struct PqcTodayInteropClient {
    _token_env: TokenEnv,
    base_provider: PqcTodayProvider,
    groups: Mutex<Vec<InteropGroup>>,
    // pending is keyed by transaction_id (u32 from CreateKeyPackage) — the correct
    // IETF correlation key. Keying by identity breaks for configs like external_join
    // which run many scenarios with the same actor identity concurrently.
    pending: Mutex<HashMap<u32, PendingKeyPackage>>,
    // identity_map: reverse lookup so StorePSK (which receives transaction_id) can
    // find the identity for cross-scenario helper code.
    transaction_id_map: Mutex<HashMap<u32, Vec<u8>>>,
}

impl PqcTodayInteropClient {
    /// Build the server. Resolves the PKCS#11 module from `$PKCS11_MODULE`
    /// or the repo-local CMake build, initialises a fresh per-process
    /// softhsm token in a tmpdir, opens the base provider session.
    pub fn new() -> Result<Self, Box<dyn std::error::Error>> {
        let module = resolve_module()
            .ok_or("no PKCS#11 module found — set $PKCS11_MODULE or build softhsmv3")?;
        let (token_env, base_provider) = setup_softhsm(&module)?;
        Ok(Self {
            _token_env: token_env,
            base_provider,
            groups: Mutex::new(Vec::new()),
            pending: Mutex::new(HashMap::new()),
            transaction_id_map: Mutex::new(HashMap::new()),
        })
    }

    /// Spawn a fresh sibling provider on the same PKCS#11 context.
    fn sibling(&self) -> Result<PqcTodayProvider, Status> {
        // PIN=None: the base provider already logged the token in, and PKCS#11
        // login is token-scoped, not session-scoped.
        self.base_provider
            .spawn_sibling(None)
            .map_err(|e| Status::new(Code::Internal, format!("HSM sibling open: {e}")))
    }
}

fn resolve_module() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("PKCS11_MODULE") {
        let pb = PathBuf::from(p);
        if pb.exists() {
            return Some(pb);
        }
    }
    let here = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    for rel in &[
        "../../build/src/lib/libsofthsmv3.dylib",
        "../../build/src/lib/libsofthsmv3.so",
        "../../build_fresh/src/lib/libsofthsmv3.dylib",
        "../../build-pqctoday/src/lib/libsofthsmv3.so",
    ] {
        let p = here.join(rel);
        if p.exists() {
            return Some(p);
        }
    }
    None
}

fn setup_softhsm(
    module: &PathBuf,
) -> Result<(TokenEnv, PqcTodayProvider), Box<dyn std::error::Error>> {
    let so_pin = "12345678";
    let user_pin = "1234";

    let tokens_dir = tempfile::tempdir()?;
    let mut conf_file = tempfile::NamedTempFile::new()?;
    writeln!(
        conf_file,
        "directories.tokendir = {}\nobjectstore.backend = file\nlog.level = ERROR",
        tokens_dir.path().display()
    )?;
    std::env::set_var("SOFTHSM2_CONF", conf_file.path());

    let ctx = Pkcs11::new(module)?;
    ctx.initialize(CInitializeArgs::OsThreads)?;
    let slot = *ctx
        .get_slots_with_token()?
        .first()
        .ok_or("no softhsm slot")?;
    ctx.init_token(slot, &AuthPin::new(so_pin.into()), "pqctoday-interop")?;
    {
        let so = ctx.open_rw_session(slot)?;
        so.login(UserType::So, Some(&AuthPin::new(so_pin.into())))?;
        so.init_pin(&AuthPin::new(user_pin.into()))?;
        so.logout().ok();
    }
    drop(ctx);

    let cfg = HsmConfig::new(module.clone()).with_pin(user_pin);
    let provider = PqcTodayProvider::new(&cfg)?;
    Ok((
        TokenEnv {
            _tokens_dir: tokens_dir,
            _conf_file: conf_file,
        },
        provider,
    ))
}

fn into_status<E: std::fmt::Display>(e: E) -> Status {
    Status::new(Code::Aborted, format!("openmls error: {e}"))
}

fn to_ciphersuite(cs: u32) -> Result<Ciphersuite, Status> {
    Ciphersuite::try_from(cs as u16)
        .map_err(|_| Status::new(Code::InvalidArgument, "ciphersuite not supported"))
}

fn wire_format_policy(encrypt: bool) -> WireFormatPolicy {
    if encrypt {
        PURE_CIPHERTEXT_WIRE_FORMAT_POLICY
    } else {
        PURE_PLAINTEXT_WIRE_FORMAT_POLICY
    }
}

fn ratchet_tree_from_config(bytes: Vec<u8>) -> Option<RatchetTreeIn> {
    if bytes.is_empty() {
        None
    } else {
        RatchetTreeIn::tls_deserialize_exact(bytes.as_slice()).ok()
    }
}

/// Extract + validate a KeyPackage from a TLS-serialised MlsMessage (the
/// form the gRPC wire carries). Replaces the test-utils-gated
/// `into_keypackage()` shortcut with `extract()` + `KeyPackageIn::validate`.
fn parse_key_package(
    bytes: &[u8],
    provider: &PqcTodayProvider,
) -> Result<KeyPackage, Status> {
    let msg = MlsMessageIn::tls_deserialize_exact(bytes)
        .map_err(|_| Status::aborted("failed to deserialise MlsMessage as KeyPackage"))?;
    match msg.extract() {
        MlsMessageBodyIn::KeyPackage(kp_in) => kp_in
            .validate(provider.crypto(), ProtocolVersion::Mls10)
            .map_err(|e| Status::aborted(format!("KeyPackage validate: {e}"))),
        _ => Err(Status::aborted("MlsMessage body was not a KeyPackage")),
    }
}

// ── Service ─────────────────────────────────────────────────────────────────

#[tonic::async_trait]
impl MlsClient for PqcTodayInteropClient {
    async fn name(
        &self,
        _req: Request<NameRequest>,
    ) -> Result<Response<NameResponse>, Status> {
        Ok(Response::new(NameResponse {
            name: IMPLEMENTATION_NAME.to_string(),
        }))
    }

    async fn supported_ciphersuites(
        &self,
        _req: Request<SupportedCiphersuitesRequest>,
    ) -> Result<Response<SupportedCiphersuitesResponse>, Status> {
        Ok(Response::new(SupportedCiphersuitesResponse {
            ciphersuites: SUPPORTED_CIPHERSUITES.to_vec(),
        }))
    }

    // ── CreateGroup ─────────────────────────────────────────────────────────
    async fn create_group(
        &self,
        req: Request<CreateGroupRequest>,
    ) -> Result<Response<CreateGroupResponse>, Status> {
        let r = req.into_inner();
        let ciphersuite = to_ciphersuite(r.cipher_suite)?;
        let provider = self.sibling()?;

        let signer = provider
            .generate_signer(ciphersuite.signature_algorithm())
            .map_err(|e| Status::new(Code::Internal, format!("HSM signer gen: {e:?}")))?;
        let credential = BasicCredential::new(r.identity.clone());
        let cred_with_key = CredentialWithKey {
            credential: credential.into(),
            signature_key: signer.public_key().to_vec().into(),
        };

        let wfp = wire_format_policy(r.encrypt_handshake);
        let create_cfg = MlsGroupCreateConfig::builder()
            .ciphersuite(ciphersuite)
            .max_past_epochs(32)
            .number_of_resumption_psks(32)
            .sender_ratchet_configuration(SenderRatchetConfiguration::default())
            .use_ratchet_tree_extension(true)
            .wire_format_policy(wfp)
            .build();

        let group = MlsGroup::new_with_group_id(
            &provider,
            &signer,
            &create_cfg,
            GroupId::from_slice(&r.group_id),
            cred_with_key,
        )
        .map_err(into_status)?;

        let interop_group = InteropGroup {
            group,
            signer,
            provider,
            wire_format_policy: wfp,
            messages_out: Vec::new(),
        };
        let mut groups = self.groups.lock().unwrap();
        let state_id = groups.len() as u32;
        groups.push(interop_group);

        Ok(Response::new(CreateGroupResponse { state_id }))
    }

    // ── JoinGroup ───────────────────────────────────────────────────────────
    async fn join_group(
        &self,
        req: Request<JoinGroupRequest>,
    ) -> Result<Response<JoinGroupResponse>, Status> {
        let r = req.into_inner();
        let wfp = wire_format_policy(r.encrypt_handshake);
        let join_cfg = MlsGroupJoinConfig::builder()
            .max_past_epochs(32)
            .number_of_resumption_psks(32)
            .sender_ratchet_configuration(SenderRatchetConfiguration::default())
            .use_ratchet_tree_extension(true)
            .wire_format_policy(wfp)
            .build();

        let pending = self
            .pending
            .lock()
            .unwrap()
            .remove(&r.transaction_id)
            .ok_or_else(|| {
                Status::aborted(format!(
                    "no pending KeyPackage for transaction_id {} (identity {:x?})",
                    r.transaction_id, r.identity
                ))
            })?;

        // Write the KeyPackage into the provider's storage so the Welcome
        // path can look it up by hash_ref (matches openmls/interop_client).
        use openmls_traits::storage::StorageProvider as _;
        let kp_ref = pending
            .bundle
            .key_package()
            .hash_ref(pending.provider.crypto())
            .map_err(into_status)?;
        pending
            .provider
            .storage()
            .write_key_package(&kp_ref, &pending.bundle)
            .map_err(into_status)?;

        let welcome_msg = MlsMessageIn::tls_deserialize_exact(r.welcome.as_slice())
            .map_err(|_| Status::aborted("failed to deserialise Welcome MlsMessage"))?;
        let welcome = match welcome_msg.extract() {
            MlsMessageBodyIn::Welcome(w) => w,
            _ => return Err(Status::aborted("MlsMessage body was not a Welcome")),
        };

        let ratchet_tree = ratchet_tree_from_config(r.ratchet_tree.clone());
        let staged =
            StagedWelcome::new_from_welcome(&pending.provider, &join_cfg, welcome, ratchet_tree)
                .map_err(into_status)?;
        let group = staged.into_group(&pending.provider).map_err(into_status)?;

        let epoch_authenticator = group.epoch_authenticator().as_slice().to_vec();
        let interop_group = InteropGroup {
            group,
            signer: pending.signer,
            provider: pending.provider,
            wire_format_policy: wfp,
            messages_out: Vec::new(),
        };
        let mut groups = self.groups.lock().unwrap();
        let state_id = groups.len() as u32;
        groups.push(interop_group);

        // Silence unused-warning on `credential` (it's the BasicCredential we
        // stored alongside the bundle but openmls reconstructs the leaf
        // credential from the Welcome itself).
        let _ = pending.credential;

        Ok(Response::new(JoinGroupResponse {
            state_id,
            epoch_authenticator,
        }))
    }

    // ── CreateKeyPackage ────────────────────────────────────────────────────
    async fn create_key_package(
        &self,
        req: Request<CreateKeyPackageRequest>,
    ) -> Result<Response<CreateKeyPackageResponse>, Status> {
        let r = req.into_inner();
        let ciphersuite = to_ciphersuite(r.cipher_suite)?;
        let provider = self.sibling()?;

        let signer = provider
            .generate_signer(ciphersuite.signature_algorithm())
            .map_err(|e| Status::new(Code::Internal, format!("HSM signer gen: {e:?}")))?;
        let credential = BasicCredential::new(r.identity.clone());
        let cred_with_key = CredentialWithKey {
            credential: credential.clone().into(),
            signature_key: signer.public_key().to_vec().into(),
        };

        // Build a capabilities list that always includes the actual ciphersuite being
        // requested. The test runner uses the union of all clients' cipher suites, so
        // we may receive requests for cipher suites beyond our SupportedCiphersuites
        // advertised set. The leaf node MUST list the group's ciphersuite.
        let mut leaf_ciphersuites = vec![
            Ciphersuite::MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519,
            Ciphersuite::MLS_128_DHKEMP256_AES128GCM_SHA256_P256,
        ];
        if !leaf_ciphersuites.contains(&ciphersuite) {
            leaf_ciphersuites.push(ciphersuite);
        }

        let bundle = KeyPackage::builder()
            .leaf_node_capabilities(Capabilities::new(
                Some(&[ProtocolVersion::Mls10]),
                Some(&leaf_ciphersuites),
                Some(&EXTENSION_TYPES),
                None,
                Some(&CREDENTIAL_TYPES),
            ))
            .build(ciphersuite, &provider, &signer, cred_with_key)
            .map_err(into_status)?;

        let key_package_msg: MlsMessageOut = bundle.key_package().clone().into();
        let key_package_bytes = key_package_msg
            .tls_serialize_detached()
            .map_err(|e| Status::new(Code::Internal, format!("KeyPackage TLS-encode: {e}")))?;

        // For our HSM-backed flow, the protobuf's `signature_priv` field
        // is the opaque HsmKeyHandle blob (versioned, "PQTH" magic), NOT
        // raw key material. The handle is what `signer.sign()` decodes to
        // look up the token object via `C_FindObjects(CKA_ID)`.
        let signature_priv = signer.handle_blob().to_vec();

        let init_priv = bundle
            .init_private_key()
            .tls_serialize_detached()
            .map_err(|e| Status::new(Code::Internal, format!("init_priv TLS-encode: {e}")))?;
        // openmls 0.8.1 gates `encryption_private_key()` behind `test-utils`,
        // which transitively pins `wasm-bindgen-test = "0.3.50"` and
        // conflicts with our `hpke-rs → libcrux → js-sys = 0.3.98` chain.
        // Empty here for now — cross-impl Welcome flow that consumes our
        // KeyPackages won't work until upstream ungates this. Local
        // (self-pairing) flow doesn't need the wire copy because we
        // retain the bundle in `pending` keyed by identity.
        let encryption_priv: Vec<u8> = Vec::new();

        let transaction_id: [u8; 4] = provider
            .rand()
            .random_array()
            .map_err(|e| Status::new(Code::Internal, format!("HSM rand: {e:?}")))?;
        let transaction_id = u32::from_be_bytes(transaction_id);

        self.transaction_id_map
            .lock()
            .unwrap()
            .insert(transaction_id, r.identity.clone());
        self.pending.lock().unwrap().insert(
            transaction_id,
            PendingKeyPackage {
                bundle,
                credential: credential.into(),
                signer,
                provider,
            },
        );

        Ok(Response::new(CreateKeyPackageResponse {
            transaction_id,
            key_package: key_package_bytes,
            encryption_priv,
            init_priv,
            signature_priv,
        }))
    }

    // ── AddProposal ────────────────────────────────────────────────────────
    async fn add_proposal(
        &self,
        req: Request<AddProposalRequest>,
    ) -> Result<Response<ProposalResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;

        let key_package = parse_key_package(&r.key_package, &g.provider)?;

        let join_cfg = MlsGroupJoinConfig::builder()
            .max_past_epochs(32)
            .number_of_resumption_psks(32)
            .sender_ratchet_configuration(SenderRatchetConfiguration::default())
            .use_ratchet_tree_extension(true)
            .wire_format_policy(g.wire_format_policy)
            .build();
        g.group
            .set_configuration(g.provider.storage(), &join_cfg)
            .map_err(|e| Status::internal(format!("set_configuration: {e}")))?;

        let (proposal_msg, _proposal_ref) = g
            .group
            .propose_add_member(&g.provider, &g.signer, &key_package)
            .map_err(into_status)?;

        // Track our own proposal so Commit / HandleCommit skip it.
        let proposal_in: MlsMessageIn = MlsMessageIn::tls_deserialize_exact(
            proposal_msg
                .tls_serialize_detached()
                .map_err(|e| Status::internal(format!("serialise proposal: {e}")))?
                .as_slice(),
        )
        .map_err(|e| Status::internal(format!("round-trip proposal: {e}")))?;
        g.messages_out.push(proposal_in);

        let proposal_bytes = proposal_msg
            .tls_serialize_detached()
            .map_err(|e| Status::internal(format!("serialise proposal: {e}")))?;
        Ok(Response::new(ProposalResponse {
            proposal: proposal_bytes,
        }))
    }

    // ── Commit ──────────────────────────────────────────────────────────────
    //
    // Handles both `by_reference` (wire-encoded proposals from peers) and
    // `by_value` (inline proposal descriptions emitted directly into the
    // commit). `groupContextExtensions` and `reinit` proposal types are
    // not yet supported (return UNIMPLEMENTED).
    async fn commit(
        &self,
        req: Request<CommitRequest>,
    ) -> Result<Response<CommitResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;

        // ── by_reference: standalone proposals from peers ───────────────────
        for proposal_bytes in &r.by_reference {
            let msg = MlsMessageIn::tls_deserialize_exact(proposal_bytes.as_slice())
                .map_err(|_| Status::aborted("failed to deserialise proposal"))?;
            if g.messages_out.contains(&msg) {
                continue; // our own proposal coming back
            }
            let processed = g
                .group
                .process_message(
                    &g.provider,
                    msg.try_into_protocol_message()
                        .map_err(|_| Status::aborted("proposal not a ProtocolMessage"))?,
                )
                .map_err(into_status)?;
            match processed.into_content() {
                ProcessedMessageContent::ProposalMessage(p) => {
                    g.group
                        .store_pending_proposal(g.provider.storage(), *p)
                        .map_err(|e| Status::internal(format!("store_pending_proposal: {e}")))?;
                }
                _ => {
                    return Err(Status::aborted(
                        "expected ProposalMessage in Commit.by_reference",
                    ))
                }
            }
        }

        // ── by_value: inline proposals emitted directly into this commit ───
        for desc in &r.by_value {
            let proposal_type = std::str::from_utf8(&desc.proposal_type)
                .map_err(|_| Status::invalid_argument("proposal_type not UTF-8"))?;
            match proposal_type {
                "add" => {
                    let key_package = parse_key_package(&desc.key_package, &g.provider)?;
                    g.group
                        .propose_add_member_by_value(&g.provider, &g.signer, key_package)
                        .map_err(|e| {
                            Status::internal(format!("propose_add_member_by_value: {e}"))
                        })?;
                }
                "remove" => {
                    let removed_credential = BasicCredential::new(desc.removed_id.clone());
                    g.group
                        .propose_remove_member_by_credential_by_value(
                            &g.provider,
                            &g.signer,
                            &removed_credential.into(),
                        )
                        .map_err(|e| {
                            Status::internal(format!(
                                "propose_remove_member_by_credential_by_value: {e}"
                            ))
                        })?;
                }
                "externalPSK" => {
                    let external_psk = Psk::External(ExternalPsk::new(desc.psk_id.clone()));
                    let psk_id = PreSharedKeyId::new(
                        g.group.ciphersuite(),
                        g.provider.rand(),
                        external_psk,
                    )
                    .map_err(|_| Status::internal("PreSharedKeyId::new"))?;
                    g.group
                        .propose_external_psk_by_value(&g.provider, &g.signer, psk_id)
                        .map_err(|e| {
                            Status::internal(format!("propose_external_psk_by_value: {e}"))
                        })?;
                }
                "resumptionPSK" => {
                    let psk_id = PreSharedKeyId::resumption(
                        ResumptionPskUsage::Application,
                        g.group.group_id().clone(),
                        GroupEpoch::from(desc.epoch_id),
                        "B".repeat(g.group.ciphersuite().hash_length()).into_bytes(),
                    );
                    g.group
                        .propose_external_psk_by_value(&g.provider, &g.signer, psk_id)
                        .map_err(|e| {
                            Status::internal(format!(
                                "propose_external_psk_by_value (resumption): {e}"
                            ))
                        })?;
                }
                "groupContextExtensions" | "reinit" => {
                    // by_value GCE requires CommitBuilder API (proposal embedded inline)
                    // rather than the by_reference path used by GroupContextExtensionsProposal.
                    // Affects 6/~284 commit scenarios — deferred; openmls reference itself
                    // returns Unimplemented for 524/~284 GCE scenarios on its side.
                    return Err(Status::unimplemented(format!(
                        "Commit.by_value proposal_type {proposal_type:?} not yet supported"
                    )));
                }
                other => {
                    return Err(Status::invalid_argument(format!(
                        "unknown proposal_type {other:?}"
                    )))
                }
            }
        }

        let (commit, welcome_opt, _group_info) = g
            .group
            .commit_to_pending_proposals(&g.provider, &g.signer)
            .map_err(into_status)?;

        let commit_bytes = commit
            .tls_serialize_detached()
            .map_err(|e| Status::internal(format!("serialise commit: {e}")))?;
        let welcome_bytes = match welcome_opt {
            Some(w) => w
                .tls_serialize_detached()
                .map_err(|e| Status::internal(format!("serialise welcome: {e}")))?,
            None => Vec::new(),
        };
        let ratchet_tree = if r.external_tree {
            g.group
                .export_ratchet_tree()
                .tls_serialize_detached()
                .map_err(|e| Status::internal(format!("serialise ratchet tree: {e}")))?
        } else {
            Vec::new()
        };

        Ok(Response::new(CommitResponse {
            commit: commit_bytes,
            welcome: welcome_bytes,
            ratchet_tree,
        }))
    }

    // ── HandleCommit ────────────────────────────────────────────────────────
    async fn handle_commit(
        &self,
        req: Request<HandleCommitRequest>,
    ) -> Result<Response<HandleCommitResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;

        for proposal_bytes in &r.proposal {
            let msg = MlsMessageIn::tls_deserialize_exact(proposal_bytes.as_slice())
                .map_err(|_| Status::aborted("failed to deserialise proposal"))?;
            if g.messages_out.contains(&msg) {
                continue;
            }
            let processed = g
                .group
                .process_message(
                    &g.provider,
                    msg.try_into_protocol_message()
                        .map_err(|_| Status::aborted("not a ProtocolMessage"))?,
                )
                .map_err(into_status)?;
            match processed.into_content() {
                ProcessedMessageContent::ProposalMessage(p) => {
                    g.group
                        .store_pending_proposal(g.provider.storage(), *p)
                        .map_err(|e| Status::internal(format!("store_pending_proposal: {e}")))?;
                }
                _ => return Err(Status::aborted("expected ProposalMessage")),
            }
        }

        let commit_msg = MlsMessageIn::tls_deserialize_exact(r.commit.as_slice())
            .map_err(|_| Status::aborted("failed to deserialise commit"))?;
        let processed = g
            .group
            .process_message(
                &g.provider,
                commit_msg
                    .try_into_protocol_message()
                    .map_err(|_| Status::aborted("commit not a ProtocolMessage"))?,
            )
            .map_err(into_status)?;

        match processed.into_content() {
            ProcessedMessageContent::StagedCommitMessage(staged) => {
                g.group
                    .merge_staged_commit(&g.provider, *staged)
                    .map_err(into_status)?;
            }
            _ => return Err(Status::aborted("expected StagedCommitMessage")),
        }

        let epoch_authenticator = g.group.epoch_authenticator().as_slice().to_vec();
        Ok(Response::new(HandleCommitResponse {
            state_id: r.state_id,
            epoch_authenticator,
        }))
    }

    // ── HandlePendingCommit ─────────────────────────────────────────────────
    async fn handle_pending_commit(
        &self,
        req: Request<HandlePendingCommitRequest>,
    ) -> Result<Response<HandleCommitResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;
        g.group
            .merge_pending_commit(&g.provider)
            .map_err(|e| Status::aborted(format!("merge_pending_commit: {e}")))?;
        let epoch_authenticator = g.group.epoch_authenticator().as_slice().to_vec();
        Ok(Response::new(HandleCommitResponse {
            state_id: r.state_id,
            epoch_authenticator,
        }))
    }

    // ── StateAuth ──────────────────────────────────────────────────────────
    async fn state_auth(
        &self,
        req: Request<StateAuthRequest>,
    ) -> Result<Response<StateAuthResponse>, Status> {
        let r = req.into_inner();
        let groups = self.groups.lock().unwrap();
        let g = groups
            .get(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;
        Ok(Response::new(StateAuthResponse {
            state_auth_secret: g.group.epoch_authenticator().as_slice().to_vec(),
        }))
    }

    // ── Protect (encrypt an application message) ───────────────────────────
    async fn protect(
        &self,
        req: Request<ProtectRequest>,
    ) -> Result<Response<ProtectResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;

        if !r.authenticated_data.is_empty() {
            g.group.set_aad(r.authenticated_data.clone());
        }

        let msg_out: MlsMessageOut = g
            .group
            .create_message(&g.provider, &g.signer, &r.plaintext)
            .map_err(into_status)?;
        let ciphertext = msg_out
            .tls_serialize_detached()
            .map_err(|e| Status::internal(format!("serialise application msg: {e}")))?;

        Ok(Response::new(ProtectResponse { ciphertext }))
    }

    // ── Unprotect (decrypt an application message) ─────────────────────────
    async fn unprotect(
        &self,
        req: Request<UnprotectRequest>,
    ) -> Result<Response<UnprotectResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;

        let msg = MlsMessageIn::tls_deserialize_exact(r.ciphertext.as_slice())
            .map_err(|_| Status::aborted("failed to deserialise ciphertext"))?;
        let processed = g
            .group
            .process_message(
                &g.provider,
                msg.try_into_protocol_message()
                    .map_err(|_| Status::aborted("not a ProtocolMessage"))?,
            )
            .map_err(into_status)?;
        let authenticated_data = processed.aad().to_vec();
        let plaintext = match processed.into_content() {
            ProcessedMessageContent::ApplicationMessage(app) => app.into_bytes(),
            _ => return Err(Status::aborted("expected ApplicationMessage")),
        };
        Ok(Response::new(UnprotectResponse {
            plaintext,
            authenticated_data,
        }))
    }

    // ── UpdateProposal (propose own leaf-node update) ──────────────────────
    async fn update_proposal(
        &self,
        req: Request<UpdateProposalRequest>,
    ) -> Result<Response<ProposalResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;

        let join_cfg = MlsGroupJoinConfig::builder()
            .max_past_epochs(32)
            .number_of_resumption_psks(32)
            .sender_ratchet_configuration(SenderRatchetConfiguration::default())
            .use_ratchet_tree_extension(true)
            .wire_format_policy(g.wire_format_policy)
            .build();
        g.group
            .set_configuration(g.provider.storage(), &join_cfg)
            .map_err(|e| Status::internal(format!("set_configuration: {e}")))?;

        let (proposal_msg, _proposal_ref) = g
            .group
            .propose_self_update(&g.provider, &g.signer, LeafNodeParameters::default())
            .map_err(into_status)?;

        let proposal_bytes = proposal_msg
            .tls_serialize_detached()
            .map_err(|e| Status::internal(format!("serialise proposal: {e}")))?;
        let proposal_in = MlsMessageIn::tls_deserialize_exact(proposal_bytes.as_slice())
            .map_err(|e| Status::internal(format!("round-trip proposal: {e}")))?;
        g.messages_out.push(proposal_in);

        Ok(Response::new(ProposalResponse {
            proposal: proposal_bytes,
        }))
    }

    // ── RemoveProposal ──────────────────────────────────────────────────────
    async fn remove_proposal(
        &self,
        req: Request<RemoveProposalRequest>,
    ) -> Result<Response<ProposalResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;

        let join_cfg = MlsGroupJoinConfig::builder()
            .max_past_epochs(32)
            .number_of_resumption_psks(32)
            .use_ratchet_tree_extension(true)
            .wire_format_policy(g.wire_format_policy)
            .build();
        g.group
            .set_configuration(g.provider.storage(), &join_cfg)
            .map_err(|e| Status::internal(format!("set_configuration: {e}")))?;

        let removed_credential = BasicCredential::new(r.removed_id.clone());
        let (proposal_msg, _proposal_ref) = g
            .group
            .propose_remove_member_by_credential(
                &g.provider,
                &g.signer,
                &removed_credential.into(),
            )
            .map_err(into_status)?;

        let proposal_bytes = proposal_msg
            .tls_serialize_detached()
            .map_err(|e| Status::internal(format!("serialise proposal: {e}")))?;
        let proposal_in = MlsMessageIn::tls_deserialize_exact(proposal_bytes.as_slice())
            .map_err(|e| Status::internal(format!("round-trip proposal: {e}")))?;
        g.messages_out.push(proposal_in);

        Ok(Response::new(ProposalResponse {
            proposal: proposal_bytes,
        }))
    }

    // ── Export ─────────────────────────────────────────────────────────────
    async fn export(
        &self,
        req: Request<ExportRequest>,
    ) -> Result<Response<ExportResponse>, Status> {
        let r = req.into_inner();
        let groups = self.groups.lock().unwrap();
        let g = groups
            .get(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;
        let exported_secret = g
            .group
            .export_secret(g.provider.crypto(), &r.label, &r.context, r.key_length as usize)
            .map_err(into_status)?;
        Ok(Response::new(ExportResponse { exported_secret }))
    }

    // ── GroupInfo ──────────────────────────────────────────────────────────
    async fn group_info(
        &self,
        req: Request<GroupInfoRequest>,
    ) -> Result<Response<GroupInfoResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;
        let group_info_msg = g
            .group
            .export_group_info(g.provider.crypto(), &g.signer, !r.external_tree)
            .map_err(into_status)?;
        let group_info = group_info_msg
            .tls_serialize_detached()
            .map_err(|e| Status::internal(format!("serialise GroupInfo: {e}")))?;
        let ratchet_tree = if r.external_tree {
            g.group
                .export_ratchet_tree()
                .tls_serialize_detached()
                .map_err(|e| Status::internal(format!("serialise ratchet tree: {e}")))?
        } else {
            Vec::new()
        };
        Ok(Response::new(GroupInfoResponse {
            group_info,
            ratchet_tree,
        }))
    }

    // ── ExternalJoin ───────────────────────────────────────────────────────
    //
    // Joins an MLS group via an external commit against a `GroupInfo`,
    // rather than via a Welcome.
    async fn external_join(
        &self,
        req: Request<ExternalJoinRequest>,
    ) -> Result<Response<ExternalJoinResponse>, Status> {
        let r = req.into_inner();
        let provider = self.sibling()?;

        // Parse the GroupInfo message.
        let msg = MlsMessageIn::tls_deserialize_exact(r.group_info.as_slice())
            .map_err(|_| Status::aborted("failed to deserialise GroupInfo MlsMessage"))?;
        let verifiable_group_info = match msg.extract() {
            MlsMessageBodyIn::GroupInfo(g) => g,
            _ => return Err(Status::aborted("MlsMessage body was not a GroupInfo")),
        };

        let ratchet_tree = ratchet_tree_from_config(r.ratchet_tree.clone());
        let ciphersuite = verifiable_group_info.ciphersuite();

        // Fresh HSM-backed credential keypair for the joining identity.
        let signer = provider
            .generate_signer(ciphersuite.signature_algorithm())
            .map_err(|e| Status::new(Code::Internal, format!("HSM signer gen: {e:?}")))?;
        let credential = BasicCredential::new(r.identity.clone());
        let cred_with_key = CredentialWithKey {
            credential: credential.into(),
            signature_key: signer.public_key().to_vec().into(),
        };

        let wfp = wire_format_policy(r.encrypt_handshake);
        let join_cfg = MlsGroupJoinConfig::builder()
            .max_past_epochs(32)
            .number_of_resumption_psks(32)
            .sender_ratchet_configuration(SenderRatchetConfiguration::default())
            .use_ratchet_tree_extension(true)
            .wire_format_policy(wfp)
            .build();

        let builder = MlsGroup::external_commit_builder().with_config(join_cfg);
        let builder = if let Some(tree) = ratchet_tree {
            builder.with_ratchet_tree(tree)
        } else {
            builder
        };

        let (group, commit_bundle) = builder
            .build_group(&provider, verifiable_group_info, cred_with_key)
            .map_err(into_status)?
            .load_psks(provider.storage())
            .map_err(|e| Status::internal(format!("load_psks: {e}")))?
            .build(provider.rand(), provider.crypto(), &signer, |_| true)
            .map_err(|e| Status::internal(format!("external commit build: {e}")))?
            .finalize(&provider)
            .map_err(into_status)?;

        let commit_msg = commit_bundle.into_commit();
        let commit_bytes = commit_msg
            .tls_serialize_detached()
            .map_err(|e| Status::internal(format!("serialise commit: {e}")))?;

        let epoch_authenticator = group.epoch_authenticator().as_slice().to_vec();
        let interop_group = InteropGroup {
            group,
            signer,
            provider,
            wire_format_policy: wfp,
            messages_out: Vec::new(),
        };
        let mut groups = self.groups.lock().unwrap();
        let state_id = groups.len() as u32;
        groups.push(interop_group);

        Ok(Response::new(ExternalJoinResponse {
            state_id,
            commit: commit_bytes,
            epoch_authenticator,
        }))
    }

    // ── StorePSK ───────────────────────────────────────────────────────────
    //
    // Stores an external PSK secret keyed by (ciphersuite, psk_id) so it can
    // be referenced from a later ExternalPSKProposal. The `state_or_transaction_id`
    // field disambiguates: if it matches a transaction_id we minted in
    // CreateKeyPackage, store against that pending state's provider; else
    // treat it as a group state_id.
    async fn store_psk(
        &self,
        req: Request<StorePskRequest>,
    ) -> Result<Response<StorePskResponse>, Status> {
        let r = req.into_inner();
        let external_psk = Psk::External(ExternalPsk::new(r.psk_id.clone()));

        // Check transaction_id_map first.
        let pending_identity = self
            .transaction_id_map
            .lock()
            .unwrap()
            .get(&r.state_or_transaction_id)
            .cloned();

        if let Some(_identity) = pending_identity {
            let pending = self.pending.lock().unwrap();
            let p = pending.get(&r.state_or_transaction_id).ok_or_else(|| {
                Status::internal("transaction_id mapped to missing pending state")
            })?;
            let cs = p.bundle.key_package().ciphersuite();
            let psk_id = PreSharedKeyId::new(cs, p.provider.rand(), external_psk)
                .map_err(|_| Status::internal("PreSharedKeyId::new"))?;
            psk_id
                .store(&p.provider, &r.psk_secret)
                .map_err(|_| Status::internal("PSK store"))?;
        } else {
            let groups = self.groups.lock().unwrap();
            let g = groups
                .get(r.state_or_transaction_id as usize)
                .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_or_transaction_id"))?;
            let cs = g.group.ciphersuite();
            let psk_id = PreSharedKeyId::new(cs, g.provider.rand(), external_psk)
                .map_err(|_| Status::internal("PreSharedKeyId::new"))?;
            psk_id
                .store(&g.provider, &r.psk_secret)
                .map_err(|_| Status::internal("PSK store"))?;
        }

        Ok(Response::new(StorePskResponse::default()))
    }

    // ── ExternalPSKProposal ────────────────────────────────────────────────
    async fn external_psk_proposal(
        &self,
        req: Request<ExternalPskProposalRequest>,
    ) -> Result<Response<ProposalResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;

        let external_psk = Psk::External(ExternalPsk::new(r.psk_id.clone()));
        let psk_id = PreSharedKeyId::new(g.group.ciphersuite(), g.provider.rand(), external_psk)
            .map_err(|_| Status::internal("PreSharedKeyId::new"))?;

        let (proposal_msg, _proposal_ref) = g
            .group
            .propose_external_psk(&g.provider, &g.signer, psk_id)
            .map_err(|e| Status::internal(format!("propose_external_psk: {e}")))?;

        let proposal_bytes = proposal_msg
            .tls_serialize_detached()
            .map_err(|e| Status::internal(format!("serialise proposal: {e}")))?;
        let proposal_in = MlsMessageIn::tls_deserialize_exact(proposal_bytes.as_slice())
            .map_err(|e| Status::internal(format!("round-trip proposal: {e}")))?;
        g.messages_out.push(proposal_in);

        Ok(Response::new(ProposalResponse {
            proposal: proposal_bytes,
        }))
    }

    // ── ResumptionPSKProposal ──────────────────────────────────────────────
    //
    // Reference an earlier epoch's resumption PSK via PreSharedKeyId::resumption.
    // The psk_nonce here is the openmls-reference placeholder; it goes into
    // the PSK ID but doesn't gate correctness as long as both sides use the
    // same shape.
    async fn resumption_psk_proposal(
        &self,
        req: Request<ResumptionPskProposalRequest>,
    ) -> Result<Response<ProposalResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;

        let psk_id = PreSharedKeyId::resumption(
            ResumptionPskUsage::Application,
            g.group.group_id().clone(),
            GroupEpoch::from(r.epoch_id),
            "A".repeat(g.group.ciphersuite().hash_length()).into_bytes(),
        );

        let (proposal_msg, _proposal_ref) = g
            .group
            .propose_external_psk(&g.provider, &g.signer, psk_id)
            .map_err(|e| Status::internal(format!("propose_resumption_psk: {e}")))?;

        let proposal_bytes = proposal_msg
            .tls_serialize_detached()
            .map_err(|e| Status::internal(format!("serialise proposal: {e}")))?;
        let proposal_in = MlsMessageIn::tls_deserialize_exact(proposal_bytes.as_slice())
            .map_err(|e| Status::internal(format!("round-trip proposal: {e}")))?;
        g.messages_out.push(proposal_in);

        Ok(Response::new(ProposalResponse {
            proposal: proposal_bytes,
        }))
    }

    // ── Free ────────────────────────────────────────────────────────────────
    async fn free(
        &self,
        _: Request<FreeRequest>,
    ) -> Result<Response<FreeResponse>, Status> {
        // Per the upstream openmls/interop_client reference, Free is a
        // no-op: per-test-run state is GC'd when the server exits.
        Ok(Response::new(FreeResponse {}))
    }

    // ── Stubbed: remaining RPCs return UNIMPLEMENTED. See README.md ───────
    async fn group_context_extensions_proposal(
        &self,
        req: Request<GroupContextExtensionsProposalRequest>,
    ) -> Result<Response<ProposalResponse>, Status> {
        let r = req.into_inner();
        let mut groups = self.groups.lock().unwrap();
        let g = groups
            .get_mut(r.state_id as usize)
            .ok_or_else(|| Status::new(Code::InvalidArgument, "unknown state_id"))?;

        // The proto Extension carries raw (extension_type, extension_data) pairs.
        // Decode known types properly so openmls can locate RequiredCapabilities,
        // ExternalSenders, etc. in the proposal. Fall back to Unknown for anything
        // unrecognised. If the resulting extension set still contains Unknown types
        // that aren't default and aren't listed in RequiredCapabilities, auto-patch
        // the RequiredCapabilities so openmls's commit validation won't reject it.
        let mut openmls_exts: Vec<Extension> = r
            .extensions
            .into_iter()
            .map(|e| decode_proto_extension(e.extension_type, e.extension_data))
            .collect();

        // Collect any Unknown extension types (all Unknown types are non-default
        // and must be listed in RequiredCapabilities before commit validation passes).
        let unknown_types: Vec<ExtensionType> = openmls_exts
            .iter()
            .filter_map(|e| match e {
                Extension::Unknown(id, _) => Some(ExtensionType::Unknown(*id)),
                _ => None,
            })
            .collect();

        // If there are non-default Unknown types, ensure RequiredCapabilities covers them.
        if !unknown_types.is_empty() {
            let existing = openmls_exts
                .iter()
                .position(|e| matches!(e, Extension::RequiredCapabilities(_)));
            let new_rce = if let Some(pos) = existing {
                let rce = match openmls_exts.remove(pos) {
                    Extension::RequiredCapabilities(r) => r,
                    _ => unreachable!(),
                };
                let mut ext_types: Vec<ExtensionType> = rce.extension_types().to_vec();
                for et in &unknown_types {
                    if !ext_types.contains(et) {
                        ext_types.push(*et);
                    }
                }
                RequiredCapabilitiesExtension::new(&ext_types, rce.proposal_types(), rce.credential_types())
            } else {
                RequiredCapabilitiesExtension::new(&unknown_types, &[], &[])
            };
            openmls_exts.push(Extension::RequiredCapabilities(new_rce));
        }

        let extensions = Extensions::<GroupContext>::from_vec(openmls_exts)
            .map_err(|e| Status::invalid_argument(format!("invalid extensions: {e}")))?;

        let (proposal_msg, _proposal_ref) = g
            .group
            .propose_group_context_extensions(&g.provider, extensions, &g.signer)
            .map_err(|e| Status::internal(format!("propose_group_context_extensions: {e}")))?;

        let proposal_bytes = proposal_msg
            .tls_serialize_detached()
            .map_err(|e| Status::internal(format!("serialise proposal: {e}")))?;
        let proposal_in = MlsMessageIn::tls_deserialize_exact(proposal_bytes.as_slice())
            .map_err(|e| Status::internal(format!("round-trip proposal: {e}")))?;
        g.messages_out.push(proposal_in);

        Ok(Response::new(ProposalResponse {
            proposal: proposal_bytes,
        }))
    }
    async fn re_init_proposal(
        &self,
        _: Request<ReInitProposalRequest>,
    ) -> Result<Response<ProposalResponse>, Status> {
        Err(stubbed("ReInitProposal"))
    }
    async fn re_init_commit(
        &self,
        _: Request<CommitRequest>,
    ) -> Result<Response<CommitResponse>, Status> {
        Err(stubbed("ReInitCommit"))
    }
    async fn handle_pending_re_init_commit(
        &self,
        _: Request<HandlePendingCommitRequest>,
    ) -> Result<Response<HandleReInitCommitResponse>, Status> {
        Err(stubbed("HandlePendingReInitCommit"))
    }
    async fn handle_re_init_commit(
        &self,
        _: Request<HandleCommitRequest>,
    ) -> Result<Response<HandleReInitCommitResponse>, Status> {
        Err(stubbed("HandleReInitCommit"))
    }
    async fn re_init_welcome(
        &self,
        _: Request<ReInitWelcomeRequest>,
    ) -> Result<Response<CreateSubgroupResponse>, Status> {
        Err(stubbed("ReInitWelcome"))
    }
    async fn handle_re_init_welcome(
        &self,
        _: Request<HandleReInitWelcomeRequest>,
    ) -> Result<Response<JoinGroupResponse>, Status> {
        Err(stubbed("HandleReInitWelcome"))
    }
    async fn create_branch(
        &self,
        _: Request<CreateBranchRequest>,
    ) -> Result<Response<CreateSubgroupResponse>, Status> {
        Err(stubbed("CreateBranch"))
    }
    async fn handle_branch(
        &self,
        _: Request<HandleBranchRequest>,
    ) -> Result<Response<HandleBranchResponse>, Status> {
        Err(stubbed("HandleBranch"))
    }
    async fn new_member_add_proposal(
        &self,
        _: Request<NewMemberAddProposalRequest>,
    ) -> Result<Response<NewMemberAddProposalResponse>, Status> {
        Err(stubbed("NewMemberAddProposal"))
    }
    async fn create_external_signer(
        &self,
        _: Request<CreateExternalSignerRequest>,
    ) -> Result<Response<CreateExternalSignerResponse>, Status> {
        Err(stubbed("CreateExternalSigner"))
    }
    async fn add_external_signer(
        &self,
        _: Request<AddExternalSignerRequest>,
    ) -> Result<Response<ProposalResponse>, Status> {
        Err(stubbed("AddExternalSigner"))
    }
    async fn external_signer_proposal(
        &self,
        _: Request<ExternalSignerProposalRequest>,
    ) -> Result<Response<ProposalResponse>, Status> {
        Err(stubbed("ExternalSignerProposal"))
    }
}

fn stubbed(rpc: &str) -> Status {
    Status::unimplemented(format!(
        "{rpc} not yet implemented in pqctoday-mls v0.1 — see interop/README.md \
         for the full RPC port roadmap"
    ))
}

/// Decode a proto `(extension_type, extension_data)` pair into an openmls
/// [`Extension`]. The five default extension types are TLS-deserialized from
/// their raw payload bytes so openmls treats them as the proper variants —
/// otherwise it would see them as `Unknown(N)` and reject them during commit
/// validation (e.g. demand they appear in the leaf-node Capabilities list,
/// which only carries non-default types).
fn decode_proto_extension(ext_type: u32, data: Vec<u8>) -> Extension {
    use openmls::prelude::tls_codec::Deserialize as TlsDeserialize;
    let mut slice = data.as_slice();
    match ext_type as u16 {
        1 => {
            if let Ok(e) = ApplicationIdExtension::tls_deserialize(&mut slice) {
                return Extension::ApplicationId(e);
            }
        }
        2 => {
            if let Ok(e) = RatchetTreeExtension::tls_deserialize(&mut slice) {
                return Extension::RatchetTree(e);
            }
        }
        3 => {
            if let Ok(e) = RequiredCapabilitiesExtension::tls_deserialize(&mut slice) {
                return Extension::RequiredCapabilities(e);
            }
        }
        4 => {
            if let Ok(e) = ExternalPubExtension::tls_deserialize(&mut slice) {
                return Extension::ExternalPub(e);
            }
        }
        5 => {
            if let Ok(e) = ExternalSendersExtension::tls_deserialize(&mut slice) {
                return Extension::ExternalSenders(e);
            }
        }
        _ => {}
    }
    Extension::Unknown(ext_type as u16, UnknownExtension(data))
}
