#!/usr/bin/env python3
"""Generate the behaviour-record id tables for both engines from ids.json.

    python3 behaviour/gen.py            # rewrite both generated files
    python3 behaviour/gen.py --check    # exit 1 if either is stale (CI / tests)

Outputs (checked in, never hand-edited):
    rust/src/behaviour/ids.rs
    src/lib/common/BehaviourIds.h

The daemon on the appliance side reads behaviour/ids.json directly, so the
three consumers (Rust engine + KMIP server, C++ engine, daemon) cannot drift.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "behaviour" / "ids.json"
RUST_OUT = ROOT / "rust" / "src" / "behaviour" / "ids.rs"
CPP_OUT = ROOT / "src" / "lib" / "common" / "BehaviourIds.h"

BANNER = "GENERATED by behaviour/gen.py from behaviour/ids.json — do not edit by hand."


def rust_ident(name: str) -> str:
    return name.upper().replace("-", "_").replace("/", "_").replace("{", "").replace("}", "").replace(".", "_").strip("_")


def load():
    with SRC.open() as f:
        return json.load(f)


def gen_rust(t) -> str:
    o = []
    w = o.append
    w(f"//! {BANNER}")
    w("//!")
    w("//! Id tables of the 8-byte behaviour record (see `behaviour/README.md`).")
    w("//! Every function here is a plain `match`; unknown inputs map to 0 (n/a)")
    w("//! or `ALG_OTHER`, never to a panic.")
    w("")
    w("#![allow(dead_code)]")
    w("")
    w(f"pub const TABLE_VERSION: u32 = {t['version']};")
    w("")
    w("// ── src (byte 0) ─────────────────────────────────────────────────────────")
    for e in t["src"]:
        w(f"pub const SRC_{rust_ident(e['name'])}: u8 = {e['id']};")
    w("")
    w("/// `src` id for a `PQC_BEHAVIOUR_SRC` value (the three PKCS#11 producers).")
    w("pub fn src_from_name(name: &str) -> Option<u8> {")
    w("    match name {")
    for e in t["src"]:
        w(f"        \"{e['name']}\" => Some({e['id']}),")
    w("        _ => None,")
    w("    }")
    w("}")
    w("")
    for ns, body in t["op"].items():
        ident = rust_ident(ns)
        w(f"// ── op (byte 1), namespace `{ns}` ──────────────────────────────────────")
        for e in body["entries"]:
            w(f"pub const OP_{ident}_{rust_ident(e['name'])}: u8 = {e['id']};")
        w("")
        w(f"/// `op` id in the `{ns}` namespace; 0 when the name is not in the table.")
        w(f"pub fn op_{ident.lower()}(name: &str) -> u8 {{")
        w("    match name {")
        for e in body["entries"]:
            w(f"        \"{e['name']}\" => {e['id']},")
        w("        _ => 0,")
        w("    }")
        w("}")
        w("")
    w("// ── alg (byte 2) ─────────────────────────────────────────────────────────")
    w("pub const ALG_NONE: u8 = 0;")
    for e in t["alg"]["entries"]:
        w(f"pub const ALG_{rust_ident(e['name'])}: u8 = {e['id']};")
    w(f"pub const ALG_OTHER: u8 = {t['alg']['other']};")
    w("")
    w("/// `alg` id for a canonical algorithm name (`\"ML-DSA-65\"`, `\"RSA\"`, …);")
    w("/// `ALG_NONE` for an empty name, `ALG_OTHER` for one not in the table.")
    w("pub fn alg_from_name(name: &str) -> u8 {")
    w("    match name {")
    w("        \"\" => ALG_NONE,")
    for e in t["alg"]["entries"]:
        w(f"        \"{e['name']}\" => {e['id']},")
    w("        _ => ALG_OTHER,")
    w("    }")
    w("}")
    w("")
    w("/// `alg` id for a PKCS#11 (mechanism, `CKA_PARAMETER_SET`) pair. Pairs listed")
    w("/// with parameter set 0 match any parameter set. `ALG_OTHER` when unknown.")
    w("pub fn alg_from_ckm(mech: u32, param_set: u32) -> u8 {")
    w("    match (mech, param_set) {")
    exact = []
    anyps = []
    for e in t["alg"]["entries"]:
        for mech, ps in e["ckm"]:
            (anyps if ps == 0 else exact).append((int(mech, 16), ps, e["id"]))
    for mech, ps, i in exact:
        w(f"        (0x{mech:08x}, {ps}) => {i},")
    for mech, _ps, i in anyps:
        w(f"        (0x{mech:08x}, _) => {i},")
    w("        _ => ALG_OTHER,")
    w("    }")
    w("}")
    w("")
    w("// ── result (byte 3) ──────────────────────────────────────────────────────")
    for e in t["result"]:
        w(f"pub const RESULT_{rust_ident(e['name'])}: u8 = {e['id']};")
    rid = {e["name"]: e["id"] for e in t["result"]}
    w("")
    w("/// Result class of a PKCS#11 `CK_RV`.")
    w("pub fn result_from_ckr(rv: u32) -> u8 {")
    w("    match rv {")
    w(f"        0 => {rid['ok']},")
    for cls, vals in t["ckr_class"].items():
        if cls.startswith("$"):
            continue
        for v in vals:
            w(f"        0x{int(v, 16):08x} => {rid[cls]},")
    w(f"        _ => {rid['caller-error']},")
    w("    }")
    w("}")
    w("")
    w("/// Result class of a KMIP `ResultReason` variant name (`KmipResponseSent`")
    w("/// carries it as `format!(\"{:?}\", reason)`); `None` means success.")
    w("pub fn result_from_kmip_reason(reason: Option<&str>) -> u8 {")
    w("    match reason {")
    w(f"        None => {rid['ok']},")
    for cls, vals in t["kmip_reason_class"].items():
        if cls.startswith("$"):
            continue
        for v in vals:
            w(f"        Some(\"{v}\") => {rid[cls]},")
    w(f"        Some(_) => {rid['caller-error']},")
    w("    }")
    w("}")
    w("")
    w("/// Result class of an HTTP status on the admin plane.")
    w("pub fn result_from_http_status(status: u16) -> u8 {")
    w("    match status {")
    w(f"        200..=399 => {rid['ok']},")
    w(f"        401 | 403 => {rid['auth-fail']},")
    w(f"        400..=499 => {rid['caller-error']},")
    w(f"        500..=599 => {rid['internal-error']},")
    w(f"        _ => {rid['caller-error']},")
    w("    }")
    w("}")
    w("")
    w("// ── golden vectors (tests in both engines encode these) ─────────────────")
    w("/// `(src, op, alg, result, client, size_bytes, latency_us, dt_us, expected LE u64)`;")
    w("/// `dt_us == -1` means \"first record from this process\".")
    w("pub const VECTORS: &[(u8, u8, u8, u8, u8, u64, u64, i64, u64)] = &[")
    for v in vectors(t):
        w(f"    ({v['src']}, {v['op']}, {v['alg']}, {v['result']}, {v['client']}, {v['size_bytes']}, {v['latency_us']}, {v['dt_us']}, 0x{v['u64']:016x}),")
    w("];")
    return "\n".join(o) + "\n"


def vectors(t):
    src = {e["name"]: e["id"] for e in t["src"]}
    ops = {}
    for ns, body in t["op"].items():
        for e in body["entries"]:
            ops[(ns, e["name"])] = e["id"]
    alg = {e["name"]: e["id"] for e in t["alg"]["entries"]}
    alg[""] = 0
    res = {e["name"]: e["id"] for e in t["result"]}
    ns_for_src = {
        "kmip-data": "kmip", "kmip-admin": "kmip-admin", "policy": "policy",
        "p11-remoting-grpc": "pkcs11", "p11-remoting-rest": "pkcs11", "p11-local": "pkcs11",
        "tls": "tls", "auth": "auth",
    }
    out = []
    for v in t["vectors"]["entries"]:
        b = bytes.fromhex(v["hex"])
        assert len(b) == 8, v
        out.append({
            "src": src[v["src"]],
            "op": ops[(ns_for_src[v["src"]], v["op"])],
            "alg": alg[v["alg"]],
            "result": res[v["result"]],
            "client": v["client"],
            "size_bytes": v["size_bytes"],
            "latency_us": v["latency_us"],
            "dt_us": v["dt_us"],
            "u64": int.from_bytes(b, "little"),
            "hex": v["hex"],
        })
    return out


def gen_cpp(t) -> str:
    o = []
    w = o.append
    w("/*")
    w(" * Copyright (c) 2026 pqctoday")
    w(" * SPDX-License-Identifier: BSD-2-Clause")
    w(" */")
    w("")
    w(f"/* {BANNER} */")
    w("")
    w("#ifndef _SOFTHSM_V2_BEHAVIOURIDS_H")
    w("#define _SOFTHSM_V2_BEHAVIOURIDS_H")
    w("")
    w("#include <stdint.h>")
    w("#include <string.h>")
    w("")
    w("namespace BehaviourIds")
    w("{")
    w(f"\tstatic const uint32_t TABLE_VERSION = {t['version']};")
    w("")
    for e in t["src"]:
        w(f"\tstatic const uint8_t SRC_{rust_ident(e['name'])} = {e['id']};")
    w("")
    w("\tinline uint8_t srcFromName(const char* name)")
    w("\t{")
    w("\t\tif (name == NULL) return 0;")
    for e in t["src"]:
        w(f"\t\tif (strcmp(name, \"{e['name']}\") == 0) return {e['id']};")
    w("\t\treturn 0;")
    w("\t}")
    w("")
    for ns, body in t["op"].items():
        ident = rust_ident(ns)
        for e in body["entries"]:
            w(f"\tstatic const uint8_t OP_{ident}_{rust_ident(e['name'])} = {e['id']};")
        w("")
    w("\tstatic const uint8_t ALG_NONE = 0;")
    for e in t["alg"]["entries"]:
        w(f"\tstatic const uint8_t ALG_{rust_ident(e['name'])} = {e['id']};")
    w(f"\tstatic const uint8_t ALG_OTHER = {t['alg']['other']};")
    w("")
    w("\t/* alg id for a PKCS#11 (mechanism, CKA_PARAMETER_SET) pair; 0 in the table")
    w("\t   means any parameter set. ALG_OTHER when unknown. */")
    w("\tinline uint8_t algFromCkm(unsigned long mech, unsigned long paramSet)")
    w("\t{")
    w("\t\tswitch (mech)")
    w("\t\t{")
    by_mech = {}
    for e in t["alg"]["entries"]:
        for mech, ps in e["ckm"]:
            by_mech.setdefault(int(mech, 16), []).append((ps, e["id"]))
    for mech in sorted(by_mech):
        pairs = by_mech[mech]
        w(f"\t\t\tcase 0x{mech:08X}UL:")
        anyid = [i for ps, i in pairs if ps == 0]
        if anyid:
            w(f"\t\t\t\treturn {anyid[0]};")
        else:
            w("\t\t\t\tswitch (paramSet)")
            w("\t\t\t\t{")
            for ps, i in pairs:
                w(f"\t\t\t\t\tcase {ps}: return {i};")
            w("\t\t\t\t\tdefault: return ALG_OTHER;")
            w("\t\t\t\t}")
    w("\t\t\tdefault: return ALG_OTHER;")
    w("\t\t}")
    w("\t}")
    w("")
    for e in t["result"]:
        w(f"\tstatic const uint8_t RESULT_{rust_ident(e['name'])} = {e['id']};")
    rid = {e["name"]: e["id"] for e in t["result"]}
    w("")
    w("\t/* Result class of a CK_RV. */")
    w("\tinline uint8_t resultFromCkr(unsigned long rv)")
    w("\t{")
    w("\t\tswitch (rv)")
    w("\t\t{")
    w(f"\t\t\tcase 0: return {rid['ok']};")
    for cls, vals in t["ckr_class"].items():
        if cls.startswith("$"):
            continue
        for v in vals:
            w(f"\t\t\tcase 0x{int(v, 16):08X}UL:")
        w(f"\t\t\t\treturn {rid[cls]};")
    w(f"\t\t\tdefault: return {rid['caller-error']};")
    w("\t\t}")
    w("\t}")
    w("")
    w("\t/* Golden vectors: src, op, alg, result, client, size_bytes, latency_us,")
    w("\t   dt_us (-1 = first record), expected little-endian u64. */")
    w("\tstruct Vector { uint8_t src, op, alg, result, client; uint64_t sizeBytes, latencyUs; int64_t dtUs; uint64_t expected; };")
    w("\tstatic const Vector VECTORS[] = {")
    for v in vectors(t):
        w(f"\t\t{{ {v['src']}, {v['op']}, {v['alg']}, {v['result']}, {v['client']}, {v['size_bytes']}ULL, {v['latency_us']}ULL, {v['dt_us']}LL, 0x{v['u64']:016X}ULL }},")
    w("\t};")
    w(f"\tstatic const size_t VECTOR_COUNT = {len(t['vectors']['entries'])};")
    w("}")
    w("")
    w("#endif /* !_SOFTHSM_V2_BEHAVIOURIDS_H */")
    return "\n".join(o) + "\n"


def main(argv):
    t = load()
    outputs = {RUST_OUT: gen_rust(t), CPP_OUT: gen_cpp(t)}
    if "--check" in argv:
        stale = [p for p, s in outputs.items() if not p.exists() or p.read_text() != s]
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)}", file=sys.stderr)
        return 1 if stale else 0
    for p, s in outputs.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(s)
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
