//! cross_engine_cli — a thin file-based CLI bridge for the C++/Rust
//! cross-engine validation required by
//! `docs/implementation-plan-classic-mceliece-all-parameter-sets-2026-09-08.md`
//! §5.5(b): a keypair generated by one engine must be usable by the other
//! (pk/sk/ct are raw bytes, and both engines are independently verified
//! against the same official KAT vectors — this CLI is what lets that
//! wire-format claim be checked directly, not just inferred).
//!
//! Not part of the library's public API surface (examples aren't
//! re-exported), and depends on `rand`'s OS entropy source only as a
//! dev-dependency — the library itself stays `no_std` / OS-RNG-free.
//!
//! Usage:
//!   cross_engine_cli keygen  <variant> <pk_out> <sk_out>
//!   cross_engine_cli encaps  <variant> <pk_in>  <ct_out> <ss_out>
//!   cross_engine_cli decaps  <variant> <sk_in>  <ct_in>  <ss_out>

use rand::rngs::OsRng;
use std::env;
use std::fs;
use std::process::ExitCode;

macro_rules! dispatch_variant {
    ($variant:expr, $module:ident, $body:block) => {
        match $variant {
            "348864" => {
                use classic_mceliece_multi::mceliece348864 as $module;
                $body
            }
            "348864f" => {
                use classic_mceliece_multi::mceliece348864f as $module;
                $body
            }
            "460896" => {
                use classic_mceliece_multi::mceliece460896 as $module;
                $body
            }
            "460896f" => {
                use classic_mceliece_multi::mceliece460896f as $module;
                $body
            }
            "6688128" => {
                use classic_mceliece_multi::mceliece6688128 as $module;
                $body
            }
            "6688128f" => {
                use classic_mceliece_multi::mceliece6688128f as $module;
                $body
            }
            "6960119" => {
                use classic_mceliece_multi::mceliece6960119 as $module;
                $body
            }
            "6960119f" => {
                use classic_mceliece_multi::mceliece6960119f as $module;
                $body
            }
            "8192128" => {
                use classic_mceliece_multi::mceliece8192128 as $module;
                $body
            }
            "8192128f" => {
                use classic_mceliece_multi::mceliece8192128f as $module;
                $body
            }
            other => {
                eprintln!("unknown variant: {other}");
                return ExitCode::FAILURE;
            }
        }
    };
}

fn read_boxed_array<const N: usize>(path: &str) -> Box<[u8; N]> {
    let data = fs::read(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let len = data.len();
    let boxed_slice: Box<[u8]> = data.into_boxed_slice();
    boxed_slice
        .try_into()
        .unwrap_or_else(|_| panic!("{path}: expected {N} bytes, got {len}"))
}

fn main() -> ExitCode {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("usage: cross_engine_cli <keygen|encaps|decaps> <variant> <args...>");
        return ExitCode::FAILURE;
    }

    match args[1].as_str() {
        "keygen" => {
            if args.len() != 5 {
                eprintln!("usage: cross_engine_cli keygen <variant> <pk_out> <sk_out>");
                return ExitCode::FAILURE;
            }
            let (variant, pk_out, sk_out) = (args[2].as_str(), &args[3], &args[4]);
            dispatch_variant!(variant, m, {
                let mut rng = OsRng;
                let (pk, sk) = m::keypair_boxed(&mut rng);
                fs::write(pk_out, pk.as_ref()).expect("write pk");
                fs::write(sk_out, sk.as_ref()).expect("write sk");
            });
        }
        "encaps" => {
            if args.len() != 6 {
                eprintln!("usage: cross_engine_cli encaps <variant> <pk_in> <ct_out> <ss_out>");
                return ExitCode::FAILURE;
            }
            let (variant, pk_in, ct_out, ss_out) = (args[2].as_str(), &args[3], &args[4], &args[5]);
            dispatch_variant!(variant, m, {
                let pk_bytes = read_boxed_array::<{ m::CRYPTO_PUBLICKEYBYTES }>(pk_in);
                let pk = classic_mceliece_multi::PublicKey::from(pk_bytes);
                let mut rng = OsRng;
                let (ct, ss) = m::encapsulate_boxed(&pk, &mut rng);
                fs::write(ct_out, ct.as_ref()).expect("write ct");
                fs::write(ss_out, ss.as_ref()).expect("write ss");
            });
        }
        "decaps" => {
            if args.len() != 6 {
                eprintln!("usage: cross_engine_cli decaps <variant> <sk_in> <ct_in> <ss_out>");
                return ExitCode::FAILURE;
            }
            let (variant, sk_in, ct_in, ss_out) = (args[2].as_str(), &args[3], &args[4], &args[5]);
            dispatch_variant!(variant, m, {
                let sk_bytes = read_boxed_array::<{ m::CRYPTO_SECRETKEYBYTES }>(sk_in);
                let sk = classic_mceliece_multi::SecretKey::from(sk_bytes);
                let ct_bytes = read_boxed_array::<{ m::CRYPTO_CIPHERTEXTBYTES }>(ct_in);
                let ct = classic_mceliece_multi::Ciphertext::from(*ct_bytes);
                let ss = m::decapsulate_boxed(&ct, &sk);
                fs::write(ss_out, ss.as_ref()).expect("write ss");
            });
        }
        other => {
            eprintln!("unknown command: {other}");
            return ExitCode::FAILURE;
        }
    }

    ExitCode::SUCCESS
}
