#!/usr/bin/env python3
"""Provenance guard for tests/acvp/*.json — WS-0.4 of the PKCS#11 v3.2
coverage remediation plan (docs/remediation-plan-pkcs11-v32-coverage-
2026-08-29.md).

The plan's evidence ladder (§1) makes NIST ACVP mandatory wherever it
exists, RFC/SP text acceptable only where ACVP does not cover a mechanism,
and self-generated material NEVER acceptable as sole evidence. Nothing
enforced that before this script: a self-generated vector with no
provenance at all (tests/acvp/aescbc_test.json, until fix/acvp-hmac-
general-aes-kwp) sat on disk indistinguishable from a real one to anyone
not reading the file by hand.

A file passes if it has at least one of `_provenance` / `_provenance_tier3`
(a file may carry both — see eddsa_ed448_test.json, Tier 1 for the base
cases plus Tier 3 for RFC 8032 context-string cases ACVP doesn't publish),
and every block present:
  - has all five required string fields (source_url, source_release,
    retrieved, producer, source_sha256) plus `note`
  - `producer` does not read as self-generated (the exact failure this
    script exists to catch — see SELF_GENERATED_MARKERS)
  - `source_sha256` matches a live re-fetch of `source_url` (network;
    skipped with a warning, not a failure, when offline — see --offline)

This does NOT check whether a file's vector CONTENT is actually correct
for the mechanism it claims to cover, only that its stated origin is real
and hasn't silently drifted from that origin since it was pinned. Content
correctness is each implementation commit's own job (an independent
oracle re-verification, recorded in `note`).

Usage:
    python3 scripts/check_acvp_provenance.py              # full check, network fetch
    python3 scripts/check_acvp_provenance.py --offline     # skip hash re-fetch
    python3 scripts/check_acvp_provenance.py --json        # machine-readable report
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ACVP_DIR = ROOT / "tests" / "acvp"

REQUIRED_FIELDS = ("source_url", "source_release", "retrieved", "producer", "source_sha256", "note")

# Substrings that mean "this was generated by us, not sourced from a real
# standard" — the exact pattern the self-generated aescbc_test.json used
# ("Generated via Node.js crypto (OpenSSL backend), ..."). Case-insensitive.
SELF_GENERATED_MARKERS = (
    "generated via",
    "generated by",
    "node.js crypto",
    "self-generated",
    "self generated",
)

FETCH_TIMEOUT_S = 20


def find_provenance_blocks(doc: dict) -> dict[str, dict]:
    blocks = {}
    for key in ("_provenance", "_provenance_tier3"):
        if key in doc:
            blocks[key] = doc[key]
    return blocks


def check_block(key: str, block, offline: bool) -> list[str]:
    problems = []
    if not isinstance(block, dict):
        return [f"{key} is not an object"]

    # An explicit `"source_sha256": null` is a deliberate, documented "not
    # applicable" (e.g. an AFT test type whose seeds are freshly randomized
    # on every real ACVP pull, so there is no stable byte content to pin a
    # hash against at all — see lms_keygen_test.json's note). That's a
    # different, honest claim from an absent/empty field, which is just
    # incomplete. Require an unusually substantial `note` as evidence the
    # null was a deliberate call, not an oversight that happens to be null.
    sha_present = "source_sha256" in block
    sha_is_explicit_null = sha_present and block["source_sha256"] is None
    skip_hash_check = False
    if sha_is_explicit_null:
        note = block.get("note", "")
        if isinstance(note, str) and len(note.strip()) >= 200:
            skip_hash_check = True
        else:
            problems.append(
                f"{key}.source_sha256 is null but note is too short to justify why "
                "(a deliberate null needs a substantial documented reason, not just an omission)"
            )

    for field in REQUIRED_FIELDS:
        if field == "source_sha256" and skip_hash_check:
            continue
        if not isinstance(block.get(field), str) or not block[field].strip():
            problems.append(f"{key}.{field} missing or not a non-empty string")

    producer = block.get("producer", "")
    if isinstance(producer, str):
        lowered = producer.lower()
        for marker in SELF_GENERATED_MARKERS:
            if marker in lowered:
                problems.append(
                    f"{key}.producer reads as self-generated (matched {marker!r}): {producer!r}"
                )
                break

    if problems:
        # Field-shape problems make the hash re-fetch meaningless; don't
        # also report a fetch failure for an already-broken block.
        return problems

    if offline or skip_hash_check:
        return problems

    source_url = block["source_url"]
    stated_sha = block["source_sha256"].lower()
    try:
        req = urllib.request.Request(source_url, headers={"User-Agent": "pqctoday-hsm-provenance-check/1.0"})
        with urllib.request.urlopen(req, timeout=FETCH_TIMEOUT_S) as resp:
            content = resp.read()
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, OSError) as e:
        problems.append(f"{key}: could not re-fetch source_url ({e}) — run with --offline to skip this check")
        return problems

    actual_sha = hashlib.sha256(content).hexdigest()
    if actual_sha != stated_sha:
        problems.append(
            f"{key}: source_sha256 mismatch — stated {stated_sha}, live fetch of {source_url} hashes to {actual_sha}. "
            "Either the file drifted since this vector was pinned, or source_sha256 was never verified against the real source."
        )
    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--offline", action="store_true", help="skip the live source_sha256 re-fetch")
    ap.add_argument("--json", action="store_true", help="machine-readable report on stdout")
    args = ap.parse_args()

    if not ACVP_DIR.is_dir():
        print(f"ERROR: {ACVP_DIR} does not exist", file=sys.stderr)
        return 1

    files = sorted(ACVP_DIR.glob("*.json"))
    results = {}
    any_fail = False

    for f in files:
        try:
            doc = json.loads(f.read_text())
        except json.JSONDecodeError as e:
            results[f.name] = {"ok": False, "problems": [f"invalid JSON: {e}"]}
            any_fail = True
            continue

        blocks = find_provenance_blocks(doc)
        if not blocks:
            results[f.name] = {"ok": False, "problems": ["no _provenance or _provenance_tier3 block present"]}
            any_fail = True
            continue

        problems = []
        for key, block in blocks.items():
            problems.extend(check_block(key, block, args.offline))

        ok = not problems
        results[f.name] = {"ok": ok, "problems": problems, "tiers": sorted(blocks.keys())}
        if not ok:
            any_fail = True

    if args.json:
        print(json.dumps(results, indent=2))
    else:
        n_ok = sum(1 for r in results.values() if r["ok"])
        for name, r in results.items():
            if r["ok"]:
                print(f"  ✓ {name}  ({'+'.join(r['tiers'])})")
            else:
                print(f"  ✗ {name}")
                for p in r["problems"]:
                    print(f"      - {p}")
        print(f"\n{n_ok}/{len(results)} vector files have valid, {'shape-checked' if args.offline else 're-verified'} provenance.")
        if any_fail:
            print("\nFAIL — see scripts/check_acvp_provenance.py's docstring for what a passing file needs.")

    return 1 if any_fail else 0


if __name__ == "__main__":
    sys.exit(main())
