#!/usr/bin/env bash
# gen-pkcs11-provider-config-h.sh — emit src/vendor/pkcs11-provider/src/config.h
# for the WASM build.
#
# Why this exists: upstream generates config.h with meson
# (`configure_file(output: 'config.h', ...)` at the bottom of the vendored
# meson.build), but we compile the provider sources directly with emcc — no
# meson run, and config.h itself is .gitignore'd. So a clean checkout fails
# at the very first source file with `fatal error: 'config.h' file not
# found`. This script reproduces exactly the defines that meson.build's
# `conf` object sets, for the WASM target.
#
# Deliberate choices, all of which mirror or narrow meson's own logic:
#   - WORDS_BIGENDIAN is NOT set: wasm32 is little-endian.
#   - DEFAULT_PKCS11_MODULE is set to the in-process module token. Upstream
#     only sets it when p11-kit is present; here it is the compile-time
#     fallback in p11prov_module_init()'s resolution order (env
#     PKCS11_PROVIDER_MODULE -> `pkcs11-module-path` config directive ->
#     this). Pointing it at the statically-linked engine means the provider
#     works even when no openssl.cnf stanza was loaded, instead of failing
#     with "No PKCS#11 module specified". The literal is recognised by the
#     consumer's fake dlopen (pqctoday-hub/src/wasm/pkcs11_static_shim.c).
#   - P11PROV_BUILDINFO names the engine actually linked in. It is surfaced
#     verbatim in the UI (OpenSSL Studio's Algorithm Explorer prints it as
#     the provider's "Build:" line), so it must not claim an engine that is
#     not there.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_DIR="$ROOT/src/vendor/pkcs11-provider/src"
OUT="$SRC_DIR/config.h"

# Version comes from the vendored meson.build's project() line — parse it
# rather than hardcoding, so a vendor bump cannot silently desync.
MESON_BUILD="$ROOT/src/vendor/pkcs11-provider/meson.build"
VERSION="$(awk "/^  version: '/{ gsub(/.*version: '|',.*/, \"\"); print; exit }" "$MESON_BUILD")"
if [[ -z "$VERSION" ]]; then
    echo "[p11prov-config] could not parse version from $MESON_BUILD" >&2
    exit 1
fi
MAJOR="${VERSION%%.*}"
MINOR="${VERSION#*.}"
MINOR="${MINOR%%.*}"

# Which PKCS#11 engine is statically linked into the consumer binary.
# Override when linking a different one.
PKCS11_ENGINE="${PKCS11_ENGINE:-softhsmrustv3}"
if [[ "$PKCS11_ENGINE" == "softhsmrustv3" ]]; then
    RUST_TOML="$ROOT/rust/Cargo.toml"
    ENGINE_VERSION="$(awk '/^version = /{ gsub(/version = |"/, ""); print; exit }' "$RUST_TOML" 2>/dev/null || echo "")"
    BUILDINFO="Built for softhsmrustv3 ${ENGINE_VERSION:-?} (pure-Rust engine, no OpenSSL backend)"
else
    BUILDINFO="Built for SoftHSMv3 PQC Parity"
fi
BUILDINFO="${P11PROV_BUILDINFO:-$BUILDINFO}"

cat > "$OUT" <<EOF
/* GENERATED by scripts/gen-pkcs11-provider-config-h.sh — do not edit.
 *
 * Stands in for the config.h that upstream's meson build produces; see that
 * script's header for why the WASM build needs it and how each define is
 * chosen. Regenerate rather than hand-editing. */
#pragma once

#define PACKAGE_NAME "pkcs11-provider"
#define PACKAGE_MAJOR $MAJOR
#define PACKAGE_MINOR $MINOR

#define P11PROV_VERSION "$VERSION"
#define P11PROV_BUILDINFO "$BUILDINFO"

/* Compile-time fallback module path — resolved by the consumer's static
 * dlopen shim to the in-process engine (no real shared object exists in a
 * WASM build). */
#define DEFAULT_PKCS11_MODULE "wasm:softhsmv3"

/* Emscripten provides dlfcn.h; the symbols it declares are satisfied by the
 * consumer's pkcs11_static_shim.c rather than by real dynamic linking. */
#define HAVE_DLFCN_H 1
EOF

echo "[p11prov-config] wrote $OUT"
echo "[p11prov-config]   version   : $VERSION"
echo "[p11prov-config]   buildinfo : $BUILDINFO"
