directories.tokendir = /Users/pqctoday/Antigravity/pqctoday-hsm/build_audit_0812/p11_v32_compliance_workdir/tokens/
objectstore.backend = file
log.level = DEBUG
slots.removable = false
log.backend = file
log.file = /Users/pqctoday/Antigravity/pqctoday-hsm/build_audit_0812/p11_v32_compliance_workdir/softhsm2.log
