/*
 * Copyright (c) 2026 pqctoday
 * SPDX-License-Identifier: BSD-2-Clause
 */

/* GENERATED by behaviour/gen.py from behaviour/ids.json — do not edit by hand. */

#ifndef _SOFTHSM_V2_BEHAVIOURIDS_H
#define _SOFTHSM_V2_BEHAVIOURIDS_H

#include <stdint.h>
#include <string.h>

namespace BehaviourIds
{
	static const uint32_t TABLE_VERSION = 1;

	static const uint8_t SRC_KMIP_DATA = 1;
	static const uint8_t SRC_KMIP_ADMIN = 2;
	static const uint8_t SRC_POLICY = 3;
	static const uint8_t SRC_P11_REMOTING_GRPC = 4;
	static const uint8_t SRC_P11_REMOTING_REST = 5;
	static const uint8_t SRC_P11_LOCAL = 6;
	static const uint8_t SRC_TLS = 7;
	static const uint8_t SRC_AUTH = 8;

	inline uint8_t srcFromName(const char* name)
	{
		if (name == NULL) return 0;
		if (strcmp(name, "kmip-data") == 0) return 1;
		if (strcmp(name, "kmip-admin") == 0) return 2;
		if (strcmp(name, "policy") == 0) return 3;
		if (strcmp(name, "p11-remoting-grpc") == 0) return 4;
		if (strcmp(name, "p11-remoting-rest") == 0) return 5;
		if (strcmp(name, "p11-local") == 0) return 6;
		if (strcmp(name, "tls") == 0) return 7;
		if (strcmp(name, "auth") == 0) return 8;
		return 0;
	}

	static const uint8_t OP_KMIP_CREATE = 1;
	static const uint8_t OP_KMIP_CREATEKEYPAIR = 2;
	static const uint8_t OP_KMIP_REGISTER = 3;
	static const uint8_t OP_KMIP_REKEY = 4;
	static const uint8_t OP_KMIP_DERIVEKEY = 5;
	static const uint8_t OP_KMIP_CERTIFY = 6;
	static const uint8_t OP_KMIP_RECERTIFY = 7;
	static const uint8_t OP_KMIP_LOCATE = 8;
	static const uint8_t OP_KMIP_CHECK = 9;
	static const uint8_t OP_KMIP_GET = 10;
	static const uint8_t OP_KMIP_GETATTRIBUTES = 11;
	static const uint8_t OP_KMIP_GETATTRIBUTELIST = 12;
	static const uint8_t OP_KMIP_ADDATTRIBUTE = 13;
	static const uint8_t OP_KMIP_MODIFYATTRIBUTE = 14;
	static const uint8_t OP_KMIP_DELETEATTRIBUTE = 15;
	static const uint8_t OP_KMIP_OBTAINLEASE = 16;
	static const uint8_t OP_KMIP_GETUSAGEALLOCATION = 17;
	static const uint8_t OP_KMIP_ACTIVATE = 18;
	static const uint8_t OP_KMIP_REVOKE = 19;
	static const uint8_t OP_KMIP_DESTROY = 20;
	static const uint8_t OP_KMIP_ARCHIVE = 21;
	static const uint8_t OP_KMIP_RECOVER = 22;
	static const uint8_t OP_KMIP_VALIDATE = 23;
	static const uint8_t OP_KMIP_QUERY = 24;
	static const uint8_t OP_KMIP_CANCEL = 25;
	static const uint8_t OP_KMIP_POLL = 26;
	static const uint8_t OP_KMIP_NOTIFY = 27;
	static const uint8_t OP_KMIP_PUT = 28;
	static const uint8_t OP_KMIP_REKEYKEYPAIR = 29;
	static const uint8_t OP_KMIP_DISCOVERVERSIONS = 30;
	static const uint8_t OP_KMIP_ENCRYPT = 31;
	static const uint8_t OP_KMIP_DECRYPT = 32;
	static const uint8_t OP_KMIP_SIGN = 33;
	static const uint8_t OP_KMIP_SIGNATUREVERIFY = 34;
	static const uint8_t OP_KMIP_MAC = 35;
	static const uint8_t OP_KMIP_MACVERIFY = 36;
	static const uint8_t OP_KMIP_RNGRETRIEVE = 37;
	static const uint8_t OP_KMIP_RNGSEED = 38;
	static const uint8_t OP_KMIP_HASH = 39;
	static const uint8_t OP_KMIP_CREATESPLITKEY = 40;
	static const uint8_t OP_KMIP_JOINSPLITKEY = 41;
	static const uint8_t OP_KMIP_IMPORT = 42;
	static const uint8_t OP_KMIP_EXPORT = 43;
	static const uint8_t OP_KMIP_LOG = 44;
	static const uint8_t OP_KMIP_LOGIN = 45;
	static const uint8_t OP_KMIP_LOGOUT = 46;
	static const uint8_t OP_KMIP_DELEGATEDLOGIN = 47;
	static const uint8_t OP_KMIP_ADJUSTATTRIBUTE = 48;
	static const uint8_t OP_KMIP_SETATTRIBUTE = 49;
	static const uint8_t OP_KMIP_SETENDPOINTROLE = 50;
	static const uint8_t OP_KMIP_PKCS11 = 51;
	static const uint8_t OP_KMIP_INTEROP = 52;
	static const uint8_t OP_KMIP_REPROVISION = 53;
	static const uint8_t OP_KMIP_SETDEFAULTS = 54;
	static const uint8_t OP_KMIP_SETCONSTRAINTS = 55;
	static const uint8_t OP_KMIP_GETCONSTRAINTS = 56;
	static const uint8_t OP_KMIP_QUERYASYNCHRONOUSREQUESTS = 57;
	static const uint8_t OP_KMIP_PROCESS = 58;
	static const uint8_t OP_KMIP_PING = 59;
	static const uint8_t OP_KMIP_CREATEGROUP = 60;
	static const uint8_t OP_KMIP_OBLITERATE = 61;
	static const uint8_t OP_KMIP_CREATEUSER = 62;
	static const uint8_t OP_KMIP_CREATECREDENTIAL = 63;
	static const uint8_t OP_KMIP_DEACTIVATE = 64;
	static const uint8_t OP_KMIP_ENCAPSULATE = 65;
	static const uint8_t OP_KMIP_DECAPSULATE = 66;

	static const uint8_t OP_KMIP_ADMIN_HEALTHZ = 1;
	static const uint8_t OP_KMIP_ADMIN_VERSION = 2;
	static const uint8_t OP_KMIP_ADMIN_OPENAPI_YAML = 3;
	static const uint8_t OP_KMIP_ADMIN_API_V1_POLICIES = 4;
	static const uint8_t OP_KMIP_ADMIN_API_V1_POLICIES_NAME = 5;
	static const uint8_t OP_KMIP_ADMIN_API_V1_ACTIVE = 6;
	static const uint8_t OP_KMIP_ADMIN_API_V1_VALIDATE = 7;
	static const uint8_t OP_KMIP_ADMIN_API_V1_DRY_RUN = 8;
	static const uint8_t OP_KMIP_ADMIN_API_V1_AUDIT = 9;
	static const uint8_t OP_KMIP_ADMIN_API_V1_AUDIT_STREAM = 10;
	static const uint8_t OP_KMIP_ADMIN_API_V1_ACTIVE_MODULES = 11;
	static const uint8_t OP_KMIP_ADMIN_API_V1_ACTIVE_MODULES_NAME = 12;
	static const uint8_t OP_KMIP_ADMIN_API_V1_CONFIG_UNCOVERED_OPS = 13;

	static const uint8_t OP_POLICY_DENY = 1;
	static const uint8_t OP_POLICY_WARN = 2;
	static const uint8_t OP_POLICY_REKEY_PLANNED = 3;
	static const uint8_t OP_POLICY_ACTIVATED = 4;

	static const uint8_t OP_PKCS11_C_SIGNINIT = 1;
	static const uint8_t OP_PKCS11_C_SIGN = 2;
	static const uint8_t OP_PKCS11_C_SIGNFINAL = 3;
	static const uint8_t OP_PKCS11_C_VERIFYINIT = 4;
	static const uint8_t OP_PKCS11_C_VERIFY = 5;
	static const uint8_t OP_PKCS11_C_VERIFYFINAL = 6;
	static const uint8_t OP_PKCS11_C_GENERATEKEYPAIR = 7;
	static const uint8_t OP_PKCS11_C_ENCAPSULATEKEY = 8;
	static const uint8_t OP_PKCS11_C_DECAPSULATEKEY = 9;

	static const uint8_t OP_TLS_KMIP = 1;
	static const uint8_t OP_TLS_ADMIN = 2;

	static const uint8_t OP_AUTH_KMIP_CREDENTIAL = 1;
	static const uint8_t OP_AUTH_KMIP_TLS_HANDSHAKE = 2;
	static const uint8_t OP_AUTH_REMOTING_PIN = 3;

	static const uint8_t ALG_NONE = 0;
	static const uint8_t ALG_ML_DSA_44 = 1;
	static const uint8_t ALG_ML_DSA_65 = 2;
	static const uint8_t ALG_ML_DSA_87 = 3;
	static const uint8_t ALG_ML_KEM_512 = 4;
	static const uint8_t ALG_ML_KEM_768 = 5;
	static const uint8_t ALG_ML_KEM_1024 = 6;
	static const uint8_t ALG_SLH_DSA_SHA2_128S = 7;
	static const uint8_t ALG_SLH_DSA_SHAKE_128S = 8;
	static const uint8_t ALG_SLH_DSA_SHA2_128F = 9;
	static const uint8_t ALG_SLH_DSA_SHAKE_128F = 10;
	static const uint8_t ALG_SLH_DSA_SHA2_192S = 11;
	static const uint8_t ALG_SLH_DSA_SHAKE_192S = 12;
	static const uint8_t ALG_SLH_DSA_SHA2_192F = 13;
	static const uint8_t ALG_SLH_DSA_SHAKE_192F = 14;
	static const uint8_t ALG_SLH_DSA_SHA2_256S = 15;
	static const uint8_t ALG_SLH_DSA_SHAKE_256S = 16;
	static const uint8_t ALG_SLH_DSA_SHA2_256F = 17;
	static const uint8_t ALG_SLH_DSA_SHAKE_256F = 18;
	static const uint8_t ALG_HSS = 19;
	static const uint8_t ALG_XMSS = 20;
	static const uint8_t ALG_XMSSMT = 21;
	static const uint8_t ALG_RSA = 22;
	static const uint8_t ALG_ECDSA = 23;
	static const uint8_t ALG_EDDSA = 24;
	static const uint8_t ALG_ECDH = 25;
	static const uint8_t ALG_AES = 26;
	static const uint8_t ALG_HMAC = 27;
	static const uint8_t ALG_CHACHA20 = 28;
	static const uint8_t ALG_OTHER = 255;

	/* alg id for a PKCS#11 (mechanism, CKA_PARAMETER_SET) pair; 0 in the table
	   means any parameter set. ALG_OTHER when unknown. */
	inline uint8_t algFromCkm(unsigned long mech, unsigned long paramSet)
	{
		switch (mech)
		{
			case 0x00000000UL:
				return 22;
			case 0x00000001UL:
				return 22;
			case 0x00000003UL:
				return 22;
			case 0x00000006UL:
				return 22;
			case 0x00000009UL:
				return 22;
			case 0x0000000DUL:
				return 22;
			case 0x0000000EUL:
				return 22;
			case 0x0000000FUL:
				switch (paramSet)
				{
					case 1: return 4;
					case 2: return 5;
					case 3: return 6;
					default: return ALG_OTHER;
				}
			case 0x00000017UL:
				switch (paramSet)
				{
					case 1: return 4;
					case 2: return 5;
					case 3: return 6;
					default: return ALG_OTHER;
				}
			case 0x0000001CUL:
				switch (paramSet)
				{
					case 1: return 1;
					case 2: return 2;
					case 3: return 3;
					default: return ALG_OTHER;
				}
			case 0x0000001DUL:
				switch (paramSet)
				{
					case 1: return 1;
					case 2: return 2;
					case 3: return 3;
					default: return ALG_OTHER;
				}
			case 0x0000001FUL:
				switch (paramSet)
				{
					case 1: return 1;
					case 2: return 2;
					case 3: return 3;
					default: return ALG_OTHER;
				}
			case 0x0000002DUL:
				switch (paramSet)
				{
					case 1: return 7;
					case 2: return 8;
					case 3: return 9;
					case 4: return 10;
					case 5: return 11;
					case 6: return 12;
					case 7: return 13;
					case 8: return 14;
					case 9: return 15;
					case 10: return 16;
					case 11: return 17;
					case 12: return 18;
					default: return ALG_OTHER;
				}
			case 0x0000002EUL:
				switch (paramSet)
				{
					case 1: return 7;
					case 2: return 8;
					case 3: return 9;
					case 4: return 10;
					case 5: return 11;
					case 6: return 12;
					case 7: return 13;
					case 8: return 14;
					case 9: return 15;
					case 10: return 16;
					case 11: return 17;
					case 12: return 18;
					default: return ALG_OTHER;
				}
			case 0x00000034UL:
				switch (paramSet)
				{
					case 1: return 7;
					case 2: return 8;
					case 3: return 9;
					case 4: return 10;
					case 5: return 11;
					case 6: return 12;
					case 7: return 13;
					case 8: return 14;
					case 9: return 15;
					case 10: return 16;
					case 11: return 17;
					case 12: return 18;
					default: return ALG_OTHER;
				}
			case 0x00000040UL:
				return 22;
			case 0x00000041UL:
				return 22;
			case 0x00000042UL:
				return 22;
			case 0x00000043UL:
				return 22;
			case 0x00000044UL:
				return 22;
			case 0x00000045UL:
				return 22;
			case 0x00000046UL:
				return 22;
			case 0x00000047UL:
				return 22;
			case 0x00000060UL:
				return 22;
			case 0x00000063UL:
				return 22;
			case 0x00000251UL:
				return 27;
			case 0x00000252UL:
				return 27;
			case 0x00000261UL:
				return 27;
			case 0x00000262UL:
				return 27;
			case 0x00000271UL:
				return 27;
			case 0x00000272UL:
				return 27;
			case 0x000002B1UL:
				return 27;
			case 0x000002B2UL:
				return 27;
			case 0x00001040UL:
				return 23;
			case 0x00001041UL:
				return 23;
			case 0x00001042UL:
				return 23;
			case 0x00001043UL:
				return 23;
			case 0x00001044UL:
				return 23;
			case 0x00001045UL:
				return 23;
			case 0x00001046UL:
				return 23;
			case 0x00001047UL:
				return 23;
			case 0x00001048UL:
				return 23;
			case 0x00001049UL:
				return 23;
			case 0x0000104AUL:
				return 23;
			case 0x00001050UL:
				return 25;
			case 0x00001055UL:
				return 24;
			case 0x00001056UL:
				return 25;
			case 0x00001057UL:
				return 24;
			case 0x00001080UL:
				return 26;
			case 0x00001081UL:
				return 26;
			case 0x00001082UL:
				return 26;
			case 0x00001085UL:
				return 26;
			case 0x00001086UL:
				return 26;
			case 0x00001087UL:
				return 26;
			case 0x0000108AUL:
				return 26;
			case 0x00001225UL:
				return 28;
			case 0x00001226UL:
				return 28;
			case 0x0000140BUL:
				return 23;
			case 0x00002109UL:
				return 26;
			case 0x0000210AUL:
				return 26;
			case 0x0000210BUL:
				return 26;
			case 0x00004021UL:
				return 28;
			case 0x00004032UL:
				return 19;
			case 0x00004033UL:
				return 19;
			case 0x00004034UL:
				return 20;
			case 0x00004035UL:
				return 21;
			case 0x00004036UL:
				return 20;
			case 0x00004037UL:
				return 21;
			case 0x0000403CUL:
				switch (paramSet)
				{
					case 1: return 1;
					case 2: return 2;
					case 3: return 3;
					default: return ALG_OTHER;
				}
			case 0x80000100UL:
				return 27;
			case 0x80000101UL:
				return 27;
			case 0x80001057UL:
				return 24;
			default: return ALG_OTHER;
		}
	}

	static const uint8_t RESULT_OK = 0;
	static const uint8_t RESULT_POLICY_DENY = 1;
	static const uint8_t RESULT_AUTH_FAIL = 2;
	static const uint8_t RESULT_CALLER_ERROR = 3;
	static const uint8_t RESULT_INTERNAL_ERROR = 4;
	static const uint8_t RESULT_WARN_REKEY = 5;

	/* Result class of a CK_RV. */
	inline uint8_t resultFromCkr(unsigned long rv)
	{
		switch (rv)
		{
			case 0: return 0;
			case 0x000000A0UL:
			case 0x000000A1UL:
			case 0x000000A2UL:
			case 0x000000A3UL:
			case 0x000000A4UL:
			case 0x000001B8UL:
			case 0x00000100UL:
			case 0x00000101UL:
			case 0x00000102UL:
			case 0x00000103UL:
			case 0x00000104UL:
			case 0x00000105UL:
			case 0x000000B5UL:
			case 0x000000B7UL:
			case 0x000000B8UL:
				return 2;
			case 0x00000002UL:
			case 0x00000005UL:
			case 0x00000006UL:
			case 0x00000009UL:
			case 0x0000000AUL:
			case 0x00000030UL:
			case 0x00000031UL:
			case 0x00000032UL:
			case 0x00000054UL:
			case 0x000000E0UL:
			case 0x000000E1UL:
			case 0x000000E2UL:
			case 0x00000120UL:
			case 0x00000121UL:
			case 0x00000160UL:
			case 0x00000180UL:
			case 0x00000190UL:
			case 0x00000191UL:
			case 0x000001A0UL:
			case 0x000001A1UL:
				return 4;
			default: return 3;
		}
	}

	/* Golden vectors: src, op, alg, result, client, size_bytes, latency_us,
	   dt_us (-1 = first record), expected little-endian u64. */
	struct Vector { uint8_t src, op, alg, result, client; uint64_t sizeBytes, latencyUs; int64_t dtUs; uint64_t expected; };
	static const Vector VECTORS[] = {
		{ 6, 2, 2, 0, 0, 32ULL, 1500ULL, -1LL, 0xFF0A050000020206ULL },
		{ 4, 7, 5, 0, 0, 0ULL, 900ULL, 2048LL, 0x0B09000000050704ULL },
		{ 6, 1, 0, 3, 0, 0ULL, 0ULL, 1LL, 0x0000000003000106ULL },
		{ 1, 33, 3, 1, 17, 0ULL, 12000ULL, 1000000LL, 0x130D001101032101ULL },
		{ 8, 3, 0, 2, 200, 0ULL, 0ULL, 0LL, 0x000000C802000308ULL },
		{ 7, 1, 0, 0, 0, 0ULL, 0ULL, 65536LL, 0x1000000000000107ULL },
	};
	static const size_t VECTOR_COUNT = 6;
}

#endif /* !_SOFTHSM_V2_BEHAVIOURIDS_H */
