// SPDX-License-Identifier: GPL-3.0-only
//! KAT suite for `OpenMlsRustCrypto` — drives `hash`, `hmac`,
//! `hkdf_extract`, and `hkdf_expand` against the published vectors from
//! FIPS 180-4 (SHA-2), RFC 4231 (HMAC-SHA-2), and RFC 5869 (HKDF).
//!
//! Purpose: establish a byte-exact software baseline so that any future
//! regression in the RustCrypto dependency chain or in the trait dispatch
//! is caught before it can silently corrupt `PqcTodayProvider` outputs (which
//! delegate hash / HKDF to the same RustCrypto stack via `openmls_rust_crypto`
//! when the operation doesn't touch HSM key material).
//!
//! All expected values are taken verbatim from the cited standards; none
//! are generated by this codebase.

use openmls_rust_crypto::OpenMlsRustCrypto;
use openmls_traits::crypto::OpenMlsCrypto as _;
use openmls_traits::types::HashType;
use openmls_traits::OpenMlsProvider as _;

fn provider() -> OpenMlsRustCrypto {
    OpenMlsRustCrypto::default()
}

fn hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

// ── SHA-2 (FIPS 180-4 §B.1 test vectors, input "abc") ────────────────────────

#[test]
fn sha256_fips180_abc() {
    let got = provider().crypto().hash(HashType::Sha2_256, b"abc").unwrap();
    assert_eq!(
        got,
        hex("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
    );
}

#[test]
fn sha384_fips180_abc() {
    let got = provider().crypto().hash(HashType::Sha2_384, b"abc").unwrap();
    assert_eq!(
        got,
        hex("cb00753f45a35e8bb5a03d699ac65007272c32ab0eded1631a8b605a43ff5bed8086072ba1e7cc2358baeca134c825a7")
    );
}

#[test]
fn sha512_fips180_abc() {
    let got = provider().crypto().hash(HashType::Sha2_512, b"abc").unwrap();
    assert_eq!(
        got,
        hex("ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f")
    );
}

// ── HMAC-SHA-2 (RFC 4231 Test Case 1) ────────────────────────────────────────
// Key  = 0x0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b (20 bytes)
// Data = "Hi There"

const RFC4231_TC1_KEY: &[u8] = &[0x0bu8; 20];
const RFC4231_TC1_DATA: &[u8] = b"Hi There";

#[test]
fn hmac_sha256_rfc4231_tc1() {
    let got = provider()
        .crypto()
        .hmac(HashType::Sha2_256, RFC4231_TC1_KEY, RFC4231_TC1_DATA)
        .unwrap();
    assert_eq!(
        got.as_slice(),
        hex("b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7").as_slice()
    );
}

#[test]
fn hmac_sha384_rfc4231_tc1() {
    let got = provider()
        .crypto()
        .hmac(HashType::Sha2_384, RFC4231_TC1_KEY, RFC4231_TC1_DATA)
        .unwrap();
    assert_eq!(
        got.as_slice(),
        hex("afd03944d84895626b0825f4ab46907f15f9dadbe4101ec682aa034c7cebc59cfaea9ea9076ede7f4af152e8b2fa9cb6").as_slice()
    );
}

#[test]
fn hmac_sha512_rfc4231_tc1() {
    let got = provider()
        .crypto()
        .hmac(HashType::Sha2_512, RFC4231_TC1_KEY, RFC4231_TC1_DATA)
        .unwrap();
    assert_eq!(
        got.as_slice(),
        hex("87aa7cdea5ef619d4ff0b4241a1d6cb02379f4e2ce4ec2787ad0b30545e17cdedaa833b7d6b8a702038b274eaea3f4e4be9d914eeb61f1702e696c203a126854").as_slice()
    );
}

// ── HKDF (RFC 5869 §A.1) ─────────────────────────────────────────────────────
// Hash  = SHA-256
// IKM   = 0x0b0b…0b (22 bytes)
// Salt  = 0x000102…0c (13 bytes)
// Info  = 0xf0f1…f9 (10 bytes)
// L     = 42

const RFC5869_A1_IKM: &[u8] = &[
    0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b,
    0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b,
];
const RFC5869_A1_SALT: &[u8] = &[
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
];
const RFC5869_A1_INFO: &[u8] = &[
    0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9,
];

#[test]
fn hkdf_sha256_rfc5869_a1_extract() {
    let prk = provider()
        .crypto()
        .hkdf_extract(HashType::Sha2_256, RFC5869_A1_SALT, RFC5869_A1_IKM)
        .unwrap();
    assert_eq!(
        prk.as_slice(),
        hex("077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5").as_slice()
    );
}

#[test]
fn hkdf_sha256_rfc5869_a1_expand() {
    let prk = hex("077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5");
    let okm = provider()
        .crypto()
        .hkdf_expand(HashType::Sha2_256, &prk, RFC5869_A1_INFO, 42)
        .unwrap();
    assert_eq!(
        okm.as_slice(),
        hex("3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865")
            .as_slice()
    );
}

// ── HKDF-SHA-384 (RFC 5869 §A.1 inputs, SHA-384 variant) ─────────────────────

#[test]
fn hkdf_sha384_extract() {
    let prk = provider()
        .crypto()
        .hkdf_extract(HashType::Sha2_384, RFC5869_A1_SALT, RFC5869_A1_IKM)
        .unwrap();
    assert_eq!(
        prk.as_slice(),
        hex("704b39990779ce1dc548052c7dc39f303570dd13fb39f7acc564680bef80e8dec70ee9a7e1f3e293ef68eceb072a5ade")
            .as_slice()
    );
}

#[test]
fn hkdf_sha384_expand() {
    let prk =
        hex("704b39990779ce1dc548052c7dc39f303570dd13fb39f7acc564680bef80e8dec70ee9a7e1f3e293ef68eceb072a5ade");
    let okm = provider()
        .crypto()
        .hkdf_expand(HashType::Sha2_384, &prk, RFC5869_A1_INFO, 42)
        .unwrap();
    assert_eq!(
        okm.as_slice(),
        hex("9b5097a86038b805309076a44b3a9f38063e25b516dcbf369f394cfab43685f748b6457763e4f0204fc5")
            .as_slice()
    );
}

// ── HKDF-SHA-512 (RFC 5869 §A.1 inputs, SHA-512 variant) ─────────────────────

#[test]
fn hkdf_sha512_extract() {
    let prk = provider()
        .crypto()
        .hkdf_extract(HashType::Sha2_512, RFC5869_A1_SALT, RFC5869_A1_IKM)
        .unwrap();
    assert_eq!(
        prk.as_slice(),
        hex("665799823737ded04a88e47e54a5890bb2c3d247c7a4254a8e61350723590a26c36238127d8661b88cf80ef802d57e2f7cebcf1e00e083848be19929c61b4237")
            .as_slice()
    );
}

#[test]
fn hkdf_sha512_expand() {
    let prk = hex("665799823737ded04a88e47e54a5890bb2c3d247c7a4254a8e61350723590a26c36238127d8661b88cf80ef802d57e2f7cebcf1e00e083848be19929c61b4237");
    let okm = provider()
        .crypto()
        .hkdf_expand(HashType::Sha2_512, &prk, RFC5869_A1_INFO, 42)
        .unwrap();
    assert_eq!(
        okm.as_slice(),
        hex("832390086cda71fb47625bb5ceb168e4c8e26a1a16ed34d9fc7fe92c1481579338da362cb8d9f925d7cb")
            .as_slice()
    );
}
